### ISSUE TITLE
libtbb4 problems, prevent building new opencv and bowtie2

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1016]
Trying to update opencv to the latest 4.7.0-1 that just landed means I need to build libtbb4. But: 
```
curl --connect-timeout 30 -f -L -A 'fink/0.45.99.git' -O https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb43_20150424oss_src.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  259k    0  259k    0     0   225k      0 --:--:--  0:00:01 --:--:--  225k
The SHA256 checksum of the file is incorrect. The most likely cause for this is
a corrupted or incomplete download
Expected: d03b6cb18826c3d8515ba755f27ef3a1462cf079d275221e3c1bf407e363d22b
Actual: MD5(edbba3c346d6444376c35c31408e2b52)
        SHA1(9c545f6ad61f88ca10edc45ec6482401e6e4e14c)
       
SHA256(b0b3f5c96b934ae53b32718541c1fe44addc66ea136dc42260a5a09ac02be43c)
Downloading the file "tbb43_20150424oss_src.tgz" failed.
```
Cirdan says wayback has it, at https://web.archive.org/web/20150804025507if_/https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb43_20150424oss_src.tgz so we should either use that as Source or upload that to our own mirror, or verify that it's morally equivalent to what's currently available and update our checksum.

But that package is tagged
```
Architecture: i386, x86_64
```
which means it's not available on ARM, so it blocks the reverse-dependencies opencv and bowtie2 (both nieder's) on ARM.

I don't know anything about any of this, but maybe @nieder can double-check he has a viable tarball, or compare contents with the currently-available one?

**Comment by nieder** [comment]
I've uploaded a working tarball to our SF space.
For the %m issue, I'm going to guess that it was supposed to be an inclusive addition way back in the 10.7 but age and neglect made it exclusive. To get it on ARM, try just removing the `Distribution:` field and fixing the %m conditional in CompileScript ? I don't know what it does, only that those two packages look for it.

**Comment by nieder** [comment]
Looking at later versions of libtbb, %v=2017 only adds 3 new symbols (using `nm -o` output), so it seems to be compatible with our %v=4.3. It also knows about `arm64`. Working on an update.

**Comment by nieder** [comment]
bowtie2 no longer uses tbb4, and the new libtbb handles arm64 and opencv407 can build against it.
