### ISSUE TITLE
texlive-texmf has case sensitivity problem

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#1018]
texlive-texmf-2017 installs font map files that are referenced in updmap.cfg. In the upgrade to texlife-texmf-2021, a few of those files changed their case. During a 2017 -> 2021 upgrade on a case-insensitive system, the files in question kept the old case, which broke packages parsing the list of font map files because the updated updmap.cfg expected the new case system.

This was 'fixed' in commit 9e7c8253e by changing updmap.cfg to match the file names. However, I didn't understand that the cause of the problem was the case back in texlive-texmf-2017. So on a clean texlive-texmf-2021 install, updmap.cfg doesn't match the case formatting from the 2021 font map files.

I'm thinking now that the better solution is to delete the files in question in `PreInstScript` with something like this:
```
if [ "$1" = "upgrade" ]; then
	for mapfile in algolrevived baskervillef montserrat; do
		if [ -f %p/share/texmf-dist/fonts/map/dvips/$mapfile/$mapfile.map ]; then
			echo "Removing badly cased map file $mapfile.map in prep for TL-2021 upgrade."
			rm %p/share/texmf-dist/fonts/map/dvips/$mapfile/$mapfile.map
		fi
	done
		echo "Removing badly cased map file CountriesOfEurope.map in prep for TL-2021 upgrade."
		rm %p/share/texmf-dist/fonts/map/dvips/countriesofeurope/CountriesOfEurope.map
fi
```
It searches for the files with the case from texlive-texmf-2017 and deletes them if present. If deleted, they will be replaced with the file that came with the 2021 tarball that has the correct case.

**Comment by nieder** [comment]
So I'm trying variations of the above in PreRmScript and it's not working as expected.
Here's one file's history during a test.
#### From TL-2017 clean install:
```
/sw/share/texmf-dist/fonts/map/dvips/montserrat:
total 292
-rw-r--r--  1 root  admin  295296 Jan 25  2017 montserrat.map
```
#### From TL-2021 clean install:
Notice newer timestamp and now uppercase
```
/sw/share/texmf-dist/fonts/map/dvips/montserrat:
total 292
-rw-r--r--  1 root  admin  295296 Nov  8  2019 Montserrat.map
```

#### From TL-2021 upgrading from 2017 install
(first is diagnostics during PreRmScript showing installed file, followed by rm command, followed by check that the file is gone):
```
-rw-r--r--  1 root  admin  295296 Jan 25  2017 /sw/share/texmf-dist/fonts/map/dvips/montserrat/montserrat.map
Removing badly cased map file montserrat.map in prep for TL-2021 upgrade.
ls: /sw/share/texmf-dist/fonts/map/dvips/montserrat/montserrat.map: No such file or directory
no montserrat.map file
```
Then comes my manual check for the file after TL-2021 upgrades TL-2017:
```
/sw/share/texmf-dist/fonts/map/dvips/montserrat:
total 292
-rw-r--r--  1 root  admin  295296 Nov  8  2019 montserrat.map
```

The time stamps show that the upgrade version of montserrat.map is the correct version, but why is it showing up as lowercase like in TL-2017 if it was physically deleted before the upgrade to TL-2021?

@dmacks @thesin-

**Comment by nieder** [comment]
hopefully fixed by 0e53c01eca99adeea098d5704c6acb78bf54600a. The solution was to mv/recase the files in PreInstScript. For some reason, deleting and expecting the new deb would install the correctly cased ones wasn't working.

**Comment by TheSin-** [comment]
yet an other package to mess debsums :( changing or removing files via maintenance scripts will change the files md5sums file in the deb.

I like to run `debsums -c` to make sure I don't have changed files when things aren't right to make sure.

Are you sure this is the best option for this issue (I know you have spent time on it which is why I'm asking)

**Comment by nieder** [comment]
1) The file contents are not being changed, so the checksum will not be affected.
2) The file is renamed (only a case change) during PreInstScript so that the matching file from the new texlive-texmf overwrites the old one. Because the change happens during an upgrade and before the new files are installed, the final installed file should have the correct checksum.

**Comment by TheSin-** [comment]
ohhhhh I see it's cause the old one is in the way of the new one with a case change.  How unique, in this case I 100% agree with your solution, gg!
