### ISSUE TITLE
redis for arm64

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#1023]
Here is a patch for redis on arm64, it needs to be test on intel since it modifies DEFINES it could easily be breaking intel

redis.info
```
@@ -11,11 +11,8 @@
 Source-Checksum: SHA256(2139009799d21d8ff94fc40b7f36ac46699b9e1254086299f8d3b223ca54a375)
 PatchFile: %n.patch
 PatchFile-MD5: 611ce4c53a546fd7a3d4102c22d20e04
-PatchFile2: %n-arm64.patch
-PatchFile2-MD5: 8c39595a7f7bb467f1f939d64e8fc86b
 PatchScript: <<
 	sed 's|@PREFIX@|%p|g' < %{PatchFile} | patch -p1
-	sed 's|@PREFIX@|%p|g' < %{PatchFile2} | patch -p1
 <<
```
[redis-arm64.patch](https://github.com/fink/fink-distributions/files/11436005/redis-arm64.patch)

**Comment by dmacks** [comment]
Upstream is at 7.0.11 (our current 5.0.5 is from June 2020) and there seem to be a bunch of CVE on it. Several previous releases contain comparable changes to this patch, distinguishing i386 vs other-apple. Mean time though, I'm testing this patch on 10.13...

**Comment by krbullock** [comment]
Patch looks good to me pending testing on an Intel Mac.
