### ISSUE TITLE
mesa fails with xquartz 2.8

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#1053]
The package mesa fails to build because it requires the deprecated command makedepend that shipped with Xquartz until 2.8.0
```
running makedepend
Makefile:201: depend: No such file or directory
make[3]: *** [Makefile:152: depend] Error 127
```

I have makedepend (and most of the x11 stack but not the xserver itself) in my private repo and can move it to fink-dists (or piecemeal) to satisfy this dep. It's all in %p/opt/X11, so it wouldn't interfere with existing stuff, and fink-buildenv-modules has a script to facilitate building against it as needed.

**Comment by dmacks** [comment]
It's not the first such package either. For the workaround I did for cernlib2006, see 07ce8a939145c8ac77466da4f56d81767964b1c4.
