### ISSUE TITLE
New libtiff release changes

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1056]
Upstream 4.6.0 will drop %p/bin/
* fax2ps
* fax2tiff
* pal2rgb
* ppm2tiff
* raw2tiff
* tiff2bw
* tiff2rgba
* tiffcmp
* tiffcrop
* tiffdither
* tiffgt
* tiffmedian
It looks like they will be available in git just not in the release tarball, as they are completely unsupported for a long time. Do we care?

Also, I noticed libtiff-4.pc in our current package populates Requires.private:, which triggers a bunch of inherited BuildDepends. I don't see anything in the public APIs that need them, so I recommend blanking that entry in the next release.

Pinging @nieder  who often works on this package for an opinion.

**Comment by dmacks** [comment]
The -bin are dynamically linked. We could pull a secondary tarball of those other programs' sources.

**Comment by nieder** [comment]
Doesn't matter to me. /me was only keeping it up to date as needed for other graphics editing programs.

**Comment by dmacks** [comment]
I pushed the new version d3b430683bf36ba30b31468d08d545c40f91a092 according to its main tarball, which is also what Debian does.
