### ISSUE TITLE
-Wl,-read_only_stubs is fatal in Xcode15

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#1066]
A bunch of packages (mostly orig from gecko2) use the flag `-Wl,-read_only_stubs` for hardening. That flag is now fatal in Xcode 15.

This is the list of packages that grep pulls out:
- [x] ldapvi
- [x] lynx-cur
- [x] lz4 @kamischi 
- [x] lzo2
- [x] joe
- [x] nano
- [x] nginx
- [x] netrik
- [x] openvpn
- [x] socat
- [x] whois
<s>- [ ] mikmod</s>
<s>- [ ] libmikmod3</s>

We should just remove that flag across the board and bump %r.

See fink/fink#255

```
$ man ld
...
-read_only_stubs
             [i386 only] Makes the __IMPORT segment of a final linked images read-only.  This option makes a program slightly more secure in that the JMP instructions in the i386 fast
             stubs cannot be easily overwritten by malicious code.  The downside is the dyld must use mprotect() to temporarily make the segment writable while it is binding the stubs.
```

**Comment by nieder** [comment]
See #1070 for the others

**Comment by sth0** [comment]
#1070 has patch for joe, ldapvi, lz4, lzo2, socat, lynx-cur, netrik, and nginx. which are the remaining 8.

**Comment by nieder** [comment]
#1070 has been merged. Just have fink/fink#255 to deal with dpkg bootstrapping. That'll get it's own PR there.
