### ISSUE TITLE
All r-base >= 33 unbuildable: libcurl compatibility

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1079]
While rebuilding a large chunk of our dist, I tried all of our r-base* packages. As of r-base33, they all fail during ./configure:
```
checking if libcurl is version 7 and >= 7.28.0... no
configure: error: libcurl >= 7.28.0 library and headers are required with support for https
```
This is fixed upstream as https://github.com/r-devel/r-svn/commit/972c126a9006ea664ef9ce72893282912352e89a which suggests we can simply patch the configure script in our packages to accept version 8. The question is how far back we should bother doing this, rather than simply killing off the very old r-base* altogether. I note that our curl was updated to version 8 in May (3b4320e1c622a9a12046faefcacf8b3762e8dfb5), so the fact that nobody has reported it suggests that there is not a substantial user-base for them.

**Comment by dhomeier** [comment]
I've built and tested r-base41 against libcurl 8.2.1 with this patch added to `configure`:
```patch
@@ -46035,8 +46035,8 @@
 
 
 if test "x${have_libcurl}" = "xyes"; then
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking if libcurl is version 7 and >= 7.28.0" >&5
-$as_echo_n "checking if libcurl is version 7 and >= 7.28.0... " >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking if libcurl is >= 7.28.0" >&5
+$as_echo_n "checking if libcurl is >= 7.28.0... " >&6; }
 if ${r_cv_have_curl728+:} false; then :
   $as_echo_n "(cached) " >&6
 else
@@ -46052,7 +46052,7 @@
 {
 #ifdef LIBCURL_VERSION_MAJOR
 #if LIBCURL_VERSION_MAJOR > 7
-  exit(1);
+  exit(0);
 #elif LIBCURL_VERSION_MAJOR == 7 && LIBCURL_VERSION_MINOR >= 28
   exit(0);
 #else
```
Older versions may vary more.

**Comment by dmacks** [comment]
Thanks @dhomeier that worked well. Deferring "kill older versions" until someone actually cares to act on it.
