### ISSUE TITLE
Help kill libtiff5: testing needed on 10.11 or older

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1085]
The last two packages that have dependencies on libtiff5 are
 - [ ] wxcocoa293-shlibs
 - [ ] wxwidgets300-cocoa

Both are dist-restricted to OS X 10.9 - 10.11. Could someone with access to one of those older platforms see if switching their dependencies to libtiff6 gives a comparably clean build? If so, we can finally kill off the old libtiff version.

**Comment by nieder** [comment]
I doubt there's anyone running 10.9-10.11 and using those old Wx. I say switch them and then fix if anyone complains.
