### ISSUE TITLE
tgif without xmkmf

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#11]
@akhansen this package of yours is not available in 10.13 because it uses xmkmf, which nobody has gotten working on 10.13. It looks like only the message-catalogs use imake, and this step is done manually in *Script, with the actual program instead using normal build tools. As a first-pass, could you have a separate "high revision" without message-catalogs (and therefore not needing xmkmf) for 10.13?

Looking at the build though, I see `-D_NO_LOCALE_SUPPORT` is hardcoded, which appears to disable all the internal support for translated messages via #ifndef and confirmed by checking the .libs/*.Po #include results. Without that, I'm not sure the message-catalogs are used even if xmkmf is present to enable them to be built and installed. Assuming that's true, you could drop xmkmf and the manually handled catalogs altogether on all platforms.

**Comment by akhansen** [comment]
Updated in ec0cb32922 .
