### ISSUE TITLE
unixodbc2-2.2.14-2: error: implicit declaration of function 'get_column_names' is invalid in C99

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink-distributions#1102]
Another victim of `-Werror=implicit-function-declaration` being on by default now:
```
SQLColumns.c:89:19: error: implicit declaration of function 'get_column_names' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            ret = get_column_names( cl_statement );
                  ^
1 error generated.
SQLColumnPrivileges.c:90:19: error: implicit declaration of function 'get_column_names' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            ret = get_column_names( cl_statement );
                  ^
make[1]: *** [SQLColumns.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
1 error generated.
make[1]: *** [SQLColumnPrivileges.lo] Error 1
```
(I'm on x86_64 Big Sur with Xcode 13)
cc @TheSin-

**Comment by dmacks** [comment]
This one has a huge number of them, including lots of internal functions that have no .h at all. Given we have libunixodbc3 of the current upstream majorversion and I do not see any reverse-depends on unixodbc2, maybe dist-restrict or kill it altogether?

**Comment by nieder** [comment]
Kill it. 2.2.14 is 14 years old, we have a newer version, we haven't touched this one for real in 7 years, and nothing uses it.

**Comment by dmacks** [comment]
*poof*. Also updated the newer-libversion package to its latest upstream.
