### ISSUE TITLE
`fink cleanup --all` fails to remove class-tiny-pm5184 and cpan-meta-requirements-pm5184

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink-distributions#1108]
Not sure if this is an issue with base or the packages in question, but anyways, when I do `fink cleanup --all`, it currently fails with the following message:
```
$ fink cleanup --all 
Password:
Information about 15243 packages read in 5 seconds.
Collecting active source filenames...
Obsolete sources deleted from /opt/sw/src: 0

Scanning deb collection...
Obsolete deb packages deleted from fink trees: 0

Obsolete symlinks deleted: 0

Reading buildlock packages...
	All buildlocks accounted for.

The following 2 obsolete package(s) will be removed:
               class-tiny-pm5184  1.008-1  OBSOLETE: use class-tiny-pm
   cpan-meta-requirements-pm5184  2.143-1  OBSOLETE: use cpan-meta-requirements-pm

/opt/sw/bin/dpkg-lockwait --purge class-tiny-pm5184 cpan-meta-requirements-pm5184
dpkg: dependency problems prevent removal of class-tiny-pm5184:
 path-isdev-pm5184 depends on class-tiny-pm5184 (>= 0.010-1).
 path-finddev-pm5184 depends on class-tiny-pm5184 (>= 0.010-1).
 pod-spell-pm5184 depends on class-tiny-pm5184.
 test-file-sharedir-pm5184 depends on class-tiny-pm5184.
/opt/sw/bin/dpkg: error processing class-tiny-pm5184 (--purge):
 dependency problems - not removing
dpkg: dependency problems prevent removal of cpan-meta-requirements-pm5184:
 extutils-makemaker-pm5184 depends on cpan-meta-requirements-pm5184 (>= 2.121-1).
 cpan-pm5184 depends on cpan-meta-requirements-pm5184.
 cpan-meta-check-pm5184 depends on cpan-meta-requirements-pm5184 (>= 2.121).
 cpan-meta-pm5184 depends on cpan-meta-requirements-pm5184 (>= 2.121-1).
/opt/sw/bin/dpkg: error processing cpan-meta-requirements-pm5184 (--purge):
 dependency problems - not removing
Errors were encountered while processing:
 class-tiny-pm5184
 cpan-meta-requirements-pm5184
### execution of /opt/sw/bin/dpkg-lockwait failed, exit code 1

WARNING: not all obsolete packages could be removed.
/opt/sw/sbin/fink-dpkg-status-cleanup
/opt/sw/var/lib/dpkg/status cleanup:
	keep 4470
	omit 0
```
I guess the dependencies should be updated so that they no longer depend on obsolete packages? Either that or they should be obsoleted themselves, or the obsoletions should be reversed.

**Comment by cooljeanius** [comment]
cc @danielj7 (maintainer for packages in question)

**Comment by nieder** [comment]
Something is up with only partially updated packages in your tree, but the deps should have been taken care of.

For example, this belongs to path-isdev-pm5184:
https://github.com/fink/fink-distributions/blob/3ad654f442c5c949bde84aacdf19311964b45e4c/10.9-libcxx/stable/main/finkinfo/libs/perlmods/path-isdev-pm.info#L20-L28

The unvarianted path-tiny-pm is on there, so path-isdev-pm5184 should not be needing path-tiny-pm5184 like your error message says.

**Comment by nieder** [comment]
Actually, the more I think about it, it might be that Fink sees path-tiny-pm5184 as obsolete, so cleanup tries to remove it, but you don't actually have path-tiny-pm installed yet (or the updated path-isdev-pm5184), so the removal fails on the dependency check. Have you tried to update the perlmods before running fink-cleanup?

**Comment by dmacks** [comment]
The cleanup-obsolete is being blocked here solely at the dpkg level. The dependencies at the fink .info level all appear to be fixed, as nieder notes. But until the new version of the dependant package is installed, the obsolete dependency cannot be removed because the old version of the dependant package is currently installed. Check "fink list -ot" and make sure everything is actually installed at the current version: ```i``` not ```(i)```.

**Comment by cooljeanius** [comment]
Ah ok, so I guess this is just a side-effect of #1075 still afflicting me, then...

**Comment by cooljeanius** [comment]
> Ah ok, so I guess this is just a side-effect of #1075 still afflicting me, then...

OK so yeah, re-confirming that this was essentially just a dup of #1075, and thus closing it.
