### ISSUE TITLE
Apple moved opensource.apple.com to github.com/apple-opensource

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#1111]
Several of our packages use zlib.pc to find zlib. We've been getting zlib.pc from opensource.apple.com, but that's no longer working. Their mirror is now at https://github.com/apple-opensource/zlib

**Comment by nieder** [comment]
Apparently, tarballs are still present at opensource.apple.com, but most expanded trees have been removed.
The tarballs at opensource.apple.com now have base directories like so: `llvmgcc42-llvmgcc42-2336.11`, where the package name used to be singleton in the old tarballs.

The tarballs in github are singly named in the base folder but the filestams have changed so checksums are different.

**Comment by nieder** [comment]
Only one left is llvm-gcc42, but I don't have the original tarball to compare. If anyone has that tarball, move it aside, download the new one from opensource.apple.com and diff the two extracted directories.

**Comment by TheSin-** [comment]
```
$ ls -l /opt/src/llvmgcc42-2336.11.tar.gz 
-rw-r--r-- 1 root wheel 50964714 Jan 27  2023 /opt/src/llvmgcc42-2336.11.tar.gz
```

I'll put it someplace for you as soon as I get to work, if that's the right one?

**Comment by nieder** [comment]
Should be if the root directory is `llvmgcc42-2336.11`. If it is `llvmgcc42-llvmgcc42-2336.11` (double llvmgcc42), then it's the new one. sha256: 1bdb98d11abc91afa17b0d79735856e20b450aed178c79ba753b4f50054f4205

**Comment by TheSin-** [comment]
```
$ shasum -a 256 /opt/src/llvmgcc42-2336.11.tar.gz 
1bdb98d11abc91afa17b0d79735856e20b450aed178c79ba753b4f50054f4205  /opt/src/llvmgcc42-2336.11.tar.gz
```

darn

**Comment by nieder** [comment]
I was unclear. 1bdb98d11abc91afa17b0d79735856e20b450aed178c79ba753b4f50054f4205 is for the old tarball.
