### ISSUE TITLE
libunistring refactoring broken with InfoDocs

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#1112]
* libunistring2 no longer has `%p/share/info/libunistring.info` but still has `InfoDocs: libunistring.info`.
* libunistring5 moved libunistring.info out of base package but base package (now -shlibs) still has `InfoDocs: libunistring.info`.

**Comment by dmacks** [comment]
Fixed in [10edfe2](https://github.com/fink/fink-distributions/commit/10edfe2ee17774997b6099011229818d2089eb0c)

Can't wait for new-dpkg that makes InfoDocs needless.
