### ISSUE TITLE
Trouble Installing Fink on MacOS Ventura 13.6

### ISSUE THREAD

**Issue by jpajs** [fink/fink-distributions#1118]
Hello I am trying to install the fink software. I have double checked that I have Java, Xcode, XQuartz and a MacOS version 10.7 or later. I tried uninstalling Homebrew as mentioned in a previous thread but also no luck. No matter how hard I try to install it (manually or using the installation software on Git), I get the following error:

Fink must be installed and run with superuser (root) privileges. Fink can
automatically try to become root when it's run from a user account. Since
you're currently running this script as a normal user, the method you choose
will also be used immediately for this script. Available methods:

(1) Use sudo
(2) Use su
(3) None, fink must be run as root

Choose a method: [1] 1

Checking package... looks good (fink-0.45.6).
Checking system... i386-apple-darwin22.6.0
13.6 does not match the expected value of 10.18. Please run fink selfupdate to download a newer version of fink at /Downloads/fink/perlmod/Fink/Services.pm line 1430.
logout

Please help with this.

**Comment by sth0** [comment]
That is an older version of fink that you are trying to install.  There hasn’t been a newer packaged version and you should download fink from the git repository.  It seems that your version is before Apple started renumbering things from the older 10.XX versions of the OS.

To install from scratch, here is the following commands:
(Change to a directory you want to put the source in)
git clone https://github.com/fink/fink
cd fink
git checkout master
sudo ./bootstrap
This should get you going.  It would be helpful if a tarball was put on the project page.

Let us know if there are any other issues.
-Scott

**Comment by jpajs** [comment]
Thank you so much this was very helpful. I have one last question. What does this section mean? According to the git help page this requires me to "enter the numbers corresponding to my location" but how am I supposed to determine that?

Mirror selection

The Fink team maintains mirrors known as "Master" mirrors, which contain the
sources for all fink packages. You can choose to use these mirrors first, last,
never, or mixed in with regular mirrors. If you don't care, just select the
default.

**Comment by jpajs** [comment]
Update: I just pressed 'return' and then it asked me a bunch of choose mirror for questions for which I just chose 'primary'. but then I got this error, so I gave up and will try again:


BOOTSTRAP PHASE ONE: download tarballs.

curl --connect-timeout 30 -f -L -A 'fink/0.45.99.git' -O http://distfiles.master.finkmirrors.net/distfiles/tar-1.29.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   275  100   275    0     0    187      0  0:00:01  0:00:01 --:--:--   188
100 2652k  100 2652k    0     0   988k      0  0:00:02  0:00:02 --:--:-- 3233k
curl --connect-timeout 30 -f -L -A 'fink/0.45.99.git' -O http://distfiles.master.finkmirrors.net/distfiles/dpkg_1.19.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   277  100   277    0     0   1621      0 --:--:-- --:--:-- --:--:--  1619
  0  1806    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
### execution of curl failed, exit code 22
Downloading the file "dpkg_1.19.7.tar.gz" failed.

(1)	Give up
(2)	Retry the same mirror
(3)	Retry another mirror from your continent
(4)	Retry another mirror
(5)	Retry using next mirror set "sourceforge"

Default answer will be chosen in 120 seconds...
How do you want to proceed? [3] 1
file download failed for dpkg_1.19.7.tar.gz of package dpkg-bootstrap-1.19.7-1

**Comment by sth0** [comment]
You can set the mirrors to be local to your “location” so that you are not creating a lot of trans-pacific traffic etc.  Thus you can pick North America, Asia etc. as your location for mirrors.  The mirrors should synchronize and you are best served by nearby mirrors.

-Scott

**Comment by sth0** [comment]
Don’t give up!   Never, never give up……  :-)

That just means that the mirror selected did not have that source code (for dpkg 1.19.7).  Try the original code mirror (ie Sourceforce) in this case.  The default will try different hosts and eventually try that as an option.

99.9% of the time you are OK to use the defaults.

-Scott

**Comment by jpajs** [comment]
I'm trying to install new package now but it still won't work. For context I also ran this script again from the fink documentation: 
fink selfupdate
fink selfupdate-rsync
fink index -f
fink selfupdate

Here is the exact error for the one and the other package download keeps failing:

The core packages have been updated. You should now update the other packages
using commands like 'fink update-all'.

Joys-MBP-2:~ joypajarla$ fink install netpbm
Information about 14727 packages read in 3 seconds.
Failed: no package found for specification 'netpbm'!
Joys-MBP-2:~ joypajarla$ fink install imagemagick-nox
Information about 14727 packages read in 2 seconds.

fink needs help picking an alternative to satisfy a virtual dependency. The
candidates:

(1)	ghostscript: Interpreter for PostScript and PDF
(2)	ghostscript-esp: Ghostscript with better CJK and cups support
(3)	ghostscript-nox: Interpreter for PostScript and PDF

**Comment by jpajs** [comment]
Hmm actually I was able to figure this out... I was making an error in calling netpbm. Apparently it is now called netpbm11

**Comment by sth0** [comment]
There is no package called exactly “netpbm” which is why it won’t install.  Try listing netpbm packages with the “fink list netpbm”

You will find 3 packages, “netpbm11”, "netpbm-bin”, and "netpbm11-shlibs”.  These are versioned for large changes in the API so you want to install netpbm11.  Which is really version 11.3.4.

fink install netpbm11

-Scott

**Comment by jpajs** [comment]
What is the difference between netpbm11 and netpbm? I used 'fink dumpinfo netpbm11' to find more information on it and it has the following lines:

replaces: netpbm-bin (<< 10.63.01-2), netpbm, netpbm10
conflicts: netpbm, netpbm10

When I try to use this package, I get the following error 'pnmsmooth not found'. But according to Sourceforge 'pnmsmooth' must be a component of netpbm?

**Comment by dhomeier** [comment]
They are different versions, which have mutually incompatible libraries as noted above, thus Fink needs to keep them in different packages, and netpbm11-shlibs (providing the 11.x version of the library) conflicts with the 10.x version of netpbm-bin; however it also includes netpbm-bin-11.3.4 (shown under _splitoffs_ by `fink dumpinfo netpbm11-shlibs`), which includes the run-time binaries.
So `fink install netpbm-bin` should provide you with `pnmsmooth` version 11.3.4.

**Comment by nieder** [comment]
Closing since OP was able to install fink itself from the original topic
