### ISSUE TITLE
Trouble accessing 'pnmsmooth' in Netpbm11 fink install

### ISSUE THREAD

**Issue by jpajs** [fink/fink-distributions#1119]
What is the difference between netpbm11 and netpbm? I used fink to install this package. I used 'fink dumpinfo netpbm11' to find more information on it and it has the following lines:

replaces: netpbm-bin (<< 10.63.01-2), netpbm, netpbm10
conflicts: netpbm, netpbm10

When I try to use this package as a part of VMD, I get the following error 'pnmsmooth not found'. But according to Sourceforge 'pnmsmooth' must be a component of netpbm?

**Comment by nieder** [comment]
netpbm11 are the headers and other files needed for things that compile using the netpbm libraries. You want netpbm-bin, which includes the end user programs: https://pdb.finkproject.org/pdb/filefind.php?search=pnmsmooth&match_type=contains&dist_name=default&architecture=any&tree=any&submit=Search

In Terminal, `dpkg -L <PKGNAME>` will tell you what files are in an installed package. `dpkg -S <FILENAME>` will tell you what package an installed file comes from. And the above link is a search engine that looks through all our packages and tells you what you package it comes from.

**Comment by nieder** [comment]
Assuming this is fixed for your VMD by installing netpbm-bin
