### ISSUE TITLE
Time to kill texi2html?

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1120]
We rooted out its reverse-depends almost two years ago,[#910] Debian dropped it a decade ago,[[1]](https://lists.debian.org/debian-devel/2013/05/msg01516.html) and upstream formally abandoned it over a decade ago. Our current package requires the increasingly-unmaintainable perl-5.16.2. The latest upstream doesn't even pass tests with that (and Debian reports likewise). Time to just nuke the whole thing?

**Comment by nieder** [comment]
Don't know why we kept it after deprecating it. No reason to keep it.
