### ISSUE TITLE
Broken dep: no such package libleveldb for node-leveldown

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1126]
I don't see any matching or similar package-name.

**Comment by TheSin-** [comment]
is it dist restricted I'll have to look at this, no idea how I got this to work, maybe there is a provides?

```
$ fink list leveldb
Information about 15046 packages read in 26 seconds.
     leveldb-doc      1.22-1       LevelDB documentation
 i   libleveldb-dev   1.22-1       Fast key-value storage library (dev files)
 i   libleveldb1-shl  1.22-1       Fast key-value storage library
```

**Comment by dmacks** [comment]
Maybe something from a private repo leaked out?

**Comment by TheSin-** [comment]
forsure possible, I was really careful but I could have missed it, I'll check as soon as I have a few cycles

**Comment by TheSin-** [comment]
```
grep -r libleveldb *
libs/nodemods/node-leveldown.info:	libleveldb-dev,
libs/nodemods/node-leveldown.info:	libleveldb1-shlibs,
```

I see no calls at all for `libleveldb`

**Comment by dmacks** [comment]
Yes, those are the broken deps (my original filing was not the exact package-names). Grepping my whole finkinfo/ tree, this is the only file that mentions "leveldb" at all; `fink list leveldb` has nothing. What is `fink dumpinfo -finfofile leveldb-dev` for you?
