### ISSUE TITLE
expat-2.6.0 breaks pythonXX build

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#1129]
Python-upstream confirms there are test-failures due to the just-released expat-2.6.0 and has fixes. https://github.com/python/cpython/issues/115133

_Originally posted by @dmacks in https://github.com/fink/fink-distributions/issues/996#issuecomment-1974405056_

**Comment by dmacks** [comment]
Upstream has fixed python38 and above, so we can grab their patches:
- [ ] python310
- [ ] python39
- [ ] python38
Several suits of packages and a few one-offs are hardcoded to python37, so we should look at backporting a fix there:
- [ ] python37
Fink has dist-restricted python{34,35,36} to OS X 10.15 and below. Should we bother keeping 34/35/36 limping along by trying to backport upstream's fixes for newer pythonXX, or use this as a chance to kill them outright?
- [ ] python36
- [ ] python35
- [ ] python34
Some packages are pinned to python27, so we should look at backporting a fix there:
- [ ] python27

**Comment by dmacks** [comment]
Upstream patch does not apply cleanly to 36 and below (nor to 27's, where the test failure looks different also)

**Comment by nieder** [comment]
py34-36 are already dist restricted. If they can't be patched for this failure with only minimal effort, then the test can be easily skipped. That's less effort than deleting python3[456].info and modifying all existing *-py.info to remove relevant variants. Is there any indication that expat-2.6 breaks actual python function or just tickles that test?

**Comment by dmacks** [comment]
Python36 and below also are failing test_minidom; again looks like a test bug, as copying that test suite from newer pythonXX clears it on python{35,36}. On older, it doesn't apply as cleanly...still working on it.
