### ISSUE TITLE
net-delicious-pm source missing

### ISSUE THREAD

**Issue by dhomeier** [fink/fink-distributions#1179]
`Net-Delicious-1.14.tar.gz` on all Fink mirrors just includes a giant bunch of HTML garbage afaict, and none of the CPAN mirrors seem to have the source anymore at all – closest are `Net-Delicious-Export-Post-XBEL-1.4.tar.gz` and `Net-Delicious-Export-1.2.tar.gz`, but those appear rather older.

**Comment by nieder** [comment]
I've uploaded a good copy of Net-Delicious-1.14.tar.gz from my HD to SF
