### ISSUE TITLE
launch does not build on Xcode 16

### ISSUE THREAD

**Issue by sth0** [fink/fink-distributions#1193]
I am not sure how it builds on previous versions either.  I think it is the same failure on arm64 and x86_64

```
/opt/sw/src/fink.build/launch-1.2.5-1/launch-1.2.5/launch.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 15.1.99. (in target 'launch' from project 'launch')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'launch' from project 'launch')
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'launch' from project 'launch')
** BUILD FAILED **


The following build commands failed:
	Ld /opt/sw/src/fink.build/launch-1.2.5-1/launch-1.2.5/launch.build/launch.build/Objects-normal/x86_64/Binary/launch normal x86_64 (in target 'launch' from project 'launch')
(1 failure)
```
It seems that Xcode 16 cannot build pre macOS 11 code.  Should there be a Distribution version for 10.15 and previous and one for macOS 11+ that has a different deployment target?  I think I can patch the Xcode project for modern systems.

**Comment by nieder** [comment]
upstream commit for dealing with Xcode12.4+, which doesn't help with the MACOSX_DEPLOYMENT_TARGET issue, but gets some possible fixes for other Xcode problems that may arise.
https://github.com/nriley/launch/commit/0248d0583bf2dcccf9177cc86151cd90d7215d02

Why set MACOSX_DEPLOYMENT_TARGET to 11.0 vs 10.13 like the error suggests?

If MACOSX_DEPLOYMENT_TARGET needs to be edited to 11.0, I think it would be easiest to make new .info called `launch-1.2.5.info`, with `Distribution: 10.9, 10.10, 10.11, 10.12, 10.13, 10.14, 10.14.5, 10.15` with no changes from current .info, and update current .info to have `Distribution: 11.0, 11.3, 12.0, 13.0, 14.0, 15.0` and an updated MACOSX_DEPLOYMENT_TARGET in `launch.xcodeproj/project.pbxproj`

**Comment by sth0** [comment]
If I open the project in Xcode, it does not give me the option of 10.13 as a deployment target.  But even so there seems to be errors in the build process due to old code.  Unfortunately it is a dependency in some of the other more essential packages such as gsasl and dbus.

**Comment by nieder** [comment]
If you apply the patch from upstream manually (and change its `10.9` to either `10.13` or `11.0`), can you build launch outside of Fink following the CompileScript commands from the .info?

**Comment by sth0** [comment]
Changed the patch to modify 10.8 -> 10.13 and it compiles and runs in 15.1 / 16.1 (os/xcode).   Should I make a version for distribution for 10.9, 10.10, 10.11, 10.12  and a different patch script for 10.13+ ?

**Comment by nieder** [comment]
because 10.9-10.12 is a smaller set than 10.13 - 15.0, patched existing launch.info  should be for macOS 10.13-15.0, and a separate one for 10.9 - 10.12.
You will need to either make identical files launch-10.9.info, launch-10.10.info, launch-10.11.info, and launch-10.12.info, or call it launch-1.2.5.info with `Distribution: 10.9, 10.10, 10.11, 10.12`

**Comment by sth0** [comment]
Well, I called it launch-10.9 and gave it a high revision number with `Distribution: 10.9, 10.10, 10.11, 10.12` ?  Since at work they have banned all system < 13.0 I don't have much to test it on.  I thought that was the canonical way to go.  But I can change the file name to launch-1.2.5.info but that is less descriptive.  Should that also have a revision number of 100?

**Comment by sth0** [comment]
You are right, it doesn't validate.  But with the `Distribution: 10.9, 10.10, 10.11, 10.12` in launch-1.2.5.info and with `Distribution: 10.13, 10.14, 10.15, 11.0, 12.0, 13.0, 14.0, 15.0` in launch.info it validates, builds and installs on MacOS 15.1-x86_64 and macOS 10.11.  But it can't seem to find it in the local tree with macOS 10.14.5.
Is there an official list of possible supported distributions should I have 10.14.5, I can't find that in the documentation.

**Comment by nieder** [comment]
Besides the ones you have listed there as the normal numerical progression, there's currently 10.14.5 and 11.3. Plus 14.4 is being added in fink/fink#277.
