### ISSUE TITLE
Updating fink within stable tree only fails with 'unsatisfied dependency in fink: base-files'

### ISSUE THREAD

**Issue by dhomeier** [fink/fink-distributions#129]
Hi,

I wanted to rebuild some packages I had updated in my local tree using the stable tree only, to make sure I have all required dependencies pulled over before committing them to git. I.e.,

I have rsync'ed the set of packages required for the update from the `local` to the `stable` tree.

I then started the update as `fink -t stable -m update pylint-py36`.
This asks for updating the expected dependencies just added from `local`, but strangely also a bunch of packages that are already up-to-date in (and only in) `stable`.
I let it nonetheless proceed, but among the next steps fink wants to reinstall both `base-files` and `fink` itself, failing as follows:
```
/sw/bin/dpkg-lockwait -i /sw/fink/dists/stable/main/binary-darwin-x86_64/base/base-files_1.9.17-1_darwin-x86_64.deb
(Reading database ... 613747 files and directories currently installed.)
Preparing to replace base-files 1.9.17-1 (using .../base-files_1.9.17-1_darwin-x86_64.deb) ...
Unpacking replacement base-files ...
Setting up base-files (1.9.17-1) ...

Reading buildlock packages...
	All buildlocks accounted for.
/sw/bin/dpkg-lockwait -i /sw/fink/dists/stable/main/binary-darwin-x86_64/base/expat1-shlibs_2.2.5-1_darwin-x86_64.deb
(Reading database ... 613747 files and directories currently installed.)
Preparing to replace expat1-shlibs 2.2.5-1 (using .../expat1-shlibs_2.2.5-1_darwin-x86_64.deb) ...
Unpacking replacement expat1-shlibs ...
Setting up expat1-shlibs (2.2.5-1) ...

Reading buildlock packages...
	All buildlocks accounted for.
/sw/bin/dpkg-lockwait -i /sw/fink/dists/stable/main/binary-darwin-x86_64/base/base-files_1.9.17-1_darwin-x86_64.deb
(Reading database ... 613747 files and directories currently installed.)
Preparing to replace base-files 1.9.17-1 (using .../base-files_1.9.17-1_darwin-x86_64.deb) ...
Unpacking replacement base-files ...
Setting up base-files (1.9.17-1) ...

Reading buildlock packages...
	All buildlocks accounted for.

While trying to install:
  fink-0.43.0-111

The following inconsistencies found:
  Unsatisfied dependency in fink: base-files

Trying to resolve dependencies...
Could not resolve inconsistent dependencies!

Fink isn't sure how to install the above packages safely. You may be able to fix things by running:

  fink scanpackages
  sudo apt-get update
  sudo apt-get install fink=0.43.0-111

Failed: Fink::SysState: Could not resolve inconsistent dependencies
```
Needless to say, `apt-get install` just informs me that `fink-0.43.0-111` is already the newest version...

Am I somehow missing a tree here, or is this way of using fink just not meant to work?

**Comment by dmacks** [comment]
```-t stable``` means quite literally that: do not look at any tree except the stable package-set (not the virtual packages supplied by apple, such as system-perl or x11, and not the installed packages according to dpkg's database). Because you have chosen to ignore the dpkg data, fink does not recognize *any* package as being in an "installed" state because that bit is a dpkg-level detail.

**Comment by dhomeier** [comment]
Thanks, actually for just testing for missing dependencies simply attempting the update with
```
fink --trees=stable,virtual -m update [my-package]
```
works; the only thing that needs to be double-checked is if newer versions of any packages existing in `local` are required.
