### ISSUE TITLE
db53/db60 fail with unknown 'atomic_flag' errors on 10.13/Xcode9.3

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#132]
This patch: https://gist.githubusercontent.com/LnL7/5153b251fd525fe15de69b67e63a6075/raw/7778e9364679093a32dec2908656738e16b6bdcb/clang.patch
from here: https://www.databaseusers.com/article/6047407/Bug%3A+Build+failure+on+Linux+with+clang+libc%2B%2B+(atomic+issues)

fixes the build for me.

Sorry I don't have a build log, but am having troubles transferring output from my VM. The error looks like that listed in that dbusers.com link above.

**Comment by nieder** [comment]
See issue fink/fink#163

**Comment by danielj7** [comment]
Now fixed. Thanks!
