### ISSUE TITLE
Missing biplist-py34 variant/confusing versioning

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#136]
While looking at mismatches among our -pyXX package sets, found we have:
```
   	biplist-py27	1.0.3-1	
   	biplist-py34	1:0.8-2
   	biplist-py36	1.0.3-1
```
So the "middle" python-version has an older %v value but is epoch'ed to be newer and we have no -py35 at all. The packages are unmaintained. The 1:0.8 .info has never had -py2X or any -py3X higher than 34. The .info that now has 1.0.3 originally had version 0.9 and only -py27, but several updates by @nieder (bcd25875da324d82ca11d8b558ece1bd6925193c and 044720f89a76d18685ab8ee6edc443d31b38948d) brought up to 1.0.3 and added -py36.

Is 1.0.3 the current upstream? If so, it should become Epoch:1. Is it viable on python34, so we can scrap the -py34 special-case .info? And can a -py35 variant be added for completeness?

**Comment by nieder** [comment]
1.0.3 does seem to be the latest upstream. I have no idea why py34 was epoched. That dates back to the 10.7 tree with Howarth commit `bd59a42c`. I locally added Epoch: 1 to biplist-py.info and added py35 and they all built after I added `nose-py` to TestDepends.

**Comment by dmacks** [comment]
@nieder, could you please commit whatever you think is correct here to get py27/34/36 up to the correct versions, whatever missing deps, and adding py35 if you think it's worthwhile?
