### ISSUE TITLE
uritemplate/uritemplate.py confusion

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#138]
We currently have:
```
   	uritemplate-py27	0.6-1	RFC6570 up to level 4
   	uritemplate-py34	0.6-1	RFC6570 up to level 4
   	uritemplate-py35	0.6-1	RFC6570 up to level 4
   	uritemplate.py-py27	3.0.2-1	Simple python lib to deal with URI Templates
   	uritemplate.py-py34	3.0.2-1	Simple python lib to deal with URI Templates
   	uritemplate.py-py35	3.0.2-1	Simple python lib to deal with URI Templates
   	uritemplate.py-py36	3.0.2-1	Simple python lib to deal with URI Templates
```
Their Desc* say they have a python namespace collision (which they do) and their packages Conflicts/Replaces each other, but both have reverse-dependencies:
* uritemplate-pyXX: github3.py-pyXX, google-api-python-client-pyXX
* uritemplate.py-pyXX: oauth2client-pyXX

so there are certain combinations of other packages that cannot be installed concurrently.

The Desc of uritemplate.py-pyXX says "both packages are now merged upstream so this package can serve as both", so does that mean one can simply switch the Depends from uritemplate-pyXX to uritemplate.py-pyXX, or are there other compatibility changes needed? Should uritemplate-pyXX become a fink-obsolete-packages wrapper bundle rather than a real library?

**Comment by danielj7** [comment]
uritemplate 3.0.0 and uritemplate.py 3.0.2 are the same. Looks like uritemplate is the preferred and uritemplate.py won't be updated anymore though neither have been updated in a few years.

So the answer is that uritemplate.py-pyXX should go away and uritemplate-pyXX should be updated to 3.0.0.

**Comment by danielj7** [comment]
I created a new uritemplate-tng-py package that replaces both of the old ones. It should be the one used going forward.
