### ISSUE TITLE
.info/.patch files with +x permission

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#14]
We have 136 files in the current distribution that have the executable bit set:

`find /sw/fink/dists/stable/main/finkinfo -perm /111 -type f`

which seems unusual for files that are not programs. It's made for some interesting (albeit confusing) shell autocompletions, and can raise a flag for paranoid sysadmins. In CVS, once a file is committed, its permissions are unchangeable. Does git let us change it?

**Comment by nieder** [comment]
Yes, you can change the permission bits in git. I had a branch ready to commit but it got sidetracked. The bulk of the packages belong to None and some are BABA's. A couple are from @fingolfin . BABA said it's OK to commit stuff that's his. Just need @fingolfin's OK to commit his.

**Comment by dmacks** [comment]
Among the affected packages are r-base33.{info,patch} and a ton of rmods, so will hold off on this until #16 and #18 are merged to avoid diverging forks for such a minor issue.

**Comment by fingolfin** [comment]
Those file permissions often got broken in CVS. Of course it's OK to fix them, no need for permission (this does not count as modifying .info files anyway. Also, despite the nasty comments in "my" .info files, I am not that upset about changes, as long as they are explained well -- ideally in a comment in the file, or in a thorough commit message, or possibly in a direct mail to me (though recording the motivation for a change in a permanent place, like a commit message, is IMHO *much* better)

**Comment by dmacks** [comment]
Done. If this becomes a long-term recurring problem, validator could be taught to check for +x
