### ISSUE TITLE
PyQt needs newer versioned dep on sip and other failures

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#147]
PyQt4-4.12.1 needs >= 4.19.1
PyQt55.10.1 needs >= 4.19.4

PyQt4 sip failure: http://bindist.finkproject.org/10.13/logs/pyqt4-mac-py27_4.12.1-1_a8a973712b7a08908d8d3ee5d04efbb2.log
PyQt5 sip failures: http://bindist.finkproject.org/10.13/logs/pyqt5-mac-py27_5.10.1-1_d6b4b1609ae23f487e855a9f8abf7d0b.log

There might be another sip issue with mismatched sip headers and binaries: http://bindist.finkproject.org/10.13/logs/pyqt5-mac-py35_5.10.1-1_d6b4b1609ae23f487e855a9f8abf7d0b.log

And a general build failure (can't find the header?): http://bindist.finkproject.org/10.13/logs/pyqt4-mac-py36_4.12.1-1_a8a973712b7a08908d8d3ee5d04efbb2.log

**Comment by danielj7** [comment]
Yeah, sorry, forgot to update the sip deps. The pyqt4 failure was caused by a version mismatch between sip-py36 and sip-py36-bin. And I also forgot to add C/R to sip-py36-bin. :/
