### ISSUE TITLE
R version support

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#17]
Spawning a new topic from #12, wherein:

@dmacks:
>We currently use a Distribution tag to limit r-base32 to 10.{9-12}, but we don't limit any other r-base*. Should we similarly restrict r-base31? Do we even need to keep dragging r-base33 along, or is r-base34 sufficient to keep going forward?

@nieder:
>Personally, I don't know if there's any reason to keep r33 since I think most rmods that use r33 are available as r34. There are some in r31 that are not available in later releases (but I would imagine that's most likely because they're abandoned).

Here, let's figure out what rmods need to be brought forward vs be marked "do not bring forward" (so we don't have to have this conversation again in the future), and then whether to drop r31 and/or r33 on 10.13....

**Comment by dmacks** [comment]
Here are the differences among *-r3{1,2,3,4} on my 10.12 machine:

package | -r31 | -r32 | -r33 | -r34
-|-|-|-|-
bioconductor-biocparallel-rXX | no | no | no |
bioconductor-preprocessorcore-rXX ||| no | no
cran-blob-rXX | no |||
cran-cellranger-rXX | no |||
cran-chemospec-rXX ||| no | no
cran-gcexplorer-rXX | no | no | no |
cran-its-rXX | no | no | no |
cran-js-rXX ||| no | no
cran-latticist-rXX | no | no | no |
cran-mfda-rXX | no | no | no |
cran-modelmetrics-rXX | no |||
cran-multicore-rXX | no | no | no |
cran-mvpart-rXX | no | no | no |
cran-nmrs-rXX | no | no | no |
cran-pkfit-rXX | no | no | no |
cran-pkmodelfinder-rXX | no | no | no |
cran-pktools-rXX | no | no | no |
cran-plotly-rXX | no |||
cran-psm-rXX | no | no | no |
cran-purrr-rXX | no |||
cran-rcmdrplugin.doby-rXX | no | no | no |
cran-rcmdrplugin.ezr-rXX | no | no | no |
cran-rgdal-rXX | no | no | no |
cran-rglwidget-rXX | no |||
cran-robustrankaggreg-rXX | no | no ||
cran-sets-rXX | no |||
cran-spgrass6-rXX | no | no | no |
cran-tidyr-rXX | no |||
cran-tidyselect-rXX | no |||
cran-weightedkmeans-rXX | no | no | no |
metaboanalyst-tomcat6-rXX | no | no | no |
metaboanalyst-tomcat7-rXX | no | no | no |
metaboanalyst-tomcat8-rXX | no | no | no |
metaboanalyst3-tomcat7-rXX | no | no | no |
metaboanalyst3-tomcat8-rXX | no | no | no |

**Comment by dmacks** [comment]
So the only three -r31/-r32 that do not have an -r33 are:

- bioconductor-preprocessorcore-rXX - supplanted by bioconductor-preprocesscore-rXX
- cran-chemospec-rXX
- cran-js-rXX

I don't see anything obvious about those latter two that would block adding new variants but I'd love a second opinion since I don't use R that much.

**Comment by dmacks** [comment]
All modules are now available in -r34 flavor unless there is a documented reason not to carry certain ones forward.

The only two remaining users of R3.3 (other than *-r33) are rstudio (unmaintained) and rpy2-pyXX (Baba's). I can test-build them but I don't use either one to know whether they would work.

**Comment by dhomeier** [comment]
I've played around with rpy2-py updates on High Sierra and just filed them as PR #32. So far everything seems to work fine with `-r34`, but I am using R approximately once a year when TAing a statistics course...

**Comment by nieder** [comment]
closing this as ancient. There are a few mods that need to be dist restricted since r33-r35 stops at 10.14.5. Working on that.
