### ISSUE TITLE
libpulse uses orc if found 

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#194]
Copied from old tracker https://sourceforge.net/p/fink/bugs/1661/
On libpulse-11.1:
````
checking for LIBSOXR... yes
checking for ORC... yes
checking for usable orcc... 
checking for SYSTEMD... no
...
make[2]: Entering directory '/sw/src/fink.build/libpulse0-11.1-1/pulseaudio-11.1/src'
  ORCC   pulsecore/svolume-orc-gen.c
/bin/sh: --implementation: command not found
make[2]: *** [Makefile:11314: pulsecore/svolume-orc-gen.c] Error 127
````
http://bindist.finkproject.org/10.13/logs/pulseaudio-utils_11.1-1_657557fd53de16709e01bcc71c1d0154.log

libpulse uses orc if liborc-0.4-dev is present (headers found by f-p-p as well as linkage). If found, libpulse also needs the package `orc` to provide `%p/bin/orcc` at buildtime.
````
checking for ORC... yes
checking for usable orcc... /sw/bin/orcc
````

**Comment by danielj7** [comment]
Fixed in https://github.com/fink/fink-distributions/commit/07174745af301affff0c81c3549be9e9b29b5124
