### ISSUE TITLE
Remove xmkmf and its reverse-dependencies from the 10.13 distribution

### ISSUE THREAD

**Issue by akhansen** [fink/fink-distributions#2]
Currently `xmkmf` can't be built on 10.13, so it needs to go away.  Packages that need it either need to be updated not to use it, or themselves to go away.

**Comment by dmacks** [comment]
Done. Per that commit-message "Grep on XMKMFHS to find Dependees of xmkmf affected by this restriction."

**Comment by nieder** [comment]
I'm trying to track down the reason for xmkmf not being present on 10.13+. If I recall correctly, the immediate trigger was that llvm-gcc42 wasn't possible on 10.13 and xmkmf does not work with clang's /usr/bin/cpp, and so it currently depends on llvm-gcc42.
But I tried replacing the llvm-cpp-4.2 usage in xmkmf with cpp-fsf-6, and cernlib2006, rasmol, dclock, and geant4.9 built fine with this change. So why can't xmkmf use cpp from one of the gccX packages?
@jwhowarth ?

**Comment by nieder** [comment]
Another option might be to use tradcpp, which is supposedly good for imake/xmkmf things
https://www.freshports.org/devel/tradcpp/
http://ftp.netbsd.org/pub/NetBSD/misc/dholland/
````
tradcpp is a traditional (K&R-style) preprocessor.

It has the particular property that it doesn't (for the most part)
trash whitespace, so it can be used on makefiles.
````
