### ISSUE TITLE
hgsubversion has hardcoded /sw

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#208]
https://github.com/fink/fink-distributions/blob/6aad05b54d84c8ec5ad4d6d23118785e89a8c08d/10.9-libcxx/stable/main/finkinfo/libs/pythonmods/hgsubversion-py.info#L39-L42

**Comment by danielj7** [comment]
Wow. That's...dumb. I'm in the midst of updating svn/subvertpy/hgsubversion anyway so I'll fix it. The current hgsubversion doesn't work with the current mercurial anyway.

**Comment by danielj7** [comment]
This is fixed now.
