### ISSUE TITLE
Update dateutil-py to new version

### ISSUE THREAD

**Issue by danielj7** [fink/fink-distributions#228]
I had added a python-dateutil-py package because I needed it for a dep without realizing that dateutil-py was the same package. I've removed mine but the current dateutil is too old for my needs. Can you update to the newest upstream? Note that tests won't work due to a circular dep: it needs freezegun to run tests but freezegun requires dateutil.

**Comment by dmacks** [comment]
Would python-dateutil-pyXX be a saner package-name, given upstream's use of it? Either way, sounds like one should Replaces: the other and have some fink-obsolete-packages magic.

**Comment by danielj7** [comment]
python-dateutil is the upstream name but since we already have it as just dateutil it might be more disruptive to change it. Of course, that's why I didn't find it at first. It's up to you. Here's my version: https://github.com/fink/fink-distributions/commit/9a7d7805ac27b1c19f0f81376293157116f42333

My python-dateutil-py was only present for a little while before I removed it and nothing depended on it yet so I didn't worry about Replaces or any such.

**Comment by dmacks** [comment]
Kept as dateutil-pyXX with no C/R/OBSOLETE games.
