### ISSUE TITLE
missing (Build)Depends in pythonmods

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#23]
@schwehr 

* pkgconfig-py is missing a BuildDepends on nose-py
* h5py-py is missing a six-py BuildDepends

**Comment by schwehr** [comment]
Are there instructions around for migrating from cvs to git for fink?

**Comment by nieder** [comment]
Not currently. But at a minimum:

* fork https://github.com/fink/fink-distributions to your github account.
* make a local clone of your fork.
* make a branch in your fork, do your changes and commit to origin/<BRANCH>, then submit a PR inside github to merge the change(s) in BRANCH to upstream/master.

**Comment by nieder** [comment]
An update from @dhomeier on our old tracker has h5py at latest upstream + the missing BDep.
https://sourceforge.net/p/fink/package-submissions/4942/

**Comment by nieder** [comment]
And there's an update to pkgconfig-py here: https://sourceforge.net/p/fink/package-submissions/4941/ but it's missing the nose-py BuildDepends.
