### ISSUE TITLE
pysocks-pyXX and socksipy-pyXX supply same files

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#237]
```site-packages/socks.py``` is present in both, which makes them collide during installation. Looks like one package is fork of other, or both are forks of some thing even older? See debian's thread diagnosing the history and way they planned to move forward (picking which is actually the correct current upstream and separately picking which name to use):

https://groups.google.com/forum/#!topic/linux.debian.maint.python/mXmRjEHK8Dc

pysocks-pyXX is @danielj7; socksipy-pyXX is @schwehr

**Comment by danielj7** [comment]
pysocks is the currently maintained fork of socksipy which is very old. There is only one package that uses socksipy, gsutil-py. It already patches out the socksipy dependency in setup.py so in theory simply changing the package dep to pysocks-py should work. I tried to run its tests but they appear to require google credentials and net access to run. I don't know how to use it so I don't know if it works. Also there's a missing dep on retrydecorator-py.

**Comment by dmacks** [comment]
Bit of a deadlock upgrading (if have existing gsutil with its Depends on the older package), but that will fade into the memory hole after one-time manual intervention. Thanks!
