### ISSUE TITLE
meep-mpi FTBFS on 10.10+ (mis-set compiler)

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#243]
Building meep-mpi on 10.13 (and back to 10.10 according to bindist logs) fails:
```
  CXX      meep.o
clang: warning: argument unused during compilation: '-malign-double' [-Wunused-command-line-argument]
In file included from meep.cpp:1:
In file included from ./meep-ctl.hpp:10:
In file included from ./ctl-io.h:7:
/sw/include/ctl.h:270:8: error: reference to 'function' is ambiguous
extern function ctl_get_function(char *identifier);
       ^
```
That is consistent with our libctl package notes:

>DescUsage: <<
>The C++ binding for libctl's Guile commands is incompatible
>with clang/libc++, because of the "function" type it introduces.
>Programs using libctl therefore should be compiled with Fink's
>gccXX compilers. On OSX 10.9, Fink's default g++/libc++ will 
>crash with "error: reference to 'function' is ambiguous".
><<

The non-mpi variant of meep builds fine, thanks to ```CXX=g++-fsf-5```. But the mpi variant uses the mpic++ compiler wrapper, which ignores CXX and instead uses clang++ as its own preferred compiler. The openmpi docs list what variables can be used to override its own defaults. Adding:
```
export OMPI_CXX=g++-fsf-5
```
into CompileScript prior to ```./configure``` gets the package buildable on my 10.13. Assigning to Martin, as maintainer of both meep and libctl.

**Comment by nieder** [comment]
@dmacks with #546 merged, is this still an issue?

**Comment by costabel** [comment]
On 20/04/20 12:14, nieder wrote:
> @dmacks <https://github.com/dmacks> with #546
> <https://github.com/fink/fink-distributions/pull/546> merged, is this
> still an issue?

Seems to build here:
costabel% meep --version
Using MPI version 3.0, 1 processes
Meep 1.12.0, Copyright (C) 2005-2019 Massachusetts Insitute of Technology.
Using libctl 4.4.0 and Guile 2.2.7.

-- 
Martin
