### ISSUE TITLE
gdal2-shlibs-2.3.1-1 is linked against libcryptopp5-shlibs but is not in Depends

### ISSUE THREAD

**Issue by remkos** [fink/fink-distributions#268]
In the latest version of the gdal2 package (gdal2-shlibs-2.3.1-1), %p/lib/libgdal.20.dylib is linked against %p/lib/libcryptopp.5.dylib even though libcrytopp5-shlibs is not in the list of Required packages. Neither does libcrytopp5 appear in the BuildDepends.

In the configure step it is also not mentioned in the --with options. That means that the automatic detection of packages picked it about and it will need to be either:
- explicitly be excluded with a --without- option
- explicitly be included with a --with- option and added to the BuildDepends and Depends

**Comment by dmacks** [comment]
I pushed a fix (since I think I was the one working most recently on this package anyway, and also saw another error)
