### ISSUE TITLE
cryptic TestScript in numpy causes abrupt exit

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#306]
Our numpy has this command for running tests:
````
LANG=en_US.UTF-8 SHELL=/bin/sh PYTHONPATH=%i/lib/python%type_raw[python]/site-packages %p/bin/python%type_raw[python] -B -c "import numpy, sys; e=numpy.test(); sys.exit(len(e.failures)//4 + len(e.errors)*1)"
````
This runs fine for me on 10.11 for various pyXX flavors. But as I try to update to latest %v=1.15.3, the tests exit uncleanly even though they all pass:
````
NumPy version 1.15.3
NumPy relaxed strides checking option: True
.................x.............................................................................................................................................. [  3%]
.........................................................................................................................x.x.................................... [  6%]
...............................................................................................................................................................s [  9%]
[....]
..............................................................................................................................................................ss [ 98%]
s....................................s......................                                                                                                     [100%]
4974 passed, 37 skipped, 87 deselected, 9 xfailed in 53.03 seconds
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'bool' object has no attribute 'failures'
### execution of /tmp/fink.Mp3VD failed, exit code 1
````

For our current numpy-1.14.5, py27-py36 pass 100%. Py37 has 3 known failures for 1.14.5. sys.exit() was added by @dhomeier to deal with them (numpy/numpy#11460). The previous error catcher was `sys.exit(1-e.wasSuccessful())` added by @jwhowarth but that also errors out with `AttributeError: 'bool' object has no attribute 'wasSuccessful'`.

Can we get rid of the sys.exit() call (or modify it to exit cleanly with the current good test results)?

**Comment by dmacks** [comment]
I pushed numpy 1.22.1 for py38+ (its spec as minimum python version), keeping 1.14.5 for py<38. At some point prior to 1.22.1, numpy.test switched from using nose to using pytest. So nose functions such as wasSuccessful are not valid, and tons of things built on top of that approach to testing would likely need to be rewritten. I'm going to close this, as 1.22.1 pass tests for me for all its pyXX, and python up through py37 are so old now that I don't think we need to try to figure out how much we can update its numpy. If anyone actually wants them, feel free to re-open or file a new ticket and I'll see if I can move it up a little. Or someone else is welcome to hack on it, possibly starting from the new version's .info for a basis.
