### ISSUE TITLE
pytables fails to build as py37

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#317]
pytables-3.2.2-2 fails to build on 10.11 when I add a py37 variant:
````
#!/bin/sh -ev
 /sw/bin/python3.7 setup.py build_ext --cflags='-I/sw/include' --lflags='-L/sw/lib' --hdf5=/sw/ --lzo=/sw/ --bzip2=/sw/ 
* Using Python 3.7.1 (default, Oct 24 2018, 07:18:25) 
* USE_PKGCONFIG: True
* Found HDF5 headers at ``/sw/include``, library at ``/sw/lib``.
Traceback (most recent call last):
  File "setup.py", line 583, in <module>
    hdf5_version = get_hdf5_version(hdf5_header)
  File "setup.py", line 360, in get_hdf5_version
    major_version = int(re.split("\s*", line)[2])
ValueError: invalid literal for int() with base 10: 'd'
````
py27-py36 work.

**Comment by danielj7** [comment]
This is fixed in version 3.4.4. See https://github.com/PyTables/PyTables/pull/687

**Comment by dhomeier** [comment]
Confirmed, 3.4.4 builds with py37 on 10.12. However the doc builds, which I got to work before, are failing with Sphinx 1.8.1 due to a new module dependency.

**Comment by nieder** [comment]
Possible to backport the patch to our current 3.2.2 to get that building on py37 and then work with fixing the doc build failure?

**Comment by danielj7** [comment]
Simply changing every \s* to \s+ in setup.py should do it, but numexpr-py is also missing py37 so that needs updating too.

**Comment by danielj7** [comment]
Needs numexpr-py37 and therefore depends on https://github.com/fink/fink-distributions/pull/275.

**Comment by nieder** [comment]
This will be taken care of by #372
