### ISSUE TITLE
R mods upstream updates

### ISSUE THREAD

**Issue by dhomeier** [fink/fink-distributions#367]
Thanks for the massive update to `r35` and lots of the modules! Unfortunately a number of the latter have already been upgraded again upstream and thus the sources are no longer available in the original download dir. These are the packages with upped versions found on today's `fink update` attempt (not necessarily complete, since I don't have all modules installed):
```
 M cran-evaluate-r.info
 M cran-forcats-r.info
 M cran-haven-r.info
 M cran-hmisc-r.info
 M cran-knitr-r.info
 M cran-lme4-r.info
 M cran-maptools-r.info
 M cran-mgcv-r.info
 M cran-r6-r.info
 M cran-readxl-r.info
 M cran-stringi-r.info
 M cran-stringr-r.info
 M cran-xfun-r.info
 M cran-yaml-r.info
 M cran-zip-r.info
```
I could just put the new version numbers and MD5s into a PR, but this might turn into catching up with a moving target as long as our mirrors are all offline. A slightly more durable solution could be adding the archive paths as a `CustomMirror`:
```
Source: mirror:custom:zip_%v.tar.gz
Source-MD5: e5309b143d2e786bd612c9f96aca97f6
 SourceDirectory: zip
CustomMirror: <<
       Primary: https://cran.r-project.org/src/contrib
       Secondary: https://cran.r-project.org/src/contrib/00Archive/zip
<<
```
but if I'm not mistaken this will result in always looking up the r-project server first, which seems fairly heavily loaded as well...

**Comment by nieder** [comment]
I thought I had tried to do this once long before, but it didn't work, but I think that's because I wasn't putting the package name at the end of the Secondary mirror URL, but I just checked now and 5 different rmods all follow the same pattern, so it should work.

**Comment by dhomeier** [comment]
Yes, I tried with 3 or 4 packages with the old and new versions as well. Fink seems to randomly pick either the `Primary` or `Secondary` mirror first, so people will still have to pass over one failed download now and then.

**Comment by nieder** [comment]
Closing this since #369 started the fixes. We can start fixing the rest of the R mods. If you do more R mod updates, can you make the branch in fink/fink-dists so that @babayoshihiko and myself and anyone else interested can keep track of which rmods have been updated by everyone and we don't duplicate work?
