### ISSUE TITLE
cyrus-sasl2.3 original source not available

### ISSUE THREAD

**Issue by akhansen** [fink/fink-distributions#376]
Hi, @danielj7 .  With the finkmirrors.net domain  down we've been shaking out lots of non-downloadable packages.  

cyrus-sasl2's source URL doesn't seem to work anymore (and upstream hasn't bothered to update their website accordingly).  However, there's a full 2.1.27 release from November last year available on GitHub:  

https://github.com/cyrusimap/cyrus-sasl/releases/download/cyrus-sasl-2.1.27/cyrus-sasl-2.1.27.tar.gz

**Comment by danielj7** [comment]
Fixed by https://github.com/fink/fink-distributions/pull/400
