### ISSUE TITLE
flag-sort fails if there's a space between -I and path

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#394]
This command fails:
````
$ flag-sort -v -r gcc -ffor-scope -I/sw/Library/Frameworks/R.framework/Versions/3.3/Resources/include -DNDEBUG -I . -DINTEGERTIME -DPARSER_LP -DBUILDING_FOR_R -DYY_NEVER_INTERACTIVE -DUSRDLL -DCLOCKTIME -DRoleIsExternalInvEngine -DINVERSE_ACTIVE=INVERSE_LUSOL -DINLINE=static -DParanoia -I/sw/include    -fPIC  -g -O3  -c colamd.c -o colamd.o
/sw/bin/flag-sort: gcc -ffor-scope -DNDEBUG . -DINTEGERTIME -DPARSER_LP -DBUILDING_FOR_R -DYY_NEVER_INTERACTIVE -DUSRDLL -DCLOCKTIME -DRoleIsExternalInvEngine -DINVERSE_ACTIVE=INVERSE_LUSOL -DINLINE=static -DParanoia -fPIC -g -O3 -c colamd.c -o colamd.o -I -I/sw/Library/Frameworks/R.framework/Versions/3.3/Resources/include -I/sw/include
colamd.c:757:10: fatal error: 'R.h' file not found
````
`R.h` is present in `/sw/Library/Frameworks/R.framework/Versions/3.3/Resources/include`. The problem is that the flag `-I .` (notice space) gets translated to just `-I` by flag sort, which then swallows up the `-I/sw/Library/...`. If I manually remove the space and re-run the command, then the command is successful.

**Comment by dmacks** [comment]
Whitespace between -I (or -L) and its path is not guaranteed to be accepted by compilers anyway (syntax spec is no-space). Sounds like a bug in...whatever package you are trying to compile.

**Comment by dmacks** [comment]
GIGO
