### ISSUE TITLE
nginx and nginx-cur build failures

### ISSUE THREAD

**Issue by akhansen** [fink/fink-distributions#395]
The builds fail in the configuration phase as follows:

...
\+ ./configure --prefix=/sw --conf-path=/sw/etc/nginx/nginx.conf --error-log-path=/sw/var/log/nginx/error.log --http-client-body-temp-path=/sw/var/lib/nginx/body --http-fastcgi-temp-path=/sw/var/lib/nginx/fastcgi --http-log-path=/sw/var/log/nginx/access.log --http-proxy-temp-path=/sw/var/lib/nginx/proxy --http-scgi-temp-path=/sw/var/lib/nginx/scgi --http-uwsgi-temp-path=/sw/var/lib/nginx/uwsgi --lock-path=/sw/var/lock/nginx/nginx.lock --modules-path=/sw/var/lib/nginx/modules --pid-path=/sw/var/run/nginx.pid --with-pcre-jit --with-debug --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module --with-ipv6 --with-mail --with-mail_ssl_module --with-perl=/usr/bin/perl --with-stream --with-stream_ssl_module --with-threads --user=www --group=www '--with-ld-opt=-Wl,-read_only_stubs -Wl,-bind_at_load -fPIE -Wl,-pie -L/sw/lib' '--with-cc-opt=-g -O2 -fstack-protector -Wformat -Werror=format-security -fPIE -D_FORTIFY_SOURCE=2 -I/sw/include' --with-perl_modules_path=/sw/lib/perl5/5.18.2
...
checking for libxslt ... not found
checking for libxslt in /usr/local/ ... not found
checking for libxslt in /usr/pkg/ ... not found
checking for libxslt in /opt/local/ ... not found

./configure: error: the HTTP XSLT module requires the libxml2/libxslt
libraries. You can either do not enable the module or install the libraries.

The actual detection command from %p/src/fink.build/nginx-1.12.2-1/nginx-1.12.2/objs/autoconf.err is:

checking for libxslt

objs/autotest.c:4:10: fatal error: 'libxml/parser.h' file not found
#include <libxml/parser.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <libxml/parser.h>
                      #include <libxml/tree.h>
                      #include <libxslt/xslt.h>
                      #include <libxslt/xsltInternals.h>
                      #include <libxslt/transform.h>
                      #include <libxslt/xsltutils.h>

int main(void) {
    xmlParserCtxtPtr    ctxt = NULL;
                      xsltStylesheetPtr   sheet = NULL;
                      xmlDocPtr           doc;
                      doc = xmlParseChunk(ctxt, NULL, 0, 0);
                      xsltApplyStylesheet(sheet, doc, NULL);;
    return 0;
}

----------
cc -g -O2 -fstack-protector -Wformat -Werror=format-security -fPIE -g -O2 -fstack-protector -Wformat -Werror=format-security -fPIE -D_FORTIFY_SOURCE=2 -I/sw/include -I /usr/include/libxml2 -o objs/autotest objs/autotest.c -Wl,-read_only_stubs -Wl,-bind_at_load -fPIE -Wl,-pie -L/sw/lib -lxml2 -lxslt

Fink's libxml/parser.h is installed in a path that this command isn't including:

Fionna:Downloads hansen$ dpkg -S libxml/parser.h
libxml2: /sw/include/libxml2/libxml/parser.h

**Comment by nieder** [comment]
It must be OS or Xcode specific. On 10.13/Xcode9:
````
checking for zlib library ... found
checking for libxslt ... found
checking for libexslt ... found
checking for GD library ... found
````
and the build succeeds.

I think it's the no /usr/include thing again with Xcode10. `auto/lib/libxslt/conf` has checks for /usr/include/libxml2, /usr/local/include/libxml2, /usr/pkg/include/libxml2, & /opt/local/include/libxml2.

So we've been (un)lucky that the libxml2/xslt checks look for system-xml/xslt but actually use Fink libraries.

**Comment by dmacks** [comment]
libxml2 and libxslt are documented to use pkgconfig (and maybe alternately a -config script) to publish flags. This is a good upstream bug to report also.

**Comment by akhansen** [comment]
> It must be OS or Xcode specific. On 10.13/Xcode9:
> 
> ```
> checking for zlib library ... found
> checking for libxslt ... found
> checking for libexslt ... found
> checking for GD library ... found
> ```
> and the build succeeds.
> 
> I think it's the no /usr/include thing again with Xcode10. `auto/lib/libxslt/conf` has checks for /usr/include/libxml2, /usr/local/include/libxml2, /usr/pkg/include/libxml2, & /opt/local/include/libxml2.
> 
> So we've been (un)lucky that the libxml2/xslt checks look for system-xml/xslt but actually use Fink libraries.

Yeah, this is Xcode 10.2 on macOS 10.14.

**Comment by nieder** [comment]
> libxml2 and libxslt are documented to use pkgconfig (and maybe alternately a -config script) to publish flags. This is a good upstream bug to report also.

Our nginx packages are pretty old but I just tested 1.14.2 (latest in 'stable' branch) and it has same issue.
https://trac.nginx.org/nginx/ticket/1765
