### ISSUE TITLE
Apply new CVE patches to libjasper1

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#420]
We currently patch libjasper with 8 Debian patches for CVE fixes. The debian patches are 4+ years old and the old tarball is no longer available in Debian's mirrors. I just updated to find the new Debian tarball, but kept only the original 8 applied patches. The current Debian tarball has an additional 21 CVE patches available. We should apply those patches as well.

**Comment by dmacks** [comment]
One of the CVS fixes changes the types of a few function parameters and public struct fields from int to size_t, which is a different size datatype. Is that an ABI break we should care about?

**Comment by nieder** [comment]
Not sure. Old source %v, CVE fix, Debian didn't seem to mind about the break, but upstream hasn't incorporated the change. C.f mdadams/jasper#208

**Comment by dmacks** [comment]
I think everyone gave up on upstream doing anything, which is why Debian is now using a local source (https://packages.debian.org/source/jessie/jasper). We could just do that (dmacks/fink-distributions@331d1430bf4ae2a68979391aca35da0d90655c1b), wipe our hands on Debian's pants, and call it a day?

**Comment by nieder** [comment]
Is the debian primary source tarball `jasper_1.900.1-debian1.orig.tar.gz` any different than upstream's original `jasper-1.900.1.zip`? I'm OK with this.

**Comment by dmacks** [comment]
Those source seem the same. I picked Debian's for consistency since we're now tracking Debian itself as a maintained fork-like-thing.
