### ISSUE TITLE
librasqal3-dev not found on 10.14.5

### ISSUE THREAD

**Issue by jaokiro** [fink/fink-distributions#438]
Thanks. It works now:)

_Originally posted by @jaokiro in https://github.com/fink/fink/pull/190#issuecomment-516807242_

I now want to install kile on the Mac 10.14.5 using fink. I have tried
fink install kile-kde4-mac, with no success. Is there another way to do the installation.
 Here is the error message:
Jareds-MacBook-Pro:~ jaredokiro$ fink install kile-kde4-mac
Information about 10646 packages read in 0 seconds.
Can't resolve dependency "librasqal3-dev (>= 0.9.28-1)" for package "soprano-mac-2.9.4-2" (no matching
packages/versions found)
Exiting with failure.

**Comment by jaokiro** [comment]
This is the output:
Jareds-MacBook-Pro:~ jaredokiro$ fink --version; grep Distribution /sw/etc/fink.conf
Package manager version: 0.44.99.git
Distribution version: selfupdate-svn Wed Jul 31 19:18:06 2019, 10.14.5, x86_64
Trees: local/main stable/main

Copyright (c) 2001 Christoph Pfisterer
Copyright (c) 2001-2016 The Fink Package Manager Team
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
Distribution: 10.14.5

**Comment by nieder** [comment]
`fink selfupdate` should bring you Fink-0.45.0 and an up to date tree that has librasqal3 for 10.14.5.

**Comment by nieder** [comment]
Should be fixed and no response.
