### ISSUE TITLE
Caution when building pinentry from source

### ISSUE THREAD

**Issue by x-ii-ii-x** [fink/fink-distributions#460]
Good Day @bcully and the Fink team,

It's me again. I switched back to Fink gpg - pinentry. Everything is working fine for now but I found this warning interesting while building the pinentry from source (the ncurses one):

```
configure: WARNING: unrecognized options: --disable-pinentry-gtk, --disable-pinentry-qt
configure:

	Pinentry v0.9.1 has been configured as follows:

	Revision:  0b2d5e4  (2861)
	Platform:  x86_64-apple-darwin17.7.0

	Curses Pinentry ..: yes
	TTY Pinentry .....: maybe
	GTK+-2 Pinentry ..: no
	Qt4 Pinentry .....: no
	W32 Pinentry .....: no

	Fallback to Curses: yes

	Default Pinentry .: pinentry-curses
```

Looks like the configure options are deprecated, meaning that if other packages were installed, the gtk2 or qt4 version might be built at the same time.
Nothing in hurry, was just thinking it was worth pointing it.

Cheers

**Comment by nieder** [comment]
`--disable-pinentry-gtk` refers to the old GTK+1 interface and `disable-pinentry-qt` refers to the old Qt3 interface which have been completely remove from pinentry. The GTK+2 and Qt4 frontends have different configure flags, so their build status is unaffected.
