### ISSUE TITLE
Claws Mail and GPG modules setup

### ISSUE THREAD

**Issue by x-ii-ii-x** [fink/fink-distributions#468]
Good Day all,

When I tried to launch the PGP modules in Claws Mail I got an error similar to this one:

`/sw/bin/gpg2: program not found`

On my environment gpgme-config --get-gpg returns /sw/bin/gpg2 which does not exist.
I tried to make a symlink and a few other tricks but that doesn't seem to work ><
Is it related to something wrong with environment or something with a package?
I was using the Mac binary previously but I removed it, the whole /usr/local and brew as well before switching back to Fink.

Thank you very much in advance for any hints :-)

**Comment by sth0** [comment]
I don’t think there is such an executable installed by fink.  The current install of gnupg2 is version 2.17 and installs the executable /sw/bin/gpg.  It seems that you have confused gpgme with a bad configuration?

-Scott

**Comment by x-ii-ii-x** [comment]
Hey sth0, 

Thank you very much for the reply. Yes that's the point, there is no executable named 'gpg2'.
If you tried to launch the pgp module from claws mail, pgp-*.so, it complains about a missing gpg2. Looking at the dependencies, I *guess* it might come from the gpgme11 (only set for the build actually as a dev dependency) package which provides gpgme-config (or I mistake?):
- https://github.com/fink/fink-distributions/blob/master/10.9-libcxx/stable/main/finkinfo/crypto/gpgme11.info

```
$ gpgme-config --get-gpg
$ /sw/bin/gpg2
```
Don't know why but in the past I *suppose* there was a gpg2 available?
No hurry but if @dmalloc or @nieder has an idea about that, I would be glad to know :-)
Currently I can use Claws Mail without PGP. My purpose  is to be able to use PGP hehe.

**Comment by TheSin-** [comment]
Most distress add an alias for gpg2, you can use u-a yourself to make one or make a symlink but you are correct gpg2 should be installed with gnupg2, most tools look for gog2 as the binary

**Comment by x-ii-ii-x** [comment]
@TheSin- Thank you for the reply.
Actually there are always workarounds to do with symlinks, simply copying gpg to gpg2 worked.
It still got some issue with the settings but it looks related to my switch to a new mailing service ><
I'm closing the ticket for now. Thank you all for your time and your reply 👍

**Comment by sth0** [comment]
Well, the “fink way” is to actually us a symbolic link to a file in /sw/etc/alternatives and from there link to the specific version you want.  This is probably what should be built into the gpg2 package installer.  Things are in flux with that package since its original name was gnupg2 (IIRC).

Copying may work but lead to issues down the line as you update versions gpg2 and are left using the copied orphan copy with possible security holes.  Just a suggestion, YMMV.

-Scott

**Comment by nieder** [comment]
gnupg2 now installs a symlink gpg2 pointing to gpg

**Comment by x-ii-ii-x** [comment]
@nieder @TheSin- @sth0 Thank you very much to everyone for the help.
My own copy / symlink didn't work as expected. The new gnupg2 created solved the launching / setup error! And actually I had a hard time to figure out that *pinentry-gtk2* looks required when claws mail asked for your passphrase when signing a message ><
I apologize for the inconvenience and I am more than happy that it finally works!
Great job 👍
