### ISSUE TITLE
Upgrade cpplapack to use newer lapackXXX libs

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#483]
cpplapack-2015.05.11-1 has: ``Recommends: atlas | lapack350 | lapack342 | lapack341`` but our current lapackXXX versions are: lapack350, lapack360, lapack361, lapack371, lapack380, many of which have build problems and/or no other users in fink. It would be great to be able to kill off those old versions, or at least not require them for this package here. Can cpplapack use newer lapackXXX?

**Comment by nieder** [comment]
@okayamat This is yours I think.

**Comment by dmacks** [comment]
Looks like it might not be doable because it has template code around symbols that were deprecated and then removed in lapack>=360

**Comment by dmacks** [comment]
Upstream has been dead for years, no other Mac package-manager or major linux distro seems to have it. Should we just kill it (or at lest dist-restrict to <= 10.14.5 so we don't have to keep ancient lapack350 forever?

**Comment by okayamat** [comment]
It is ok for me to remove this package. Thank you for the notice.

**Comment by dmacks** [comment]
Thanks.
