### ISSUE TITLE
request goldendict to new version

### ISSUE THREAD

**Issue by ctrngk** [fink/fink-distributions#517]
The current installable package  goldendict-x11 in fink is  v1.0.1, very old version, while the latest version is v1.5.x. I try to build it from source but failed. Hope maintainers can update it to latest version.

**Comment by nieder** [comment]
Updating to 1.5RC2 will require libeb and opencc, which are not currently in Fink.

**Comment by nieder** [comment]
latest version is now goldendict-mac

**Comment by ctrngk** [comment]
fink install goldendict-mac
> Failed: phase compiling: libopencc2-shlibs-1.0.5-1 failed
Failed: phase compiling: libopenjp2.7-shlibs-2.1.1-1 failed

I solved the first package by installing libopencc2-dev, while the second package libopenjp2.7-shlibs or libopenjp2.7 still remain failed.

**Comment by nieder** [comment]
Can you post the actual error message you got when building libopencc2-shlibs ? The `Failed: ` line just says that the package failed to build, but doesn't provide any details as to how or why. And if it's actually libopencc2-shlibs that failed and/or libopenjp2.7, please open separate tickets to them so that we can easily track them and the eventual fixes. Thanks.

**Comment by ctrngk** [comment]
My bad. I miss an important note as follows.
> ...
There are files installed in /usr/local on your computer that are
known to interfere with building some Fink packages. Try temporarily
renaming or moving /usr/local while Fink is compiling a package. See
http://fink.sourceforge.net/faq/comp-general.php#usr-local-libs for
more information.
...

After renaming /usr/local,  I am able to install everything. Thanks.

I have to mention that it still has exactly the same bugs as native mac version. For example, selecting a few words from article does not always work.  That is why I want a x11 version. There is no such bugs in Linux/windows.

**Comment by nieder** [comment]
I was able to also update the Qt4-x11 variant of goldendict to 1.5.0. Try that. No guarantee that the bug is aqua vs x11 and not mac vs win/linux.
