### ISSUE TITLE
gnuplot* missing gnuplot.el

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#523]
The gnuplot packages at version 4.6.7 supply share/emacs/site-lisp/gnuplot-mode/gnuplot.el and etc/emacs/site-start.d/50gnuplot.el that uses it, both of which as part of the gnuplot tarball. In 5.0.7, the site-start.d hook is still included but gnuplot.el itself is not. 

Upgrading therefore is a regression for users who want gnuplot-mode in emacs. And it also triggers a warning during lots of emacs install/remove operations:

```
Package `gnuplot' is not installed and no info is available.
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
```

gnuplot-mode is now its own upstream dist (at a newer version than with old gnuplot) with the gnuplot-mode/gnuplot.el file but not the site-start.d hook.

https://packages.debian.org/source/sid/gnuplot-mode
https://salsa.debian.org/debian/gnuplot-mode
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944249

 And the site-start.d are support files for loaded by emacsen-common. So how do we package this now? Should new gnuplot* pull the new gnuplot.el via Source2? Should we have a stand-alone gnuplot-mode package (but if so, does gnuplot-mode:Depends:gnuplot* or do gnuplot*:Depends:gnuplot-mode)?

**Comment by nieder** [comment]
Ubuntu/Debian have
```
gnuplot-mode <<
Depends: gnuplot
Enhances: emacs
<<
```
https://packages.ubuntu.com/eoan/elpa-gnuplot-mode
That makes the most sense but requires emacs users to install it separately to get back functionality. Minimal effort for us and users is Source2:

**Comment by dmacks** [comment]
That diagnostic became non-reproducible as I tried to diagnose it, but "M-x gnuplot-mode" successfully autocompleted but failed to load, so the missing files are a true bug. And installing debian's files (via Source2) fixed it.
