### ISSUE TITLE
gnupg2 missing depend on pinentry

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#534]
I believe all variants of pinentry if there is no provides will work, I just installed normal pinentry and it started to work.

**Comment by nieder** [comment]
Does this look like a RuntimeDepends or should it be a straight Depends:?

**Comment by TheSin-** [comment]
yeah Runtime

**Comment by TheSin-** [comment]
Just did some testing and it looks like pinentry is the RuntimeDepend, pinentry-mac can build now but it doesn't satisfy gpg

to test just run

`echo test | gpg --clear-sign`
