### ISSUE TITLE
Problem with installing xmltv

### ISSUE THREAD

**Issue by sehroriginell** [fink/fink-distributions#536]
I am getting the following error message:
Can't resolve dependency "convert-binhex-pm" for package "mime-tools-pm5182-5.509-1" (no matching packages/versions found)

When trying to install convert-binhex-pm I do get the following message:
Failed: no package found for specification 'convert-binhex-pm'!

It seems like convert-binhex is only available up to system version 10.13, I have 10.14.

**Comment by dmacks** [comment]
@nieder what is our current standard for setting systemperl variant on 10.14? Are we assuming it's always 5.18.4 now?

**Comment by TheSin-** [comment]
it's 5.18.4 on 10.14.5+ as far as I know, at least that is what I have been doing.

**Comment by nieder** [comment]
Yes, 10.14.5 and 10.15 are both at systemperl=5.18.4.

This assumes 10.15.2 did not bump systemperl. It did bump uname from 19.0.0 to 19.2.0, but 10.15.2 bricked my 10.15VM, so I haven't had a chance to confirm the darwin version change or if perl stayed at 5.18.4

**Comment by TheSin-** [comment]
I can confirm it is indeed 19.2.0

**Comment by nieder** [comment]
Commit 86a4bbf1 added convert-binhex-pm to Dist:10.14 (we already long had it available to 10.14.5 and 11.0).
