### ISSUE TITLE
ocaml-extlib build issues

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#537]
```
env LANG=C LC_ALL=C /opt/sw/bin/tar  --no-same-owner --no-same-permissions -xf /opt/src/extlib-1.5.3.tar.gz
sudo -u fink-bld [ENV] sh -c /tmp/fink.mmUt8
touch odoc_style.css
mkdir out
ocaml install.ml -b -n -doc -d out
File "command line", line 1:
Error: Unbound module Pervasives
### execution of ocaml failed, exit code 2
```

**Comment by TheSin-** [comment]
could be related to #538

**Comment by TheSin-** [comment]
https://github.com/stevenvar/OMicroB/issues/13#issuecomment-467527579

**Comment by TheSin-** [comment]
This package also installs improperly, here is my working version.

I can commit it if everyone is okay with it.

```
PatchScript: <<
  perl -pi -e 's,ocamlfind install,ocamlfind install -destdir=build,g' Makefile
<<
CompileScript: <<
  make
  make cmxs
  make doc
<<
InstallScript: <<
  mkdir build
  make install
  mkdir -p %i/lib/site-lib
  mv build/* %i/lib/site-lib/
  mkdir -p %i/share/doc
  mv doc %i/share/doc/ocaml-lib
<<
```

**Comment by nieder** [comment]
Does 46bad2a fix the build problem? Or does it still need the modified *Script changes?
Should it be updated to something newer than 5 years old? Or is the rest of the ocaml stack too old?

**Comment by TheSin-** [comment]
I think the findlib issue fix should fix this I'll test it tomorrow.

**Comment by nieder** [comment]
@TheSin- ping? did the fix work with findlib?

**Comment by TheSin-** [comment]
Shoot sorry I forgot to reply, it did indeed work just did my second install with it and it wasn’t an issue at all

**Comment by nieder** [comment]
Thanks
