### ISSUE TITLE
checksum doesn't match on tgif.patch

### ISSUE THREAD

**Issue by okayamat** [fink/fink-distributions#570]
On Mac OS X 10.9, "fink update tgif" failed with the following message:

Failed: PatchFile "/sw/fink/dists/stable/main/finkinfo/graphics/tgif.patch" checksum does not match!
Actual: 7c3043690af5e61a3cd07d9a588f6902
Expected: ab8a88563553aa5d82acf760c21ceb79

**Comment by nieder** [comment]
Look OK here after a fresh selfupdate:
```
$ fink validate /sw/fink/dists/stable/main/finkinfo/graphics/tgif.info 
Validating package file /sw/fink/dists/stable/main/finkinfo/graphics/tgif.info...
Package looks good!
$ md5 /sw/fink/dists/stable/main/finkinfo/graphics/tgif.patch 
MD5 (/sw/fink/dists/stable/main/finkinfo/graphics/tgif.patch) = ab8a88563553aa5d82acf760c21ceb79
```
Check for a local change. If you're using selfupdate-git (vs rsync), run `git status` inside `/sw/fink/dists/stable` and that'll tell you if something is changed. Also check whether you have some other tgif.info floating around: `fink dumpinfo -finfofile tgif`. That should point to `/sw/fink/dists/stable/main/finkinfo/graphics/tgif.info`

**Comment by okayamat** [comment]
Thank you for your reply. I found that hnd.jp.asi.finkmirrors.net (165.242.110.160) synced with a wrong git repository, https://github.com/danielj7/fink-dists . Now it syncs with https://github.com/fink/fink-distributions and the issue solves.
