### ISSUE TITLE
perlXYZ no longer pass tests in year 2020 (time::local bug)

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#579]
As of Jan 1, 2020, the perl packages fail tests here:
```
cpan/Time-Local/t/Local ....................................... #   Failed test 'timelocal year for 1970 1 2 0 0 0'
#   at t/Local.t line 104.
#          got: '170'
#     expected: '70'
FAILED at test 6
```
This is apparently a known bug in the bundled Time::Local in our Perls.

https://github.com/Perl/perl5/issues/17410
https://rt.cpan.org/Public/Bug/Display.html?id=124787 (has patch but doesn't apply cleanly to perl < 5.26.

**Comment by nieder** [comment]
time-local-pm also suffers from this. Our %v is 1.2300, but upstream went back to sane numbering and current upstream is 1.30.

**Comment by dmacks** [comment]
Thanks for pushing the patch to time-local-pm (1066ff10ff8ee7e0e9ac665d181d4acb5b8e962b). I pushed the new upstream version (2bfe2917714a7298390ad85dc2e28b042d93ae05)
