### ISSUE TITLE
Request for packaging Nuspell

### ISSUE THREAD

**Issue by PanderMusubi** [fink/fink-distributions#588]
Please package [Nuspell](https://nuspell.github.io/). This is a FOSS spell checking library and command-line tool written in modern C++ which supports the Hunspell dictionary format.

See the packages and ports already available at https://github.com/nuspell/nuspell/wiki/Nuspell-packaged-binaries including support for brew at https://github.com/nuspell/misc-nuspell/tree/master/packaging Let me know if you have any questions.

**Comment by nieder** [comment]
nuspell is now available as libnuspell3-shlibs, libnuspell3-dev, & nuspell packages (lib, headers, binary)

**Comment by PanderMusubi** [comment]
Thanks very much! How long does it usually take to see it appear in http://pdb.finkproject.org/pdb/browse.php?summary=nuspell ?

**Comment by nieder** [comment]
I think the database refreshes every hour or so. I'm not sure of the exact cycle length, but should be today.
