### ISSUE TITLE
Dependency Error in coot

### ISSUE THREAD

**Issue by JoseAlvarado95** [fink/fink-distributions#590]
Have an error pop up when running the command "fink install coot" 

Error: Can't resolve dependency "gcc5-shlibs (>= 5.1.0-2)" for package "coot-0.8.9-2"
(no matching packages/versions found)
Exiting with failure.

I'm on OS X 10.15.4

**Comment by nieder** [comment]
See issue #561.

Coot is set to use gcc5 but gcc5 will not build on 10.15, so coot needs to be migrated to gcc9. You can do this locally while #561 gets approved by downloading the file https://raw.githubusercontent.com/fink/fink-distributions/dcf98e79e6f42902c7b415eae1c92fe11f88c45d/10.9-libcxx/stable/main/finkinfo/sci/coot.info to /opt/sw/fink/dists/local/main/finkinfo.

**Comment by dmacks** [comment]
Closing via ea0ac49 based on #561
