### ISSUE TITLE
libidn2.0-shlibs-2.3.0-1 fails Xcode 11.3.1

### ISSUE THREAD

**Issue by sth0** [fink/fink-distributions#613]
I am trying to rebuild my standard fink installation in the new /opt/sw location.  I have reinstalled and updated fink and the info files.

I am now building a set of packages that I normally use.

In building libidn2.0-shlibs there is an issue.  The build completes but then has a section where it is trying to update previously build libraries (I think???).
```
Looking for incorrect headers in 99 dependency files...
Determining fink providers of 11 headers...
	1 - 11
Found use of headers from 3 fink packages:
	libgettext8-dev
	libiconv-dev
	libunistring2
Scanning binaries for incorrect dyld linking...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: error: 'f50beb464cc75859f6601c0c60b9d01b6f731ce4': The end of the file was unexpectedly encountered
Error reading /usr/bin/otool -L:  256
### execution of fink-package-precedence failed, exit code 1
### execution of /tmp/fink.fU2Pd failed, exit code 1
```
Any ideas of where that error code is triggered and getting that weird error?  As you can imagine, libidn is used by a lot of packages.

MacOS Mojave 10.14.6
Xcode 11.3.1

Fink reports 10.14.5 while About this Mac reports 10.14.6 and I know I ran the update:
```
% fink --version
Package manager version: 0.45.1
Distribution version: selfupdate-rsync Tue Apr 21 17:34:58 2020, 10.14.5, x86_64
Trees: local/main stable/main
```
-Scott

**Comment by nieder** [comment]
WFM on 10.13 and 10.14.6/Xcode11.3.1.

The 10.14.5 in `fink --version` refers to the Fink distribution, not the macOS version. Apple changed things between 10.14.4 and 10.14.5, so we had to make a new distribution to deal with that mess.

Is this error repeatable?
Is your Fink install on the main drive or on a mounted/external drive?

**Comment by sth0** [comment]
Got it, the 10.14.5 directory is linked to the 10.9-libcxx directory.  So that is the link being used.

Error is repeatable.  Fink is installed on main drive.

Did a "fink self-update" (now in git mode) "fink cleanup all" and "fink index"

Then attempted to do a "fink install libidn2.0-shlibs"
There are 3 compiler wanings.
```
  CC       libidn2_cmd_la-idn2_cmd.lo
In file included from idn2.c:37:
../gl/gettext.h:227:19: warning: variable length array used [-Wvla]
  char msg_ctxt_id[msgctxt_len + msgid_len];
                  ^
../gl/gettext.h:275:19: warning: variable length array used [-Wvla]
  char msg_ctxt_id[msgctxt_len + msgid_len];
                  ^
idn2.c:153:13: warning: string literal of length 28846 exceeds maximum length 4095 that ISO C99 compilers are required to support [-Woverlength-strings]
      puts (CONDITIONS);
            ^~~~~~~~~~
./blurbs.h:35:3: note: expanded from macro 'CONDITIONS'
  "                       TERMS AND CONDITIONS\n"                       \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
```
And then at the end the same error.
```
Looking for incorrect headers in 99 dependency files...
Determining fink providers of 11 headers...
	1 - 11
Found use of headers from 3 fink packages:
	libgettext8-dev
	libiconv-dev
	libunistring2
Scanning binaries for incorrect dyld linking...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: error: 'f50beb464cc75859f6601c0c60b9d01b6f731ce4': The end of the file was unexpectedly encountered
Error reading /usr/bin/otool -L:  256
### execution of fink-package-precedence failed, exit code 1
### execution of /tmp/fink.wWvpL failed, exit code 1
Removing runtime build-lock...
Removing build-lock package...
/opt/sw/bin/dpkg-lockwait -r fink-buildlock-libidn2.0-shlibs-2.3.0-1
```
Is there a corrupted binary/library in my fink installation that otool is running into?  How do I find which file was corrupted?

**Comment by nieder** [comment]
The compiler warnings are fine. They're not causing the failure.

Something is screwy with that `f50beb464cc75859f6601c0c60b9d01b6f731ce4` file.
From a successful build directory:
```
$ otool -L *
002a1654f105de94a466cc85db5c3ec0bd0803eb: is not an object file
00b6a0179b54693e37beb5142dce63bb852b8a0b: is not an object file
... lots more of these, which is the expected result ...
f389b6c6431e12b0ef94c02c3e1dce8f237b53d6: is not an object file
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'f50beb464cc75859f6601c0c60b9d01b6f731ce4': The end of the file was unexpectedly encountered
```

Do you have the command line tools installed, or only Xcode?

**Comment by sth0** [comment]
Yes, I have the command line tools installed.
```
Xcode.app: 11.3.1
Xcode command-line tools: 11.3.0.0.1.1574140115
```
I didn't realize that was an actual file created during the build process.  How was a successful build able to ignore that file during the scan that causes the issue.  All the builds should scan and find that file?
`Scanning binaries for incorrect dyld linking...`

**Comment by nieder** [comment]
`f50beb464cc75859f6601c0c60b9d01b6f731ce4` is part of the tarball. On my 10.13, when I scan it with /usr/bin/otool (which is a mirror of /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool) or with /Library/Developer/CommandLineTools/usr/bin/otool, I get the error. But when I use

Do you have `/Library/Developer/CommandLineTools/usr/bin/otool-classic` ? fink-package-precedence defaults to that if present, and only calls /usr/bin/otool if not found. But if you have the command line tools, then otool-classic should be there.

**Comment by sth0** [comment]
Just to note.  In building lcms2 I am getting the same error with a different file.  I think there is something wrong with the entire searching for incorrect dyld linking process and it is picking up files of the incorrect type.
````
Looking for incorrect headers in 44 dependency files...
Determining fink providers of 7 headers...
	1 - 7
Found use of headers from 2 fink packages:
	libjpeg9
	libtiff5
Scanning binaries for incorrect dyld linking...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: error: 'toosmall.icc': The end of the file was unexpectedly encountered
Error reading /usr/bin/otool -L:  256
### execution of /tmp/fink.3eJpg failed, exit code 1
````

**Comment by sth0** [comment]
I did a clean install of Developer tools and it surprisingly put very little in /Library/Developer.  Under Xcode 11.3, the developer tools seem to be installed in Xcode itself.  The otool-classic is at:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic
Should fink start to look there for certain versions of the CLT?

**Comment by nieder** [comment]
The Command Line Tools should be putting everything/most? into `/Library/Developer/CommandLineTools`. That's my experience on 10.12-10.15.

The package fink-package-precedence prefers `/Library/Developer/CommandLineTools/usr/bin/otool-classic` if present (line 315) and only falls back to `/usr/bin/otool` if absent. Your error mentions `/Applications/Xcode.app`, which is what `/usr/bin/otool` actually runs. You don't have otool-classic in /Library/Developer/CommandLineTools/usr/bin ?

**Comment by sth0** [comment]
No I do not have tool-classic in /Library/Developer/CommandLineTools/usr/bin.
I will re-install the CommandLine Tools.  Fink was telling me that I had command line tools installed so I was confused that another install was needed.

**Comment by sth0** [comment]
After the install of the CLT it builds but gives me the warning:
````
WARNING: Xcode.app version (11.3) and Xcode Command Line Tools version (10.3)
may not be compatible.
You may experience build errors.
````
Which I did not have before and now seems ominous...

**Comment by nieder** [comment]
It's best to keep your xcode.app and command line tools in sync. It mostly works when mismatched but there are cases where header incompatibilities between different Xcode/CLT versions cause problems.

After the CLT reinstall, you do have `/Library/Developer/CommandLineTools/usr/bin/otool-classic` ?

One thing we've noticed in the past is that system updates kill parts of the CommandLineTools. So even if there are still files in `/Library/Developer/CommandLineTools`, it might not be a full install and you need to reinstall them. Xcode.app itself is not affected when Apple does this.

**Comment by sth0** [comment]
I have been trying to keep it in sync.  It seems that "Xcode-select --install" does not install the same version as the Xcode version you have.  Going to the developer site and specifically getting the download for the CLT you need is the only way to keep in sync?

Yes!  Installing the CLT from the developer site fixed all these random errors.

**Comment by nieder** [comment]
If there's a partial install, `xcode-select --install` will say they're already installed, even though it's not really true (Good job, Apple!). You either redownload direct from developer.apple.com, or `sudo rm -r /Library/Developer/CommandLineTools` and then you can run `xcode-select --install`. The first option is much safer.

Closing since it seems solved.
