### ISSUE TITLE
fink-package-precedence should also check for Xcode.app otool-classic

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#616]
Currently, f-p-p checks for otool-classic from the command line tools, and if not found, falls back to `/usr/bin/otool` (which is a stub pointing to the version inside Xcode.app). If the CLT otool-classic is not found, it should then check for Xcode.app's otool-classic, and only fallback to `/usr/bin/otool` if neither location for otool-classic is found.

**Comment by dmacks** [comment]
I don't have access to a machine with the latest xcode suites. What is the path to otool-classic?

**Comment by nieder** [comment]
Default location is `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic`.

The path inside Xcode.app can be found with `xcode-select -print-path`, which yields "/Applications/Xcode.app/Contents/Developer". The "Toolchains..." part should be constant.

Forgot to say, this was triggered y #613 where screwy files were messing with 'normal' otool, but otool-classic was OK (but missing from the CLT after a system update without reinstalling the CLT). So this would add an extra safety cushion.
