### ISSUE TITLE
gnuplot needs emacs to build docs

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#619]
During InstallScript, gnuplot* needs emacs to build gnuplot.texi. Either our emacsen or `/usr/bin/emacs` works. But macOS 10.15.4 got rid of `/usr/bin/emacs`. What's preferred:
1) add a `BuildDepends: emacsen` to the gnuplot packages for everyone, or
2) make a separate gnuplot*.info file for 10.15 that has `BuildDepends: emacsen` ?

**Comment by nieder** [comment]
Other option: add a check at the beginning of CompileScript for `which emacs` and fail if not found with a helpful message to install a Fink emacs. We don't care which source (system/fink) or emacs version it has available. We just need one present.

**Comment by akhansen** [comment]
I'd go with a separate 10.15 .info file, personally.

**Comment by akhansen** [comment]
It's going to be more complicated.  With emacs26-nox installed I got the following:
...
Making install-info in docs
if test "emacs" != no; then \
	   test ".." = ".." || cp ./gnuplot.doc . ; \
	   emacs -batch -q --no-site-file -l doc2texi.el -f d2t-doc-to-texi ; \
	   test ".." = ".." || rm -f ./gnuplot.doc ; \
	else \
	   echo "No emacs found - cannot create texinfo file" ; \
	fi
Inserting help for terminals ...
Match data clobbered by buffer modification hooks
makeinfo -I. gnuplot.texi --no-split --output=gnuplot.info
could not open gnuplot.texi: No such file or directory
...

emacs25-nox worked.  
I don't happen to have the scroll back handy, but running the "emacs ..." command manually in the build directory gave an error message with emacs26-nox, so emacsen as a BuildDep won't cut it.

**Comment by nieder** [comment]
Interesting. I tried emacs26-app this morning as my selection and it worked. I'll try 26 and 26-nox later to see if I get the same error.

**Comment by nieder** [comment]
emacs26 and emacs25-nox works.

emacs26-nox also fails for me (on 10.15 and 10.13), but manually running (after chowning %b to me) `make install-info DESTDIR=%d` or `emacs -batch -q --no-site-file -l doc2texi.el -f d2t-doc-to-texi` in the build directory succeeds.
But if I run the emacs command directly inside gnuplot's InstallScript, it fails:
```
cd docs
 emacs -batch -q --no-site-file -l doc2texi.el -f d2t-doc-to-texi
Inserting help for terminals ...
Match data clobbered by buffer modification hooks
### execution of /tmp/fink.Ucj7j failed, exit code 255
```

**Comment by nieder** [comment]
The issue seems to be somplace in the `d2t-get-terminals()` function in gnuplot-5.0.7/docs/doc2texi:
https://sourceforge.net/p/gnuplot/gnuplot-main/ci/master/tree/docs/doc2texi.el#l465

Specifically, someplace in this code between `setq` and `replace-match`
```emacs
                (while (re-search-forward "^1[ \t]+\\(.+\\)$" nil t)
                  (setq node   (match-string 1)
                        marker (point-marker))
                  (replace-match (concat "3  " node) nil nil))
```
This is part of a whole bunch of nested loops that are processed at least partway, so at some iteration through one of those lopps, it grabs (or fails to grab?) something that disagrees with it (counting debugging output suggests loop 55 out of 59 in a successful build).

https://emacs.stackexchange.com/questions/38800/match-data-clobbered-by-buffer-modification-hooks suggests that using `save-match-data()` can help, but I haven't found the right magic.

This of course doesn't explain why it only fails with emacs26-nox.

**Comment by nieder** [comment]
The following patch seems to get rid of the immediate issue:
```diff
@@ -513,7 +523,7 @@
                 (while (re-search-forward "\\\\\"" nil t)
                   (replace-match "\"" nil nil))
                 (goto-char (point-min))
-                (while (re-search-forward "^1[ \t]+\\(.+\\)$" nil t)
+                (while (save-match-data(re-search-forward "^1[ \t]+\\(.+\\)$" nil t))
                   (setq node   (match-string 1)
                         marker (point-marker))
                   (replace-match (concat "3  " node) nil nil))
```
But that causes a hang later on in the `d2t-get-eldoc-strings` function, even with emacs26.
Hopefully this provides enough details for someone who knows emacs to fix doc2texi.el so it no longer dies.

We should at least push forward with a change to gnuplot to BDep on `emacs26-app | emacs26 | emacs25-nox | emacs25 | emacs24-nox | emacs24 | emacs23-nox | emacs23-app | emacs23`

**Comment by nieder** [comment]
So gnuplot through 5.4.5 (latest release) all fail similarly. But current git head does create gnuplot.texi (but fails later when using it for gnuplot.info).

Now to bisect the failure first failure
