### ISSUE TITLE
Python 2.7 fails build on Mac OS 10.14

### ISSUE THREAD

**Issue by sth0** [fink/fink-distributions#624]
The build for Python 2.7 fails and shows an error with the 10.14 SDK, and fails to build.  The include file is changed between the 10.14 and 10.15 SDK.  And the file inside of Xcode that is merely labeled MacOS.sdk is the same as the 10.15 SDK of the command line tools.  Go figure.

In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:98:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/CMSDecoder.h:130:5: **error: expected function body after function declarator**
    __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_5, __MAC_10_13, __IPHONE_NA, __IPHONE_NA,
    ^

I am attaching the entire build log for reference.

Package manager version: 0.45.1
Distribution version: selfupdate-git Mon May 11 08:58:03 2020, 10.14.5, x86_64
Trees: local/main stable/main
Xcode.app: 11.3.1
Xcode command-line tools: 11.3.1.0.1.1576735732
Max. Fink build jobs:  16
[Fink-python27-err.txt](https://github.com/fink/fink-distributions/files/4609787/Fink-python27-err.txt)

**Comment by dhomeier** [comment]
Not sure if this is related, since it seems non-fatal; but further up your log shows two more errors:
```
gcc -fno-strict-aliasing -Wno-nullability-completeness -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -I/opt/sw/include/ncu
rsesw -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/opt/sw/include -I/opt/sw/src/fink.bui
ld/python27-2.7.18-1/Python-2.7.18/Include -I/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18 -c /opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Mo
dules/readline.c -o build/temp.macosx-10.14-x86_64-2.7/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.o
/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.c:891:5: error: use of undeclared identifier 'rl_completion_suppress_append'
    rl_completion_suppress_append = 0;
    ^
/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.c:1016:5: error: use of undeclared identifier 'rl_catch_signals'
    rl_catch_signals = 0;
    ^
```
Those variables are defined in %p/include/readline/readline.h - perhaps you should try to rebuild/reinstall readline6?

**Comment by sth0** [comment]
I have reinstalled readline6-shlibs.  Readline 6 keeps getting uninstalled due to conflicts with readline7.
I get the same errors.

I get the same errors with readline6 installed as well.
% grep -i error: Desktop/Fink-python27-err.txt 
/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.c:891:5: error: use of undeclared identifier 'rl_completion_suppress_append'
/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.c:1016:5: error: use of undeclared identifier 'rl_catch_signals'
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/CMSDecoder.h:130:5: error: expected function body after function declarator
% fink list readline
Information about 12582 packages read in 1 seconds.
 i   readline6                                         6.3.8-2                               Comfortable terminal input library
 i   readline6-shlibs                                  6.3.8-2                               Comfortable terminal input library
     readline7                                         7.0.pl5-2                             Comfortable terminal input library
 i   readline7-shlibs                                  7.0.pl5-2                             Comfortable terminal input library

The file /opt/sw/include/readline/readline.h exists and defines rl_catch_signals and rl_completion_suppress_append as external variables.   All the gcc commands have -I/opt/sw/include in them but not -I /opt/sw/include/readline where the header file actually is.  The ncurses subdirectory is explicitly included -I/opt/sw/include/ncursesw

Should line 86 of the .info file
	export CPPFLAGS="-I%p/include -I%p/include/ncursesw -I$SDK_PATH/usr/include”
be changed to
	 export CPPFLAGS="-I%p/include -I%p/include/ncursesw -I%p/include/readline -I$SDK_PATH/usr/include"

???

-Scott

**Comment by dhomeier** [comment]
> The file /opt/sw/include/readline/readline.h exists and defines rl_catch_signals and rl_completion_suppress_append as external variables. All the gcc commands have -I/opt/sw/include in them but not -I /opt/sw/include/readline where the header file actually is. The ncurses subdirectory is explicitly included -I/opt/sw/include/ncursesw Should line 86 of the .info file export CPPFLAGS="-I%p/include -I%p/include/ncursesw -I$SDK_PATH/usr/include” be changed to export CPPFLAGS="-I%p/include -I%p/include/ncursesw -I%p/include/readline -I$SDK_PATH/usr/include"

no, Python's `readline.c` has `#include <readline/readline.h>`, so it should find it (and I think would raise an error earlier otherwise).
I cannot find any macros in `readline.h` that might cause your compiler version to miss those identifiers, but FWIW on 10.12 I've been able to build python27 against readline7-7.0pl5 as well. So you might try and replace the `readline6` `Depends` and `BuildDepends` with `readline7` - just a wild guess, but maybe it gets you further along...

**Comment by nieder** [comment]
The readline errors are a -I path ordering problem.
`Python-2.7.18/Modules/readline.c` has `#include <readline/readline.h>`, so we only need `-I%p/include` in the compiler command. The problem is that the command has `-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/opt/sw/include`, which means the build first finds the system header before Fink's.

**Comment by nieder** [comment]
So the trick is to find a way to force the SDK headers on 10.14/15 to the very end of the compiler command. flag-sort could work here, but I don't know if it might get internalized into the installed python files, like it does in the r-baseXX packages.

**Comment by sth0** [comment]
This is also a problem in building Python 3.8 as well I have found.  That seems to be the same error.

Use of flag-sort is a bit beyond my knowledge or ability to find documentation.  Does it just sort relative vs. absolute path flags?

However, the .info file has the CPPFLAGS in the “correct” order with SDK reference last.

However, it seems to edit the Include path in the setup.py file with:
	 perl -pi -e "s|/usr/include|$SDK_PATH/usr/include|” setup.py
which changes the default headers to the SDK path.

-Scott

**Comment by dhomeier** [comment]
> However, it seems to edit the Include path in the setup.py file with: perl -pi -e "s|/usr/include|$SDK_PATH/usr/include|” setup.py which changes the default headers to the SDK path.

That is intended since AFAIK 10.14 or at least 10.15 no longer has `/usr/include` at the root level; however I am not sure it is really necessary since `setup.py` already seems to provide for a detection mechanism for the correct path in `macosx_sdk_root()`.

But the problem with the wrong order actually seems to originate in `detect_modules`, which is then adding all include dirs obtained from the `CPPFLAGS` _in reverse order_; since `setup.py` has been patched to add `%p/include` to `include_dirs` first of all, it is then shifted to the back Changing the order of `CPPFLAGS` won't help with this, since it is already present in `include_dirs`; in fact _without_ `%p/include` added earlier on or through `CPPFLAGS`, it would be prepended last from `INCLUDEDIR=%p/include`, which is also set in Makefile.
You could try to turn the trick around by switching the order back to
```
                perl -pi -e "s|(self.compiler.include_dirs, .)(%p/include)|\${1}$SDK_PATH/usr/include|" setup.py
```
in the block for the 10.14 setup, or maybe there's a better way to set the INCLUDEPATH with `./configure`, but that's difficult to test without a 10.14 system.

**Comment by dhomeier** [comment]
> This is also a problem in building Python 3.8 as well I have found. That seems to be the same error. Use of flag-sort is a bit beyond my knowledge or ability to find documentation. Does it just sort relative vs. absolute path flags?

@sth0 in Python 3 the compiler is organised within different functions, but seems to follow the same lines:

1. Always add the `/usr/local` paths (i.e. _insert_ them at position 0 in the library and include search paths). This is changed to `%p` by the Fink patch resp. info files.

2. Add (i.e. insert) any paths extracted from `LDFLAGS` and `CPPFLAGS` in the Makefile, preserving their relative order.

3. Insert `INCLUDEDIR` and `LIBDIR` from `Makefile` (which are set to the Fink paths thanks to `./configure --prefix=%p`).

So normally `#3` would correctly put the Fink paths to the front, if they had not already been patched in in `#1`.
I have just pushed an update for 3.8.3 to #540 with that first patch removed, and verified that it still finds the `%p` include and library paths without this on 10.12. If you want to give it a try; I cannot really predict if it will help with the second failure in the `_scproxy` build...

**Comment by nieder** [comment]
The error from the original log:
> gcc -fno-strict-aliasing -Wno-nullability-completeness -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -I/opt/sw/include/ncursesw -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/opt/sw/include -I/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Include -I/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18 -c /opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.c -o build/temp.macosx-10.14-x86_64-2.7/opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.o
> /opt/sw/src/fink.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.c:891:5: error: use of undeclared identifier 'rl_completion_suppress_append'


This is what I get on my 10.14/Xcode11.3.1 VM:
> gcc -fno-strict-aliasing -Wno-nullability-completeness -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -I/sw/include/ncursesw -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/sw/include -I/sw/build.build/python27-2.7.18-1/Python-2.7.18/Include -I/sw/build.build/python27-2.7.18-1/Python-2.7.18 -c /sw/build.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.c -o build/temp.macosx-10.14-x86_64-2.7/sw/build.build/python27-2.7.18-1/Python-2.7.18/Modules/readline.o


The two lines are identical except for the Fink path (/opt/sw vs /sw). My log only shows some warnings about `/sw/include/readline/rltypedefs.h`, via /sw/include/readline/readline.h. So it's finding our readline, and the SDK `readline/readline.h` also exists, so besides all the path funkyness you listed above, why are similar commands giving different results?

**Comment by dmacks** [comment]
The python build system is a mystery to me:( What if you created %b/gcc as a shell script that called ```flag-sort gcc "$@"```, and prepended %b to PATH? If that works and seems like a generally useful idea (fix the problem, no risk of its bits in the build system), I could ask flag-sort maintainer to supply %p/var/lib/flag-sort-compilers/gcc and friends.

**Comment by nieder** [comment]
1) The compiler used is hardcoded in `_sysconfigdata.py`, so we can't call flag-sort directly.
2) Using
```bash
#!/bin/sh
flag-sort gcc "$@"
```
hangs immediately after the compiler check.

**Comment by dhomeier** [comment]
The way `setup.py` treats the paths seem fairly clear to me now along the lines described in https://github.com/fink/fink-distributions/issues/624#issuecomment-628873877, but I have not seen any results on what effect removing that unfortunate `perl -pi -e 's|/usr/local|%p|' setup.py` has on a 10.14 or 10.15 system so far.

**Comment by dhomeier** [comment]
The compiler behaviour remains just as mysterious to me, though. I had made similar tests directly calling the compiler on `readline.c` with `-I/usr/include` in front of `/sw/include`only encountering the same warnings as @nieder ; but now repeated the experiment (still on 10.12) with `-I$SDKPATH/usr/include -I/sw/include`, getting the same errors as @sth0.
Of course the `readline.h` files in `/usr` and `$SDKPATH/usr` are identical versions of the 8-year-old system readline!

**Comment by nieder** [comment]
I really wish I could make python fail locally. All the following build for me:
* 10.13
* 10.14.4 with just the CLT @ 10.1
* 10.14.4 with CLT/xcode.app @ 10.2.1
* 10.14.6 with CLT/xcode.app @ 11.3.1
* 10.15.4 with CLT/xcode.app @ 11.4

They all build python27-2.7.18-1 with no problems :(

**Comment by nieder** [comment]
See https://sourceforge.net/p/fink/mailman/message/37031093/ and https://sourceforge.net/p/fink/mailman/message/37031130/ for a possible cause & solution to some of the python misbuilds, even after using #540.
There seem to be cases where the SDK links are mismatched between what's installed inside Xcode.app and the Command Line Tools, so things fail no matter how much we improve the python build process.
