### ISSUE TITLE
nut-snmp missing BDep on libnetsnmp

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#636]
nut-snmp can grabs system-libnetsnmp if Fink's libnetsnmp is not present. This causes a build failure on 10.14.5 because `/usr/bin/net-snmp-config --libs` doesn't return enough information to find the libraries. (Build)Depending on libnetsnmp35 should work to provide deterministic builds.

**Comment by dmacks** [comment]
#543 landed
