### ISSUE TITLE
libserf1 FTBFS with scons3

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#637]
With scons-3, libserf1 build fails:
```
scons PREFIX=/sw CFLAGS=-m64 LINKFLAGS=-Wl,-dead_strip_dylibs,-arch,x86_64 APR=/sw/bin/apr-1-config APU=/sw/bin/apu-1-config OPENSSL=/sw GSSAPI=/usr/bin/krb5-config $MAKEFLAGS
scons: Reading SConscript files ...
Checking for GNU-compatible C compiler...yes
ValueError: too many values to unpack:
  File "/sw/build.build/libserf1-1.3.9-2/serf-1.3.9/SConstruct", line 293:
    lib_shared = env.SharedLibrary(LIBNAME, SOURCES + SHARED_SOURCES)
  File "/sw/lib/scons/SCons/Environment.py", line 260:
    return MethodWrapper.__call__(self, target, source, *args, **kw)
  File "/sw/lib/scons/SCons/Environment.py", line 224:
    return self.method(*nargs, **kwargs)
  File "/sw/lib/scons/SCons/Builder.py", line 645:
    return self._execute(env, target, source, OverrideWarner(kw), ekw)
  File "/sw/lib/scons/SCons/Builder.py", line 564:
    tlist, slist = self._create_nodes(env, target, source)
  File "/sw/lib/scons/SCons/Builder.py", line 528:
    target, source = self.emitter(target=tlist, source=slist, env=env)
  File "/sw/lib/scons/SCons/Builder.py", line 353:
    target, source = e(target, source, env)
  File "/sw/lib/scons/SCons/Tool/link.py", line 106:
    return _lib_emitter(target, source, env, symlink_generator=SCons.Tool.ShLibSymlinkGenerator)
  File "/sw/lib/scons/SCons/Tool/link.py", line 95:
    symlinks = symlink_generator(env, target[0])
  File "/sw/lib/scons/SCons/Tool/__init__.py", line 634:
    symlinks = self.generate_versioned_lib_info(env, [libnode, version, prefix, suffix], **kw2)
  File "/sw/lib/scons/SCons/Tool/__init__.py", line 527:
    return _call_linker_cb(env, callback, args, result)
  File "/sw/lib/scons/SCons/Tool/__init__.py", line 382:
    result = cbfun(env, *args)
  File "/sw/lib/scons/SCons/Tool/link.py", line 242:
    return _versioned_lib_symlinks(env, libnode, version, prefix, suffix, name_func, soname_func)
  File "/sw/lib/scons/SCons/Tool/link.py", line 217:
    soname = soname_func(env, libnode, version, prefix, suffix)
  File "/sw/lib/scons/SCons/Tool/applelink.py", line 79:
    return _applelib_versioned_lib_soname(env, libnode, version, prefix, suffix, link._versioned_shlib_name)
  File "/sw/lib/scons/SCons/Tool/applelink.py", line 72:
    (libname,_suffix) = name.split('.')
```
See https://sourceforge.net/p/fink/mailman/message/37038549/

Upstream has some changes in SVN to SConstruct that makes the build work, but then the library install_name is changed (because we do some hacking).
Alternatively, libserf1 builds with old scons-2.5.1 (vs 3.0.5). So could make a scons2 package for compatibility for anything that requires too much hacking?

**Comment by nieder** [comment]
OK, the problem is that upstream is trying to make the file `libserf-MAJOR.minor.patch`, but we change it to `libserf-1.0.MAJOR.minor.patch` (to keep the historical libserf-1.0.dylib install_name). That extra version token then breaks the build with scons-3.

Easiest solution will be to make scons2 package for this edge case (serf's SConstruct is a mess, like all scons).
Or just forget about backwards compatibility in trying to hack the old libN=0 name and use current libN=1, which is what everyone else is doing (Debian has libserf-1.so.1).
I've spent a good time trying to fight the different things setting install_name, compat_ver, and file name, I can get two out of the 3, but eventually scons internals fight to get primacy and we would need to use install_name_tool to edit and/or rename files.

BTW, only things that dep on libserf1 are svn19, svn-javahl, and svn-swig bindings.

**Comment by nieder** [comment]
If I don't see any comments, I'll make a scons2 package.

**Comment by dmacks** [comment]
[uninvolved, except by virtue of hating scons] Whatever solves it with minimal breakage of current and maximal sanity going forward sounds good.
