### ISSUE TITLE
qscintilla problems

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#645]
There are several problems with the qscintilla (qt4/qt5 and py bindings) packages:

1) none of the qscintilla packages seem to actually use openssl, but they all BDep on openssl100 (see #499).
2) On 10.13, qscintilla2.12-qt5-mac FTBFS:
```
In file included from qsciabstractapis.cpp:21:
In file included from ./Qsci/qsciabstractapis.h:33:
./Qsci/qsciscintilla.h:2138:25: error: implicit instantiation of undefined template 'QPointer<QsciLexer>'
In file included from     QPointer<QsciLexer> lex;qsciscintilla.cpp:23:
./Qsci/qsciscintilla.h:2138:25: error: implicit instantiation of undefined template 'QPointer<QsciLexer>'
    QPointer<QsciLexer> lex;
                        ^
<and many more similar errors>
```
qscintilla2.11-qt5-mac is dist restricted to `10.9, 10.10`, and qscintilla2.13-qt5-mac works. So `2.12` should probably also be dist restricted.

**Comment by dmacks** [comment]
I suspect the openssl dep from some long-ago and no-longer-propgating IBN. Lots of qt*-mac had that.

I have no objection to dist-restricting old versions. But for the FTBFS, here's a fix from another package that was reported to also-fix qscintilla: https://www.riverbankcomputing.com/pipermail/qscintilla/2016-October/001160.html

**Comment by nieder** [comment]
Dealt with by e8ad95e and 37fb0c1.
Since nothing uses qscintilla2.12-qt5-mac and it's an old libN, there's little sense in trying to fix it.
Closing this since the 2 issues have been dealt with it.
