### ISSUE TITLE
librtmp->librtmp1 migration

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#650]
Our librtmp (v2.3) has dependencies on openssl100 and FTBFS with openssl110, whereas librtmp1 (v2.4) does not have openssl dependencies at all. This is a tracker issue for updating package-suites with dependencies on the older libversion (see also #644)...

- [x] gst-plugins-bad-0.10 (Ben Reed; up for grabs)
- [x] libavcodec56-2.4-shlibs (snaggle)
- [x] libavcodec57-3.0-shlibs (snaggle)
- [x] libavcodec58-4.0-shlibs (snaggle)
- [x] libcurl4 (danielj)
- [x] mplayer (snaggle)

**Comment by nieder** [comment]
Feel free to update libavcodec* and mplayer to librtmp1 as needed.

**Comment by dmacks** [comment]
Just heads-up to @danielj gentoo has patch for librtmp openssl110 support:
https://gitweb.gentoo.org/repo/gentoo.git/tree/media-video/rtmpdump/files/rtmpdump-openssl-1.1-v2.patch

**Comment by dmacks** [comment]
librtmp (old libversion) is orphaned now. Should I convert it to a -shlibs stub (as usual for this situation) or nuke it altogether (since it's an openssl100 user)?

**Comment by nieder** [comment]
I say nuke. There's no reason to keep an unused libN that exposes a security issue.

**Comment by dmacks** [comment]
*poof*
