### ISSUE TITLE
Incomplete headers in hdf5.10

### ISSUE THREAD

**Issue by dhomeier** [fink/fink-distributions#651]
Building a simple C source against the headers in `hdf5.10` immediately fails with
```
cc -Iexec.p -I. '-I../test cases/frameworks/25 hdf5' -I/sw/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -g -MD -MQ exec.p/main.c.o -MF exec.p/main.c.o.d -o exec.p/main.c.o -c '../test cases/frameworks/25 hdf5/main.c'
In file included from ../test cases/frameworks/25 hdf5/main.c:4:
In file included from /sw/include/hdf5.h:24:
/sw/include/H5public.h:69:10: fatal error: 'H5api_adpt.h' file not found
#include "H5api_adpt.h"
         ^~~~~~~~~~~~~~
1 error generated.
```
– the missing file is moved into the `hdf5-cpp11` `SplitOff`, but `H5api_adpt.h` does not seem to be in any way c++ specific (and there is no `C++ informative` comment in the header) - has this just been misplaced in the splitoff configuration?

**Comment by nieder** [comment]
DescPackaging in hdf5.100.v.info says this:
```
	Revision 4: move H5api_adpt.h into main package so that netcdf* HDF5 detection works
	without installing the cpp package.  (Kind of weird since this file seems like it's
	for DLLs, but whatever.)  No real reason this was in the cpp package, anyway.
```
On my system, `hdf5.100.v1.10_1.10.0-4_darwin-x86_64.deb` has `%p/opt/hdf5.v1.10/include/H5api_adpt.h`. Do you need the old hdf5-cpp11 (%v=1.8.16) or can you use the newer hdf5-cpp (%v=1.10.0) ?

**Comment by dhomeier** [comment]
> On my system, `hdf5.100.v1.10_1.10.0-4_darwin-x86_64.deb` has `%p/opt/hdf5.v1.10/include/H5api_adpt.h`. Do you need the old hdf5-cpp11 (%v=1.8.16) or can you use the newer hdf5-cpp (%v=1.10.0) ?

The file in question works with any of the hdf5 versions; I was rather testing if it compiles against any version of the headers that might be present on the system – as I see it, in principle Fink could have any combination of the `hdf5.9` or `hdf5.10` plus `hdf5.100.v1.8`, `hdf5.100.v1.10` headers in their respective C, C++ and Fortran incarnations installed.
As `H5api_adpt.h` is unconditionally included via `H5public.h` and `hdf5.h`, I don't see how anything could use `hdf5.10` by itself; hdf5.100.v.info seems to have got it right.

**Comment by nieder** [comment]
Then we should update all the hdf5 packages to move H5api_adpt.h out of the cpp`-dev` package and to their respective base `-dev` packages to match the change from %r=4 in hdf5.100.v.info.
