### ISSUE TITLE
Package htmldoc-nox  1.8.30-1

### ISSUE THREAD

**Issue by Basem9955** [fink/fink-distributions#657]
When trying to install htmldoc-nox  1.8.30-1 package, the installation doesn't finish and it is stuck with "Formatting htmldoc.pdf.." forever.

Here is the log:

The following package will be installed or updated:
 htmldoc-nox
Setting runtime build-lock...
dpkg-deb -b /sw/src/fink.build/root-fink-buildlock-htmldoc-nox-1.8.30-1 /sw/src/fink.build
dpkg-deb: building package `fink-buildlock-htmldoc-nox-1.8.30-1' in `/sw/src/fink.build/fink-buildlock-htmldoc-nox-1.8.30-1_2020.08.03-07.51.20_darwin-x86_64.deb'.
Installing build-lock package...
/sw/bin/dpkg-lockwait -i /sw/src/fink.build/fink-buildlock-htmldoc-nox-1.8.30-1_2020.08.03-07.51.20_darwin-x86_64.deb
Selecting previously deselected package fink-buildlock-htmldoc-nox-1.8.30-1.
(Reading database ... 28532 files and directories currently installed.)
Unpacking fink-buildlock-htmldoc-nox-1.8.30-1 (from .../fink-buildlock-htmldoc-nox-1.8.30-1_2020.08.03-07.51.20_darwin-x86_64.deb) ...
Setting up fink-buildlock-htmldoc-nox-1.8.30-1 (2020.08.03-07.51.20) ...

sudo -u fink-bld [ENV] sh -c /tmp/fink.IyzKq
env LANG=C LC_ALL=C /sw/bin/tar  --no-same-owner --no-same-permissions -xf /sw/src/htmldoc-1.8.30.tar.gz
sudo -u fink-bld [ENV] sh -c /tmp/fink.KjlgX
[ -r /sw/fink/dists/stable/main/finkinfo/text/htmldoc.patch ]
sudo -u fink-bld [ENV] sh -c /tmp/fink.CUrlq
/usr/bin/patch -p1 < /sw/fink/dists/stable/main/finkinfo/text/htmldoc.patch
patching file htmldoc/htmlsep.cxx
Hunk #1 succeeded at 518 (offset 1 line).
sudo -u fink-bld [ENV] sh -c /tmp/fink.Cz3wS
./configure --prefix=/sw --without-gui FLTKCONFIG=/bin/false --disable-localjpeg --disable-localpng --disable-localzlib ac_cv_search___res_init=-lresolv --enable-cdsassl --disable-gnutls
checking for gawk... gawk
checking for clang... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for clang++... clang++
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C preprocessor... clang -E
checking for ranlib... ranlib
checking for ar... /usr/bin/ar
checking for chmod... /bin/chmod
checking for cp... /bin/cp
checking for fltk-config... /bin/false
checking for install-sh script... using /sw/src/fink.build/htmldoc-nox-1.8.30-1/htmldoc-1.8.30/install-sh
checking for mv... /bin/mv
checking for mkdir... /bin/mkdir
checking for rm... /bin/rm
checking for pkg-config... no
checking for grep that handles long lines and -e... /sw/bin/grep
checking for egrep... /sw/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for strings.h... (cached) yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for strdup... yes
checking for strcasecmp... yes
checking for strncasecmp... yes
checking for strlcat... yes
checking for strlcpy... yes
checking for snprintf... yes
checking for vsnprintf... yes
checking for random... yes
checking for lrand48... yes
checking for arc4random... yes
checking for tm_gmtoff member in tm structure... yes
checking for pow in -lm... yes
checking for poll... yes
checking for library containing socket... none required
checking for library containing gethostbyaddr... none required
checking for library containing getaddrinfo... none required
checking for library containing getnameinfo... none required
checking for library containing hstrerror... none required
checking for library containing __res_init... (cached) -lresolv
checking resolv.h usability... yes
checking resolv.h presence... yes
checking for resolv.h... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for long long int... yes
checking for strtoll... yes
checking Security/SecureTransport.h usability... yes
checking Security/SecureTransport.h presence... yes
checking for Security/SecureTransport.h... yes
checking Security/SecureTransportPriv.h usability... no
checking Security/SecureTransportPriv.h presence... no
checking for Security/SecureTransportPriv.h... no
checking Security/SecCertificate.h usability... yes
checking Security/SecCertificate.h presence... yes
checking for Security/SecCertificate.h... yes
checking Security/SecItem.h usability... yes
checking Security/SecItem.h presence... yes
checking for Security/SecItem.h... yes
checking for Security/SecItemPriv.h... no
checking Security/SecPolicy.h usability... yes
checking Security/SecPolicy.h presence... yes
checking for Security/SecPolicy.h... yes
checking Security/SecPolicyPriv.h usability... no
checking Security/SecPolicyPriv.h presence... no
checking for Security/SecPolicyPriv.h... no
checking Security/SecBasePriv.h usability... no
checking Security/SecBasePriv.h presence... no
checking for Security/SecBasePriv.h... no
checking Security/SecIdentitySearchPriv.h usability... no
checking Security/SecIdentitySearchPriv.h presence... no
checking for Security/SecIdentitySearchPriv.h... no
configure: Using SSLFLAGS="", SSLLIBS="-framework Security -framework CoreFoundation"
checking for library containing jpeg_CreateCompress... -ljpeg
checking for library containing gzgets... -lz
checking for library containing png_set_tRNS_to_alpha... -lpng
checking if GCC supports -fno-rtti... yes
checking if GCC supports -fno-exceptions... yes
configure: creating ./config.status
config.status: creating Makedefs
config.status: creating Makefile
config.status: creating desktop/htmldoc.plist
config.status: creating config.h
/usr/bin/make
Making all in htmldoc...
Compiling array.c...
Compiling gui.cxx...
Compiling file.c...
Compiling html.cxx...
Compiling htmldoc.cxx...
Compiling htmllib.cxx...
Compiling htmlsep.cxx...
Compiling http.c...
Compiling http-addr.c...
Compiling http-addrlist.c...
Compiling http-support.c...
Compiling image.cxx...
Compiling iso8859.cxx...
Compiling license.cxx...
Compiling md5.c...
Compiling progress.cxx...
Compiling ps-pdf.cxx...
Compiling rc4.c...
Compiling snprintf.c...
Compiling string.c...
Compiling tls.c...
Compiling toc.cxx...
Compiling util.cxx...
Linking htmldoc...
Creating application bundle...
Making all in doc...
Formatting htmldoc.html...
BYTES: 116963
Formatting htmldoc.pdf...

**Comment by nieder** [comment]
@dmacks 
This is apparently a known bug upstream that catches a clang bug.
See michaelrsweet/htmldoc/issues/363 and michaelrsweet/htmldoc/issues/349

It is supposedly fixed in the latest upstream v1.9.9

**Comment by dmacks** [comment]
Thanks for the ping. I won't be able to look at it until the weekend.

**Comment by dmacks** [comment]
Sorry for the hella-long delay.
