### ISSUE TITLE
vim-8.2.1471 source download failures

### ISSUE THREAD

**Issue by dhomeier** [fink/fink-distributions#661]
Getting a 404 on the `Source` URL
```
curl --connect-timeout 30 -f -L -A 'fink/0.45.1' -O http://www.i8u.org/\~htodd/finksrc/vim-8.2.1471.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
### execution of curl failed, exit code 22
Downloading the file "vim-8.2.1471.tar.bz2" failed.
```
and the same for `http://distfiles.master.finkmirrors.net/distfiles/vim-8.2.1471.tar.bz2`.

The original source location only offers a .tar.gz version at https://github.com/vim/vim/releases/tag/v8.2.1471
so presumably would require tweaking with the checksum and more...

**Comment by htodd** [comment]
Oops. Try it now.

On Wed, 19 Aug 2020, Derek Homeier wrote:

> 
> Assigned #661 to @htodd.
> 
> ?
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE47Z6NB7EEEFK4BJIW3SBQG4TA5CNFSM4QFGNRG2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOOR
> PWSZGO3LPEA4Y.gif]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by htodd** [comment]
There's a github tarball? I would've used that if I found it back when I
first started this mess.

On Sat, 22 Aug 2020, Derek Homeier wrote:

> 
> Thanks, that did it!
> For future reference, do you think the build itself would work with the Github tarball as well?
> 
> ?
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE4ZHJHVX3ZXV6XLDAZ3SB7ZFXA5CNFSM4QFGNRG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFBZZMDA.gi
> f]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by dhomeier** [comment]
> There's a github tarball? I would've used that if I found it back when I first started this mess.

They must have introduced automatic creation of tarballs for all tags in https://github.com/vim/vim/tags some time ago.
They would need a `SourceRename`, and GitHub extracts sometimes have a limited set of DocFiles compared to the regular releases, but here the most important like README* and LICENSE seem to be included.
