### ISSUE TITLE
move openssl100-dev out of base to crypto

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#662]
`openssl100-dev.{info,patch}` live in base because cvs used to mistakenly depended on it. cvs was fixed to not explicitly have Depends on it, but the .info/patch files were kept there.

They should be moved to crypto to live alongside `openss110-dev.info`.

**Comment by dmacks** [comment]
Pushed as d3d195f2b6a2713dae539459fb054ea5424ac223. The original move was fink-core and $maintainer is AWOL, it's been months.
