### ISSUE TITLE
locale-textdomain-pm5282 fails to build on 11.0

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#665]
On 11.0, this is the failure during InstallScript (full log attached)
[fink-build-log_locale-textdomain-pm5282_1.20-3_2020.09.17-18.39.10.txt](https://github.com/fink/fink-distributions/files/5242539/fink-build-log_locale-textdomain-pm5282_1.20-3_2020.09.17-18.39.10.txt)

> Manifying 148 pod documents
Can't locate MyInstall.pm in @INC (you may need to install the MyInstall module) (@INC contains: /opt/sw3/lib/perl5/5.28.2/darwin-thread-multi-2level /opt/sw3/lib/perl5/5.28.2 /opt/sw3/lib/perl5/darwin-thread-multi-2level /opt/sw3/lib/perl5 /opt/sw3/lib/perl5/darwin /Library/Perl/5.28/darwin-thread-multi-2level /Library/Perl/5.28 /Network/Library/Perl/5.28/darwin-thread-multi-2level /Network/Library/Perl/5.28 /Library/Perl/Updates/5.28.2 /System/Library/Perl/5.28/darwin-thread-multi-2level /System/Library/Perl/5.28 /System/Library/Perl/Extras/5.28/darwin-thread-multi-2level /System/Library/Perl/Extras/5.28).
BEGIN failed--compilation aborted.

perl5184 is currently failing a single test on 11.0, so I can't test locale-textdomain-pm5184 yet.

**Comment by nieder** [comment]
If I build perl5184 w/out tests on 11.0, then I can successfully build locale-textdomain-pm5184. So the failure is due to perl5.28(.2).  Looks like `./` is not being added to `@ inc` anymore.

**Comment by dmacks** [comment]
"./ is not being added to @ inc anymore" is exactly true, starting with perl-5.26. See: https://perldoc.perl.org/perl5260delta.html#Removal-of-the-current-directory-(%22.%22)-from-%40INC

**Comment by nieder** [comment]
Upstream references:
https://github.com/gflohr/libintl-perl/commit/e044dbf297dcb34f267602ecfa44f1b36c36e60f
https://rt.cpan.org/Public/Bug/Display.html?id=120446

Is the issue preventing our upgrading locale-textdomain-pm still relevant?

**Comment by nieder** [comment]
Upstream fix WFM on 11.0

**Comment by dmacks** [comment]
The upgrading-blocker upstream ticket is confusing! https://rt.cpan.org/Public/Bug/Display.html?id=83980 I don't have enough spare box to try building it on a bare-bones and on a fully loaded system to see if it works on both.

**Comment by nieder** [comment]
Should I just push the upstream fix for `@ inc` for now while the %v upgrade is figured out?

**Comment by dmacks** [comment]
mkitso

**Comment by nieder** [comment]
Feel free to close this or leave it open for the %v bump

**Comment by nieder** [comment]
Closing (immediate fix by e0d39bf). %v bump can be dealt elsewhere
