### ISSUE TITLE
getoptbin: typo in package description

### ISSUE THREAD

**Issue by kamischi** [fink/fink-distributions#683]
Building getoptbin fails on case sensitive file systems. Log:

/bin/cp -r ChangeLog /opt/sw/src/fink.build/root-getoptbin-1.1.5-1/opt/sw/share/doc/getoptbin/
cp: ChangeLog: No such file or directory

The actual name of the file is Changelog with lowercase l.

**Comment by dmacks** [comment]
Thanks for catching that! I pushed a new version along with that fix.
