### ISSUE TITLE
Problems updating apache2: finkinfo pointing to wrong version?

### ISSUE THREAD

**Issue by Goku-UI** [fink/fink-distributions#686]
I'm trying to update apache2 in my fink distribution, but I keep getting the following error message:

> curl --connect-timeout 30 -f -L -A 'fink/0.45.2' -O http://distfiles.master.finkmirrors.net/distfiles/apache2_2.4.23.orig.tar.bz2
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   384  100   384    0     0   2752      0 --:--:-- --:--:-- --:--:--  2762
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden
> ### execution of curl failed, exit code 22
> Downloading the file "apache2_2.4.23.orig.tar.bz2" failed.

Indeed, the apache2.info file inside finkinfo/web points to version 2.4.23, but that one is nowhere to be found in the mirrors.

**Comment by nieder** [comment]
Should be fixed now.
