### ISSUE TITLE
osxfuse fails to build on at least 10.13 and 10.15 (probably many others)

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#740]
Our osxfuse is seriously old (at least 7 years) and it fails to build on at least 10.13 and up (10.12 is almost guaranteed to fail too given the few commits I could find). .
The process first builds the kext which fails to build due to bad SDK location and trying 32bit. Fixing that (I think) then the main utility fails to build with missing functions and declarations.

I'm attaching my current changes in case someone wants to give it a go. Macports stopped at v3.8.3 because upstream is apparently no longer releasing the proper source code.

Our osxfuse is only used by these other packages:
encfs
sshfs
avfs
fuse-zip
worker (through avfs)

[osxfuse.zip](https://github.com/fink/fink-distributions/files/5940357/osxfuse.zip)

**Comment by ouboub** [comment]
Hi
I need encfs on my MacBook Air running 10.15 because I have a lot of encrypted folders from by 
Ubuntu Laptop.
I am not much acquainted with fink, so how am I suppose to try out your version to make encfs to work

**Comment by nieder** [comment]
So I managed to get osxfuse to build on 10.13 with 785ebb1.
enfcs fails to build however (see #765)

**Comment by ouboub** [comment]
>>> "n" == nieder  ***@***.***> writes:

> So I managed to get osxfuse to build on 10.13 with 785ebb1.
> enfcs fails to build however (see #765)

> So I managed to get osxfuse to build on 10.13 with 785ebb1.
> enfcs fails to build however (see #765)

Thanks for that fix, any idea when and how enfcs could be fixed?

**Comment by nieder** [comment]
It's up to the encfs maintainer in #765

**Comment by ouboub** [comment]
>>> "n" == nieder  ***@***.***> writes:

> So I managed to get osxfuse to build on 10.13 with 785ebb1.
> enfcs fails to build however (see #765)

Not sure my answer went through so I resend it.

I checked again, build fails in 10.15


,----
| checking whether /Applications/Xcode.app/Contents/Developer/usr/bin/make sets $(MAKE)... yes
| checking whether /Applications/Xcode.app/Contents/Developer/usr/bin/make supports nested variables... yes
| checking how to print strings... printf
| checking for style of include used by /Applications/Xcode.app/Contents/Developer/usr/bin/make... GNU
| checking for gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
| checking whether the C compiler works... yes
| checking for C compiler default output file name... a.out
| checking for suffix of executables... 
| checking whether we are cross compiling... configure: error: in `/opt/sw/src/fink.build/osxfuse-2.7.0-1/osxfuse-fuse':
| configure: error: cannot run C compiled programs.
| If you meant to cross compile, use `--host'.
| See `config.log' for more details
| ### execution of /tmp/fink.tQPTG failed, exit code 1
| ### execution of /tmp/fink.l9j7C failed, exit code 1
| Removing runtime build-lock...
| Removing build-lock package...
| /opt/sw/bin/dpkg-lockwait -r fink-buildlock-osxfuse-2.7.0-1
| (Reading database ... 122820 files and directories currently installed.)
| Removing fink-buildlock-osxfuse-2.7.0-1 ...
| Failed: phase compiling: osxfuse-2.7.0-1 failed
| 
| Before reporting any errors, please run "fink selfupdate" and try again.
| 
| If you continue to have issues, please check to see if the FAQ on Fink's 
| website solves the problem.  If not, ask on one (not both, please) of
| these mailing lists:
| 
| 	The Fink Users List ***@***.***>
| 	The Fink Beginners List ***@***.***>.
| 
| Please try to include the complete error message in your report.  This
| generally consists of a compiler line starting with e.g. "gcc" or "g++"
| followed by the actual error output from the compiler.
| 
| Also include the following system information:
| Package manager version: 0.45.3
| Distribution version: selfupdate-rsync Sat Apr  3 12:22:51 2021, 10.15, x86_64
| Trees: local/main stable/main
| Xcode.app: 12.4
| Xcode command-line tools: 12.4.0.0.1.1610135815
| Max. Fink build jobs:  1
| 
`----

**Comment by nieder** [comment]
10.15 build failure is now fixed
