### ISSUE TITLE
Boostrap Phase 2 Failure on Catalina

### ISSUE THREAD

**Issue by Batshua** [fink/fink-distributions#774]
Here is the salient part of the log:

Err http://bindist.finkmirrors.net stable/main Packages
  404 Not Found
Get:1 http://bindist.finkmirrors.net stable/main Release [85B]
Fetched 85B in 0s (350B/s)
Failed to fetch http://bindist.finkmirrors.net/10.15/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
Reading Package Lists...
Building Dependency Tree...
E: Some index files failed to download, they have been ignored, or old ones used instead.
### execution of /opt/sw/bin/apt-get-lockwait failed, exit code 100
WARNING: Failure while updating indexes.

ERROR: Bootstrap phase 2 failed!

**Comment by Batshua** [comment]
I see a similar issue was open which I wasn't able to find before.

**Comment by nieder** [comment]
fink/fink#227

Build finished OK, but you might also want to turn off using the binary distribution (not present on 10.15) by editing the file /opt/sw/etc/fink.conf.
