### ISSUE TITLE
xinitrc package fails with Xquartz 2.8

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#792]
See XQuartz/XQuartz#167

Our xinitrc package needs to be made aware of the new /opt/X11/etc/X11/xinit location.

If no response by maintainer, my plan is to make a new repo here with the code from the last release (v1.5), then fix and release a new version.

**Comment by dmacks** [comment]
Looks like the Todai group had been keeping the codebase in fink CVS on Sourceforge. Did we ever do a complete transfer of the 'experimental' module to github?
```
cvs -d:pserver:anonymous@a.cvs.sourceforge.net:/cvsroot/fink co -P -d xinitrc experimental/todai/xinitrc
```

**Comment by nieder** [comment]
Looks like the only parts of experimental that were brought over where experimental/dmacks and experimental/thesin as branches to fink/fink-distributions.

Who did our initial git import? Would be nice to get the author mapping file they used.

**Comment by dak180** [comment]
> Who did our initial git import? Would be nice to get the author mapping file they used.

@nieder that would be me; [dak180/fink-distsConversion](https://github.com/dak180/fink-distsConversion) has all the conversion driver files.

> Looks like the only parts of experimental that were brought over where experimental/dmacks and experimental/thesin as branches to fink/fink-distributions.

That decision was discussed on the mailing list, if I recall correctly, and those parts of experimental were the only ones that anyone expressed interest in at the time.

**Comment by nieder** [comment]
I've got xinitrc pulled from CVS::experimenta/todai and made it into a git repo. Any objections to putting it into github/fink ? Then we can deal with this

**Comment by dmacks** [comment]
Go for it. Should we have an "experimental" repo as a read-only of cvs.sf (now that it's easy to fork things into own repos, no need to have it writable)? Or a "projects" repo for collaboration/development of fink-specific programs other than fink itself?

**Comment by nieder** [comment]
There's a `master` and an `origin` branch` that are at the same place. Does that matter?
<img width="289" alt="image" src="https://user-images.githubusercontent.com/1105137/119226362-46df4a00-bace-11eb-8f58-995008dcf657.png">

**Comment by nieder** [comment]
New repo https://github.com/fink/xinitrc
So closing this to deal with the changes there.
