### ISSUE TITLE
cran modules missing dependencies

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#793]
On my 10.13 box, there are some holes in the dependency tree of the rmods:

- missing cran-magittr-r34 for cran-mstate-r34
- missing cran-magittr-r35 for cran-mstate-r35
- missing cran-magittr-r36 for cran-mstate-r36
- missing cran-mathjaxr-r36 for cran-partitions-r36

**Comment by babayoshihiko** [comment]
I will check them. Thank you.

**Comment by dmacks** [comment]
Fixed by PR #794
