### ISSUE TITLE
[New App Request] Element (Riot)-open source messaging app

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#805]
HI
I want to request Element (Riot) is as an open source messaging app

Website: ​https://element.io/get-started Github: ​​​​https://github.com/vector-im/element-desktop Latest stable: ​​​​https://packages.riot.im/desktop/install/macos/Element.dmg

**Comment by nieder** [comment]
If there's a native DMG provided by upstream, what's gained by building it from source and being managed through Fink?
This one looks particularly hard to build locally since it requires Yarn (which we don't have) and some web based frameworks.
