### ISSUE TITLE
[New Request] Jitsi-open source meeting app

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#806]
HI
I want to request Jitsi is a an open source meeting app

Website: ​​​​https://desktop.jitsi.org/Main/Download Github: ​​​​https://github.com/jitsi Latest stable: ​https://github.com/jitsi/jitsi/releases/download/Jitsi-2.10/jitsi-2.10.5550.dmg

**Comment by nieder** [comment]
Please stop submitting requests for upstream packages without explaining why you need a Fink provided package for apps readily available from the original developer.

**Comment by nieder** [comment]
@dtantono: I've blocked this for 1 day so you can answer the above question.

**Comment by nieder** [comment]
This is a web based app according to source repo. Unclear what is gained by downloading an app that is just a new frontend for the web.
