### ISSUE TITLE
[New Request] vysor-open source smartphone mirroring client

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#808]
Hi
I want to request vysor is a an open source mirroring client

​https://www.vysor.io/ Github: ​​​​https://github.com/koush/vysor.io Latest stable: ​​​​https://github.com/koush/vysor.io/releases/download/v4.1.27/Vysor-mac-4.1.27.dmg

**Comment by nieder** [comment]
No build instructions. Github code are just web pages and Javascript files.
