### ISSUE TITLE
[New Request] Oracle virtualbox-open source virtualisation app

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#810]
HI
I want to request Oracle virtualbox is a an open source virtualisation app

Website: ​​​https://www.virtualbox.org/wiki/Downloads Github: ​https://github.com/mirror/vbox Latest stable: ​​​https://download.virtualbox.org/virtualbox/6.1.22/VirtualBox-6.1.22-144080-OSX.dmg

**Comment by nieder** [comment]
Virtualbox uses FUSE, which is a mess to build on macOS due to upstream not releasing recent source code.
