### ISSUE TITLE
[New Request] Dolphin-open source Wii emulator

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#811]
HI
I want to request Dolphin is a an open source Wii emulator

Website: ​​​https://dolphin-emu.org/download/?ref=btn Github: ​https://github.com/dolphin-emu/dolphin Latest stable: ​https://dl.dolphin-emu.org/builds/9e/de/dolphin-master-5.0-14344-universal.dmg

**Comment by nieder** [comment]
Looks possible to build locally, but needs Qt5-5.9
