### ISSUE TITLE
[New Request] Mozilla Thunderbird-open source email client

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#813]
HI
I want to request Mozilla Thunderbird is a an open source email client

Website: ​​​https://www.thunderbird.net/en-US/thunderbird/all/#G Github: ​​​https://github.com/mozilla-comm Latest stable: ​​​https://download.mozilla.org/?product=thunderbird-78.11.0-SSL&os=osx&lang=en-GB

**Comment by nieder** [comment]
Security dependent app that's easily available upstream and not buildable with an alternative UI.
