### ISSUE TITLE
[New Port Request]Mozilla Firefox ESR-Open Source based browser

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#814]
HI
I want to request Mozilla Firefox ESR is a an open source based browser with long security update

Website: ​https://www.mozilla.org/en-US/firefox/all/#product-desktop-release Github: ​​​https://github.com/mozilla Latest stable: https://download-installer.cdn.mozilla.net/pub/firefox/releases/78.11.0esr/mac/en-GB/Firefox%2078.11.0esr.dmg

**Comment by nieder** [comment]
Security dependent app that's easily available upstream and not buildable with an alternative UI.
