### ISSUE TITLE
[New Request] vlc-open source video player

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#816]
HI
I want to request vlc as an open source video player

Website: https://www.videolan.org/vlc/download-macosx.html Github: ​​​​https://github.com/videolan/vlc Latest stable: ​​​​https://get.videolan.org/vlc/3.0.16/macosx/vlc-3.0.16-arm64.dmg

**Comment by nieder** [comment]
VLC has security issues. Best resolved to let upstream handle packaging and distribution to prevent version lagging.
