### ISSUE TITLE
[New Request] tusk-unofficial evernote client

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#818]
HI
I want to request Tusk is a an open source alternative for evernote client

Website: ​https://klaussinani.github.io/tusk/ Github: ​​​https://github.com/klaussinani/tusk Latest stable: ​https://github.com/klaussinani/tusk/releases/download/v0.23.0/Tusk-0.23.0.dmg

**Comment by nieder** [comment]
uses yarn
