### ISSUE TITLE
[New Request] Ramme-unofficial instagram app

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#819]
HI
I want to request Ramme is a unofficial instagram app

Website:https://github.com/terkelg/ramme Github: ​​​https://github.com/terkelg/ramme Latest stable: ​https://github.com/terkelg/ramme/releases/download/v3.2.5/Ramme-3.2.5.dmg

**Comment by nieder** [comment]
Uses yarn which we don't have, and upstream has archived their repo.
