### ISSUE TITLE
[New Request] IGDM-open source Instagam messaging app

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#820]
HI
I want to request IGDM is a an open source instagram messaging app

Website: ​​​https://github.com/igdmapps/igdm Github: ​https://github.com/igdmapps/igdm Latest stable: ​https://github.com/igdmapps/igdm/releases/download/v3.0.3/IGdm-3.0.3.dmg

**Comment by nieder** [comment]
Uses yarn to build and is an electron based web gui pretending to be an app
