### ISSUE TITLE
[New Request] drawio-open source diagram app

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#821]
HI
I want to request drawio is a an open source diagram app
Website: ​​​https://app.diagrams.net/ Github: ​https://github.com/jgraph/drawio-desktop Latest stable: ​https://github.com/jgraph/drawio-desktop/releases/download/v14.6.13/draw.io-arm64-14.6.13.dmg

**Comment by nieder** [comment]
Is an electron web gui pretending to be an app
