### ISSUE TITLE
[New Request] Deadbeef-open source music player

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#822]
HI
I want to request deadbeef is a an open source music player

Website: ​​​https://deadbeef.sourceforge.io/ Github: ​https://github.com/DeaDBeeF-Player/deadbeef Latest stable: ​​​https://sourceforge.net/projects/deadbeef/files/travis/osx/master/deadbeef-1.8.5-beta2-osx-x86_64.zip/download

**Comment by nieder** [comment]
This one had potential because it's possible to build it as a GTK+2 app (vs the native provided by upstream). But it requires GTK+2 newer than what's in Fink, so it's a no-go.

**Comment by nieder** [comment]
Upstream pushed some patches to make it build with our GTK+2
