### ISSUE TITLE
[New Port Request] Visual Studio Code-open source IDE

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#823]
HI
I want to request Visual Studio Code is a an open source IDE

Website: ​https://code.visualstudio.com/docs/?dv=osx Github: ​​​https://github.com/microsoft/vscode Latest stable: ​​​https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal

**Comment by nieder** [comment]
Needs yarn, which we don't have.
