### ISSUE TITLE
[New Request] Caprine-unofficial Facebook messenger app

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#824]
HI
I want to request Caprine is a an open source facebook messenger app

Website: ​​​https://sindresorhus.com/caprine Github: ​​​https://github.com/sindresorhus/caprine Latest stable: ​https://github.com/sindresorhus/caprine/releases/download/v2.53.0/Caprine-2.53.0.dmg

**Comment by nieder** [comment]
In an electron based web gui pretending to be an app
