### ISSUE TITLE
[New Port Request] unetbootin-open source image flasher

### ISSUE THREAD

**Issue by dtantono** [fink/fink-distributions#825]
HI
I want to request unetbootin is a an open source image flasher

Website: ​https://unetbootin.github.io/ Github: ​​​https://github.com/unetbootin/unetbootin Latest stable: ​​​https://github.com/unetbootin/unetbootin/releases/download/702/unetbootin-mac-702.dmg

**Comment by nieder** [comment]
Needs yarn to build, which we don't have.
