### ISSUE TITLE
[New App Request] IGDM-open source Instagam messaging app

### ISSUE THREAD

**Issue by dtantono1** [fink/fink-distributions#826]
Hi

I already checked on homebrew and macports that this app is not in their repositories. So, I hope IGDM is available on fink and it is a an open source instagram messaging app

Website: ​​​https://github.com/igdmapps/igdm Github: ​https://github.com/igdmapps/igdm Latest stable: ​https://github.com/igdmapps/igdm/releases/download/v3.0.3/IGdm-3.0.3.dmg

**Comment by nieder** [comment]
Requires yarn, which is not available in Fink.
