### ISSUE TITLE
[New App Request] Heroic-Open Source Epic Games Client

### ISSUE THREAD

**Issue by dtantono1** [fink/fink-distributions#829]
Hi

I already checked on homebrew and macports that this app is not in their repositories. So, I hope Heroic is a an open source epic games client and available on fink

Website: ​​​https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher Github: ​https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher Latest stable: ​​​https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v1.8.1/Heroic-1.8.1.dmg

**Comment by nieder** [comment]
Needs yarn and macOS version is only alpha quality according to upstream.
