### ISSUE TITLE
expat update using xz source causes a circular dependency

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#837]
In #832, expat1 was updated to use the .xz source. This causes a circular dependency:

expat.xz source -> pkg xz -> BD: gettext-tools -> Dep: expat1-shlibs 

All base packages need to use non-xz sources.

**Comment by TheSin-** [comment]
no essential can be xz

**Comment by dhomeier** [comment]
Shouldn't those packages then bdep on `xz` rather than just `fink (>= 0.32)`?

Fixed in #838, or does this need a revision bump?

**Comment by TheSin-** [comment]
they can't cause then you can't bootstrap, all essentials can not dep on xz

**Comment by dhomeier** [comment]
> they can't cause then you can't bootstrap, all essentials can not dep on xz

Understood that part, talking about non-essential packages that are using xz sources – I only got an alert about the minimum fink version; in principle those should all have a `BuildDepends: xz`, right?

**Comment by nieder** [comment]
With 0.32.0, xz support automatically installs xz:
```
	* xz archive support.
		* Includes validation check with 0.32 as minimum fink
		  version for .xz formatted archives.
		* Automatic unpacking source files in .tar.xz format.
		* Automatically install the xz package with no need to declare a 
		  BuildDepend when a SourceN is a .xz file.
```
