### ISSUE TITLE
Switch r-base* to readline8

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#842]
The r-base* packages are the last remaining packages using the old readline6 and readline7 libraries. It would be great to upgrade them to use the newer readline8 (often just a switch of dependencies) so we can stop having to support those older ones. Because this will require bumping the Revision (meaning users will be rebuilding), it would be a good time to see if there are any other upgrades or new versions to push. Or I can put up a PR for them if it's easier for you.

**Comment by babayoshihiko** [comment]
OK. Also, I would like to introduce r-base40 and r-base41.
