### ISSUE TITLE
Libtool busted again on 12.x

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#859]
PR #848 updated libtool to support 11.x not just 10.x, but now we have 12.x and the regexp for "modern OS X versions" again fails to match. A generic fix has been proposed upstream: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44605

This was first noticed in fink as a build-failure in graphviz ([Fink-beginners] Unable to update graphviz) that traces back to this underlying bug. Expanding our current hack for 11.x:
```
# Patch configure to see BigSur (Darwin20)
perl -pi.bak2 -e 's|darwin\[91|darwin[912|g; s| 10.\*\)|        1[01].*)|g' configure
```
to include 12.x:
```
# Patch configure to see BigSur (Darwin20/21)
perl -pi.bak2 -e 's|darwin\[91|darwin[912|g; s| 10.\*\)|        1[012].*)|g' configure
```
fixed it there (thanks for testing @nieder!).

First, we should pull the generic fix into our libtool2 package and spread the love to any packages that have the Darwin20 patch already.

More generally, at what point should we stop patching-patching-patching pregenerated ./configure scripts and just start redoing the autools toolchain from its templates?

**Comment by nieder** [comment]
Seems very expensive to regenerate autotools vs a perl one-liner. Currently, the only packages using the darwin20 perl-pie are redland and libiodbc2 (and now graphviz). But I'm ok with either fix.

But we should update libtool2. The TL;DR version of the patch is that only darwin5-8 get flat_namespace, and everything else automatically gets dynamic_lookup, vs the current practice of adding new versions to the globs. It doesn't look like libtool is going to update themselves anytime soon.

**Comment by dmacks** [comment]
I updated libtool via 2e802f17ba2b5d6c21e03911fa686d37dbc2abab; if upstream ever becomes active again, they also have been given links to more general solutions.

**Comment by cooljeanius** [comment]
I think this is what's causing the underlying gcc9 build failure that provoked #874
