### ISSUE TITLE
ztex does not find jni.h header 

### ISSUE THREAD

**Issue by dhomeier** [fink/fink-distributions#868]
Compile step fails with
```
	make -C libusbJava-src -f Makefile.macosx install2
make: Entering directory '/private/var/tmp/fink.build/ztex-140813-4/ztex/libusbJava-src'
gcc -fPIC -std=c99 -Wall -Wno-pointer-to-int-cast -bundle -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/ -I/sw/opt/include LibusbJava.c -lusb -L/sw/opt/lib -o libusbJava.jnilib
LibusbJava.c:9:10: fatal error: 'jni.h' file not found
#include <jni.h>
```
I had `system-java16-dev-16.0.1-1` installed and then ran the latest jdk-17 installer to get `system-java17-dev-17.0.1-1`, but before and after there is no `Headers` subdirectory in `/System/Library/Frameworks/JavaVM.framework/Versions/A`, and no `jni.h` file anywhere in `/System/Library`.
The only `jni.h` I found in Fink space was a fairly old one that came with gcc5-compiler; patching `Makefile.macosx` to point `JAVAINCLUDE` to its direction however let the build succeed.
The JDK installers it turns out placed their headers now instead into
`/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/include` (or corresponding path for jdk-16); on top of that `jni_md.h` there lives in a `darwin` subdirectory. Adding both to the `JAVAINCLUDE` also got it to build. So

1. The `PatchScript` would need to find the correct path version for the `system-java-dev` installed and
2. substitute `JAVAINCLUDE` for both the include path and its `darwin` subdir.

**Comment by dmacks** [comment]
Java is a hell of a moving target:(

My 10.13 with system-java{14,15,16,18}-dev (not java17) has:

* /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
* /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
* /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/include/jni.h
* /System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h

Patches welcome.

**Comment by nieder** [comment]
On 10.14.6 (updated from originally 10.11 with 10.13 in the middle). So I had Apple's Java on this at some point, but now just have oracle:
```
locate [Bubble:~] nieder $ locate /jni.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/include/jni.h
/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/include/jni.h
```
For me, ztex fails.

Upstream is hardcoding JAVAINCLUDE:
```
# $(JAVAINCLUDE) should contain jni.h
JAVAINCLUDE=/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/
```
@dhomeier Do you have jni.h inside Xcode.app or the CLT in /Library/Developer/CommandLineTools ?

**Comment by nieder** [comment]
Also, does this work added to PatchScript?
```diff
 	perl -pi -e 's|-I \$|-I\$|g' libusbJava-src/Makefile.macosx
+	perl -pi -e 's|^JAVAINCLUDE=|$&`xcrun -show-sdk-path`|g' libusbJava-src/Makefile.macosx
```

**Comment by dmacks** [comment]
WFM (my mac is from 2009 and variously upgraded OS since then).

**Comment by dhomeier** [comment]
> Do you have jni.h inside Xcode.app or the CLT in /Library/Developer/CommandLineTools ?

Yes, both (on 10.14.6, for the most part newly set up on Mojave last year):
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Headers/jni.h
/Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home/include/jni.h
/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/include/jni.h
```
The patch works for me, too; easier than the extra path for `jni_md.h`!
