### ISSUE TITLE
cran-* for r41 and r40

### ISSUE THREAD

**Issue by babayoshihiko** [fink/fink-distributions#873]
I would like to modify the existing cran-* packages (rmods/cran-*.info):
```diff
- Type: rversion (3.6)
+ Type: rversion (4.1 4.0 3.6)

- (%type_raw[rversion] << 3.6) gcc5-shlibs | (%type_raw[rversion] >= 3.6) gcc9-shlibs
+ (%type_raw[rversion] << 3.6) gcc5-shlibs | (%type_raw[rversion] = 3.6) gcc9-shlibs | (%type_raw[rversion] >= 4.0) gcc11-shlibs

- (%type_raw[rversion] << 3.6) gcc5-compiler | (%type_raw[rversion] >= 3.6) gcc9-compiler
+ (%type_raw[rversion] << 3.6) gcc5-compiler | (%type_raw[rversion] = 3.6) gcc9-compiler | (%type_raw[rversion] >= 4.0) gcc11-compiler
```

The revision number stays unless the version changes. Buildability will be checked.

Any comment?

**Comment by dmacks** [comment]
That sounds correct.

**Comment by nieder** [comment]
Do we want to distrestrict gcc9 to << macOS12 (not sure it might even need to be << 11) because it keeps failing on build (see fink-users)

**Comment by babayoshihiko** [comment]
> Do we want to distrestrict gcc9 to << macOS12 (not sure it might even need to be << 11) because it keeps failing on build (see fink-users)

So, Distrbution field should be like this?

	(%type_pkg[rversion] = 35 ) 10.9,
	(%type_pkg[rversion] = 35 ) 10.10,
	(%type_pkg[rversion] = 35 ) 10.11,
	(%type_pkg[rversion] = 35 ) 10.12,
	(%type_pkg[rversion] = 35 ) 10.13,
	(%type_pkg[rversion] = 35 ) 10.14,
	(%type_pkg[rversion] = 35 ) 10.14.5,
	(%type_pkg[rversion] = 35 ) 10.15,
	(%type_pkg[rversion] = 36 ) 10.9,
	(%type_pkg[rversion] = 36 ) 10.10,
	(%type_pkg[rversion] = 36 ) 10.11,
	(%type_pkg[rversion] = 36 ) 10.12,
	(%type_pkg[rversion] = 36 ) 10.13,
	(%type_pkg[rversion] = 36 ) 10.14,
	(%type_pkg[rversion] = 36 ) 10.14.5
	(%type_pkg[rversion] = 36 ) 10.15

**Comment by babayoshihiko** [comment]
@nieder No problem, I am still checking if the cran- packages work with R 4.0 and 4.1.

Will drop 

(%type_pkg[rversion] = 35 ) 10.15,

and also for earlier rversion.

**Comment by babayoshihiko** [comment]
[cran-acepack-r.txt](https://github.com/fink/fink-distributions/files/8149624/cran-acepack-r.txt)

This is a sample CRAN package. No distribution restriction for r 40 and 41. Any comment?

**Comment by nieder** [comment]
Missing a comma after the 2nd to last Distribution line `(%type_pkg[rversion] = 36 ) 10.14.5`, but yes, I think that's right otherwise.

**Comment by babayoshihiko** [comment]
> Missing a comma 

Oops. OK, I will commit files soon.

**Comment by babayoshihiko** [comment]
> > Missing a comma
> 
> Oops. OK, I will commit files soon.

Committed and sent a pull request (#897).

**Comment by nieder** [comment]
This was dealt with in #897, no? Can reopen if needed.
