### ISSUE TITLE
ssl-cert issue: issue with /dev/urandom

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#879]
At least on 12.x openssl 3.0.0 has an issue with /dev/urandom

I run this
```
openssl req -config /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.SQLf6YEV -new -x509 -days 3650 -nodes -sha256 -out /opt/sw/etc/ssl/certs/ssl-cert-snakeoil.pem -keyout /opt/sw/etc/ssl/private/ssl-cert-snakeoil.key > /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.unXWMeHF
```

I and get

```
Cannot write random bytes:
0046CB1801000000:error:1200007A:random number generator:RAND_write_file:Not a regular file:crypto/rand/randfile.c:190:Filename=/dev/urandom
```

which means you can't make a cert with openssl 3.0.0 which is kinda show stopper bug for openssl.  I assume that's an input for entropy.

**Comment by dmacks** [comment]
Is this with version 3.0.0, or 3.0.1 that just got pushed a few days ago?

**Comment by TheSin-** [comment]
i   openssl          3.0.1-1      Secure Sockets Layer and Crypto Library
 
but it could be from 3.0.0 as well I'm not sure.

**Comment by dmacks** [comment]
Our ssl-cert looks like it's a bit old...1.0.39, vs 1.1.2 upstream. According to [Debian Bug #990228](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990228), this bug was fixed in v1.1.1.

**Comment by TheSin-** [comment]
odd I'll update it but since it's using a openssl line I find that really had to believe

I ran the openssl line by hand and I get the same error, I assume they must have changed the call then.  I'll updated it tomorrow, see if that helps.

**Comment by TheSin-** [comment]
thanks for finding that report that totally makes sense now.
