### ISSUE TITLE
ocamlbuild and ocaml-findlib conflict

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#880]
Unpacking ocaml-findlib (1.9.1-2) ...
dpkg: error processing archive /opt/sw/fink/dists/stable/main/binary-darwin-x86_64/libs/ocamlmods/ocaml-findlib_1.9.1-2_darwin-x86_64.deb (--install):
 trying to overwrite '/opt/sw/lib/ocaml/ocamlbuild/META', which is also in package ocamlbuild 0.14.0-1

**Comment by nieder** [comment]
WFM:
```
nieder $ dpkg-deb -c ocaml-findlib_1.9.1-2_darwin-x86_64.deb | grep META
-rw-r--r-- root/admin      145 2021-09-18 03:50 ./sw/lib/ocaml/bytes/META
-rw-r--r-- root/admin      983 2021-09-18 03:50 ./sw/lib/ocaml/findlib/META
-rw-r--r-- root/admin     5409 2021-09-18 03:50 ./sw/lib/ocaml/camlp4/META
-rw-r--r-- root/admin      331 2021-09-18 03:50 ./sw/lib/ocaml/bigarray/META
-rw-r--r-- root/admin     1226 2021-09-18 03:50 ./sw/lib/ocaml/compiler-libs/META
-rw-r--r-- root/admin      363 2021-09-18 03:50 ./sw/lib/ocaml/unix/META
-rw-r--r-- root/admin      982 2021-09-18 03:50 ./sw/lib/ocaml/threads/META
-rw-r--r-- root/admin      213 2021-09-18 03:50 ./sw/lib/ocaml/stdlib/META
-rw-r--r-- root/admin      298 2021-09-18 03:50 ./sw/lib/ocaml/str/META
-rw-r--r-- root/admin      172 2021-09-18 03:50 ./sw/lib/ocaml/ocamldoc/META
-rw-r--r-- root/admin      257 2021-09-18 03:50 ./sw/lib/ocaml/dynlink/META
-rw-r--r-- root/admin    14919 2021-09-18 03:50 ./sw/share/man/man5/META.5
```
and
```
nieder $ dpkg-deb -c ocamlbuild_0.14.0-1_darwin-x86_64.deb | grep META
-rw-r--r-- root/admin      200 2021-09-18 04:07 ./sw/lib/ocaml/ocamlbuild/META
```
I know nothing about ocaml but managed to get a lot of that stuff to work about 6 months ago. Can't say if I tried to have those 2 installed at the same time, but my debs don't have the file collision. Was your copy of ocaml-findlib built with ocamlbuild already installed? Wonder if it tried to do an internal install of ocamlbuild...

**Comment by TheSin-** [comment]
they were debs so I'm not sure, that is a valid point, maybe ocamlbuild needs to be a depends and build depends?

I'll try to rebuild it and see, I'll capture the deb contains before and after as well.

**Comment by cooljeanius** [comment]
Has dup #1074

**Comment by cooljeanius** [comment]
> Has dup #1074 (affects coq and coq-doc)

From that bug: does anyone know if the proper handle for Heejong Lee (the maintainer listed for ocaml-findlib) is @HeejongLee-aws or @ihji or something else?
