### ISSUE TITLE
openmpi-1.10.7-5 hardcodes flag-sort into lots of files

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#884]
revision 5 of openmpi uses flag-sort. This gets propagated into a lot of files, including opal_config.h, wrapper-data and some executables:
> include/openmpi/opal_config.h:#define MCA_io_romio_COMPLETE_CONFIGURE_FLAGS " FROM_OMPI=yes CC='flag-sort -v -r gcc' CFLAGS='-O3 -DNDEBUG -finline-functions -fno-strict-aliasing ' CPPFLAGS='   -I/sw/include -I/sw/build.build/openmpi-1.10.7-5/openmpi-1.10.7/opal/mca/event/libevent2021/libevent -I/sw/build.build/openmpi-1.10.7-5/openmpi-1.10.7/opal/mca/event/libevent2021/libevent/include' FFLAGS='' LDFLAGS=' -Wl,-flat_namespace   -L/sw/lib' --enable-shared --enable-static  --prefix=/sw --disable-aio"

```
bin/ompi_info:
  Wrapper compiler rpath: unnecessary
              C compiler: flag-sort -v -r gcc
     C compiler absolute: /sw/bin/flag-sort
  C compiler family name: GNU
      C compiler version: 4.2.1
            C++ compiler: flag-sort -v -r g++
   C++ compiler absolute: /sw/bin/flag-sort
           Fort compiler: gfortran-fsf-11
       Fort compiler abs: /sw/bin/gfortran-fsf-11
```

**Comment by dmacks** [comment]
[43f2b13](https://github.com/fink/fink-distributions/commit/43f2b131a80870c3487558f9e92cdd431d2fc0e4)
