### ISSUE TITLE
openssl latest updates breaks postgresql on macOS 10.12

### ISSUE THREAD

**Issue by wodev** [fink/fink-distributions#888]
with the latest openssl updates 1.1.1.l/1.1.1m or openssl 3.0,x a start of postgesql is no longer possible on macOS 10.12. 
Reason for this is that openssl switched to the Apple Crypto Random API which is not correctly implemented on macOS 10.12 and prior.

Disabling the Apple Crypto Random API in OpenSSL with parameter OPENSSL_NO_APPLE_CRYPTO_RANDOM solves the issue. on macOS 10.12.

see also the issue from the PostgresApp: https://github.com/PostgresApp/PostgresApp/issues/643

**Comment by dmacks** [comment]
#889 closed by f49c59e8481c5ff6f958ba783d6a6c1c32cab31e
