### ISSUE TITLE
update libtool to v2.4.7

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#906]
Libtool was updated in March to include patches for properly recognizing various macOS releases:
https://git.savannah.gnu.org/cgit/libtool.git/commit/?id=9e8c882517082fe5755f2524d23efb02f1522490

**Comment by dmacks** [comment]
4279a4dc397afb4ee80ecc98aac883d9593c140f (same day this ticket was filed, not sure why I didn't see/remember-to-close it)
