### ISSUE TITLE
Request to register the domain hnd.jp.asi.finkmirrors.net

### ISSUE THREAD

**Issue by okayamat** [fink/fink-distributions#916]
I am not sure why (and since when), but hnd.jp.asi.finkmirrors.net cannot be resolved currently. Could you please revive the following host names? 165.242.110.160 is still alive (serves rsync and distfile mirror).

165.242.110.160 hnd.jp.asi.finkmirrors.net
165.242.110.160 distfiles.hnd.jp.asi.finkmirrors.net

**Comment by nieder** [comment]
I think @TheSin- is in charge of domains or knows who is.

**Comment by TheSin-** [comment]
It’s me or cirdan, I’ll get it is sort once I’m back home since I’m camping atm

**Comment by nieder** [comment]
ping

**Comment by beren12** [comment]
Fixed. It's been gone a long time, we had to recreate the dns when the orig server hosting it went awol, and we weren't sure if we got it all.
