### ISSUE TITLE
libiconv on 13.x

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#938]
libiconv needs groff during the man page generation, 13.x no longer has groff avail, since this is a package required for bootstrapping we can't just add a BD on `groff` unless we add it to the bootstrap and set it to essential, can we just turn this part off maybe?

```
groff -mandoc -Thtml man/iconv.1 > man/iconv.1.html-t
/bin/sh: groff: command not found
```

This is a blocker for me finishing my working on M1/M2 bootstrapping for fink

**Comment by dmacks** [comment]
Fixed via d8b27df50147543f755c663daeb4fbff5eb94d17 (pushed to stable as one component of PR #939 testing)
