### ISSUE TITLE
xft2 on arm configure hangs

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#949]
On arm only `pkg-config --exists --print-errors "xrender >= 0.8.2"` which is run in the xft2 configure script, hangs.  Running it by hand it hangs, but on x86 it returns immediately.

This makes xft2 impossible to build on arm

**Comment by dhomeier** [comment]
ppkg-config (`PKG_CONFIG=%p/bin/ppkg-config`) should work, or alternatively the new `pkgconf` from #923.
Will push more arm64 ports, but haven't had time to address the reviews to those already posted so far.

**Comment by TheSin-** [comment]
I haven't had time to push deeper yet on it.

**Comment by dhomeier** [comment]
IIRC `pkg-config --libs` actually still worked, but `pkg-config --cflags` hangs as well on this and a couple other libs.
One more reason to push forward #918/#923.

**Comment by nieder** [comment]
Weird that parsing a text file would cause a hang, and only on some .pc files (or is it for any .pc file check with `--exists --print-errors`)?

**Comment by TheSin-** [comment]
that's a good question, I'll do more testing on it tomorrow, I'll also run it with sudo see if it's a weird perms thing

**Comment by TheSin-** [comment]
just tested with ppkg-config and it works perfectly.  Since pkg-config uses ppkg-config it's self to build, which means ppkg-config will be installed, make we shoudl rename the pkg-config binary to pkgconfig and use u-a so ppkg-config is png-config ?

**Comment by TheSin-** [comment]
Just modified xft2-dev.info and added PKG_CONFIG=%p/bin/ppkg-config before %{defaultscript} in CompileScript, and it worked, fixed configure for xft2 and is now built and it's moving on to tcltk now.

**Comment by TheSin-** [comment]
tcltk isn't playing nice with the PKG_CONFIG ENV var sadly so it gets stuck at "checking whether to use xft..."

I tried using `export` at the top I tried setting it before each of the 2 ./configure calls.

I seems to make it through lots of the configures, looks like the one in `tk8.6.10/unix` is the one that fails and one respect PKG_CONFIG var.

Yup it has a hardcoded pkg-config, so I'll have to Patch it out.  Fixing pkg-config would be much simpler it seems, or using u-a to move pkg-config to ppkg-config

**Comment by dhomeier** [comment]
> just tested with ppkg-config and it works perfectly. Since pkg-config uses ppkg-config it's self to build, which means ppkg-config will be installed, make we shoudl rename the pkg-config binary to pkgconfig and use u-a so ppkg-config is png-config ?

The idea from https://github.com/fink/fink-distributions/pull/923#issuecomment-1193348111 was to use `pkgconf` as a full replacement, though I have not fully understood @dmacks's suggestion to introduce it as `Replaces` but not `Conflicts` `pkg-config`, or at least not how to handle this without `Provides` as well (so packages would not all need to be updated to `BuildDepends: pkgconf`).

**Comment by TheSin-** [comment]
Using u-a will likely be required, as Replaces and Provides won't work with versioned BD sadly.  But that being said I guess we should fix see if there is a versioned BD.

**Comment by TheSin-** [comment]
Fix committed
