### ISSUE TITLE
Kill off octave364?

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#950]
We currently have octave364 and octave382, each with a ton of varianted octmods. Apparently a bunch of octmods are tied to octave itself being built with a specific gccXX, but octave changed compilers a year without the mods keeping up. As a result of "Depends:liboctaveXXX-gccAA-dev" but "octaveXXX:Provides:liboctaveXXX-gccBB-dev", there are a ton of unbuildable packages. Given 364 is ancient (NB: even 382 is very old, though the newest we have), I propose we kill off octave364 and its mod set rather than working on fixing all its dependencies and having to keep everything in sync as we keep having to move to yet-newer gccXX on future platforms.

Pinging @dhomeier  who had worked on liboctave gcc migratiouns

**Comment by nieder** [comment]
Kill it.

**Comment by dmacks** [comment]
kill it "kill it", or dist-restrict to some level? I have no objection to hard-kill.

**Comment by nieder** [comment]
It's [10 years old](https://wiki.octave.org/Release_History). No sense in keeping it.

**Comment by dmacks** [comment]
Sent up-state, where it can run free.

**Comment by nieder** [comment]
A handful of octmods are left as gcc5. octave-3.8.2 itself is using gcc11.
```
$ grep -r ^Type: * | grep gcc | grep \(5\)
libs/octmods/tsa-oct.info:Type: oct (3.8.2), forge (tsa), gcc (5)
libs/octmods/fl-core-oct.info:Type: oct (3.8.2), forge (fl-core), gcc (5)
libs/octmods/odepkg-oct.info:Type: oct (3.8.2), forge (odepkg), -blas (-atlas -ref .), gcc (5), lapack (3.5.0)
libs/octmods/econometrics-oct.info:Type: oct (3.8.2), forge (econometrics), gcc (5)
libs/octmods/nan-oct.info:Type: oct (3.8.2), forge (nan), -blas (-atlas -ref .), gcc (5), lapack (3.5.0)
libs/octmods/general-oct.info:Type: oct (3.8.2), forge (general), gcc (5)
libs/octmods/control-oct.info:Type: oct (3.8.2), forge (control), -blas (-atlas -ref .), gcc (5), lapack (3.5.0)
libs/octmods/fits-oct.info:Type: oct (3.8.2), forge (fits), gcc (5)
libs/octmods/optiminterp-oct.info:Type: oct (3.8.2), forge (optiminterp), -blas (-atlas -ref .), gcc (5), lapack (3.5.0)
libs/octmods/dicom-oct.info:Type: oct (3.8.2), forge (dicom), gcc (5), gdcm (2.4)
```
I can't build octave right now, but can these be switched to gcc11 ? That would leave pdftk as the last gcc5 user (already dist restricted) and there's a [pdftk-java port](https://gitlab.com/pdftk-java/pdftk) that apparently doesn't need gcc5 and all the cool distros are using.

**Comment by dmacks** [comment]
Switched, along with some other cleanups in  a37904d. One of those grep results is a red herring; ```Type: gcc(_)``` is part of akh's boilerplate for octmods (and some even list 4.9!) even if packages do not actually have fortran.
