### ISSUE TITLE
gawk is x86_64 only

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#951]
in the gawk configure script there is a place that has

```
*darwin*)
    CFLAGS="${CFLAGS} -arch x86_64"
```

So we need an `aarch64-darwin*) before that, or to update gawk so it'll work on Apple Silicon

**Comment by nieder** [comment]
See upstream patch https://git.savannah.gnu.org/cgit/gawk.git/commit/?id=e0b7737930f8a677d3c509f8ce72b9130965ec0a

If we apply that, probably want to get rid of the `m4/pma.m4` chunk at the end to avoid autotools kicking in

**Comment by dhomeier** [comment]
> If we apply that, probably want to get rid of the `m4/pma.m4` chunk at the end to avoid autotools kicking in

Yes, its autoconf requires automake > 1.16.
