### ISSUE TITLE
db53 and db60

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#954]
To work on Apple Silicon both version need to add to the `ConfigureParams`

`--with-mutex=Darwin/_spin_lock_try`

db53 needs it to be changed since one is set and it's wrong anyhow

This will require a rev of since it's a change that will affect the deb in how things are compiled.

Tested on 13.2/arm64 and 13.2/x86_64

**Comment by TheSin-** [comment]
@nieder @dmacks can you confirm sanity before I commit it?

**Comment by dmacks** [comment]
db53 currently has ```--with-mutex=x86_64/gcc-assembly```. Should that be replaced with this new flag?

**Comment by TheSin-** [comment]
yes, I do not believe that wasn't the proper flag, though it did work at the time.  I tested on x86_64 with Darwin/_spin_lock_try and it still builds and works, I just can not test on sub 13.x anymore.

**Comment by dmacks** [comment]
On my 10.13, identical build-transcripts when I use that flag. You had noted a weird TestScript detail, which I also see:
```
cd test/micro; sh test_micro || exit 2
Versions db-[3-9].*.*
test_micro: line 59: test: [3-9]: integer expression expected
test_micro: line 61: test: [3-9]: integer expression expected
test_micro: line 63: test: *: integer expression expected
db-[3-9].*.* run begins: Wed Jan 25 18:05:19 EST 2023
test_micro  -d /sw/build.build/db60-aes-6.0.30-2/db-6.0.30/test/micro/RUN.Macks\
-Factor -i /sw/build.build/db60-aes-6.0.30-2/db-6.0.30/test/micro/configs/run.s\
td...
db-[3-9].*.* run ends: Wed Jan 25 18:05:19 EST 2023
phase test: passed
```
That's because of an attempted shell-variable expansion that wound up using the regex for a range instead of a list that contains the range. Given db53 and db60 are the same in this regard and upstream is dead, I'm fairly sure we don't care.

**Comment by TheSin-** [comment]
So want me to commit the changes then?

**Comment by dhomeier** [comment]
Same on 10.14.6.
As the _spin_*lock mutexes are system functions, I now also tend to think the assembly implementation did not offer any performance benefits.

**Comment by dmacks** [comment]
I pushed 3bcb64a9c1cba67e0e809ad5d0d7c3e177872012, there were some other cleanups I had lurking around for them.
