### ISSUE TITLE
openldap24 soelim 13.x

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#955]
openldap24 requires `soelim` during the build which is in `groff` which isn't available on 13.x so `groff` needs to become a BD.  This brings ghostscript into the dep pool which increases the dep list by lots.  Maybe it can be patches out? but `groff` should be a BD till we figure it out so it's buildable on 13.x

**Comment by TheSin-** [comment]
`groff` dips brings in python27 which can't be built #956 so I can't test if this is the only issue.

**Comment by nieder** [comment]
See #937 for a little discussion on what groff is doing in the package. Some manpages are included in the openldap tarball and others are generated, so not super simple to just patch it out if we want to keep all the existing manpages.

**Comment by TheSin-** [comment]
agreed, I'm just going down the list to getting git and gnupg2 ATM and listing issues so we don't forget blockers.

**Comment by TheSin-** [comment]
Build works on arm64, so as per

https://github.com/fink/fink-distributions/pull/937#issuecomment-1378645707

I'm going to add the BD for now.
