### ISSUE TITLE
asciidoc is python2 locked and old

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#959]
asciidoc was converted to python3 as of 9.0.0 we are on 8.6.10 and 10.2.0 is out.

I can not remember but if 10.9 had /usr/bin/python3 we could just update it to use python3 instead of the current patch to convert python(2) calls to /usr/bin/python2.7

Obviously this would be nice for 12.x+ as well.

**Comment by dmacks** [comment]
data-point: 10.3 has /usr/bin/python only, not python3.

**Comment by dhomeier** [comment]
System python3 is available on Catalina the earliest (I think if explicitly installed via Xcode).
The _current_ 8.6.10 source has also been updated to python3, which can be made to run on 2.7, but with at least some functionality lost in the test suite – see #946. Not sure if I have tried 9.x.

**Comment by dhomeier** [comment]
Well, 9.1.1 builds just as well on 13.2 (or rather better, with a2x.py now updated as well, and no TestDepends needed.
10.x probably requires installation in `site-packages` as a "real Python package", and I don't think we have any provisions for setting this up for system-python.

**Comment by TheSin-** [comment]
Since I have python27 from fink working on arm, we cause just keep it exactly how it is, add python27 as a dep, and change the PatchScript from /usr/bin/python27 to %p/bin/python27 while we come up with a path to upgrade so at least it's installable and usable in the meantime.

**Comment by dhomeier** [comment]
Why pull in a rather heavy (and outdated) Dep to support an also outdated version?
This would also require to save the old (python2) asciidoc-8.6.10.tar.gz and keep it from being replaced by the current (python3) asciidoc-8.6.10.tar.gz – or perhaps downgrade even further to 8.6.9.
If anything I'd consider pulling in python310 on older systems to upgrade all to 9.1.1 (or possibly 10.x).

**Comment by dak180** [comment]
As a user of asciidoc I would prefer going to the latest version rather than trying to make the old one work.

**Comment by nieder** [comment]
Fixed by #946
