### ISSUE TITLE
pth2 fixes for arm64

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#963]
Looks like pth2 needs the same fix as nettle7 did with the conditional to set the --host

```
("%m" = "arm64") --host=aarch64-apple-darwin`uname -r` \
```

in ConfigureParams

Problem is that it already has one

**Comment by TheSin-** [comment]
looks like it'll need more then that sadly

```
Configuring GNU Pth (Portable Threads), Version 2.0.7 (08-Jun-2006)
Copyright (c) 1999-2006 Ralf S. Engelschall <rse@engelschall.com>
Invalid configuration `aarch64-apple-darwin22.3.0': machine `aarch64-apple' not recognized
```

**Comment by dhomeier** [comment]
Works neither with `aarch64` nor `arm64` for me without also updating config.guess, but with that 
```
--host=%m-apple-darwin`uname -r`
```
builds and passes tests just as well. Would have to check yet if `UpdateConfigGuess` does not break older fink/dpkg.

**Comment by TheSin-** [comment]
looks like it works with `arm-apple`

**Comment by TheSin-** [comment]
> Works neither with `aarch64` nor `arm64` for me without also updating config.guess, but with that
> 
> ```
> --host=%m-apple-darwin`uname -r`
> ```
> 
> builds and passes tests just as well. Would have to check yet if `UpdateConfigGuess` does not break older fink/dpkg.

I like UpdateConfigGuess but I can no longer test with older variants :(

**Comment by TheSin-** [comment]
are you able to try with UpdateConfigGuess on dpkg 1.10?

**Comment by TheSin-** [comment]
I'm working on an autotools-dev package from my exp, I might just start to use that and just copy the config.* via PatchScript instead so it works with old fink and new fink
