### ISSUE TITLE
cairo for arm64

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#966]
Looks like

```
UpdateConfigGuessInDirs: build
```

solves it but I need this tested with dpkg 1.10 on 10.x please

**Comment by TheSin-** [comment]
@dhomeier are you able to test this with dpkg 1.10, to make sure it doesn't break there?

**Comment by dhomeier** [comment]
Where is this package?

**Comment by TheSin-** [comment]
just add that line (from the first post) to the current one and build, I need to make sure it won't break on current fink before I commit it, which I can not test sadly.
