### ISSUE TITLE
libharfbuzz0-shlibs arm64 configure hangs

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#967]
This is likely the pkg-config bug for arm64 and this package needs to be migrated to ppkg-config

hangs at

```
checking for GLIB... yes
checking for CAIRO... 
```

**Comment by TheSin-** [comment]
Adding `ppkg-config` to `BuildDepends`

and

`PKG_CONFIG="%p/bin/ppkg-config"` to `ConfigureParams`

Fixes it. If you are good with this I can commit it.

**Comment by nieder** [comment]
If ppkg-config is the new dependency-lite alternative to pkg-config, I'm OK with it for any of my packages that hang on arm64 like this.

**Comment by TheSin-** [comment]
perfect thank you I'll make the changes and commit them.  Appreciate it.

**Comment by dhomeier** [comment]
So are we making this the standard replacement rather than [pkgconf](https://github.com/fink/fink-distributions/issues/918#issuecomment-1163887385)?

**Comment by TheSin-** [comment]
at this point I assume it's on the maintainer, I like how light weight ppkg-config is (plus isn't installed to build pkgconfig anyhow so no new debs at all) and it's a direct replacement.
