### ISSUE TITLE
libde265.0-shlibs thinks arm is arm7 (neon)

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#973]
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I/opt/sw/include -I.. -g -O2 -Werror=return-type -Werror=unused-result -Werror=reorder -std=gnu++11 -DDE265_LOG_ERROR -MT libde265_arm_la-arm.lo -MD -MP -MF .deps/libde265_arm_la-arm.Tpo -c arm.cc  -fno-common -DPIC -o .libs/libde265_arm_la-arm.o
clang: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
asm.S:44:15: error: unknown arch name
        .arch armv7-a
              ^
asm.S:54:9: error: unknown directive
        .fpu neon
        ^

**Comment by TheSin-** [comment]
adding

```
("%m" = "arm64") --host=aarch64-apple-darwin`uname -r` \
```

to `ConfigureParams` fixes it

**Comment by nieder** [comment]
Cf strukturag/libde265#264 and maybe a fix in strukturag/libde265#284?

Also, there's a newer upstream than what we have.

**Comment by TheSin-** [comment]
we could keep this open for the update, but for now to keep fink momentum with arm64 going could we do the `ConfigureParams` fix.  I'm willing to commit it with permission and keep this open for the update.

**Comment by TheSin-** [comment]
committed the build fix for now, left open to new version reminder
