### ISSUE TITLE
libheif1-shlibs build error

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#974]
Likely an arm64 issue, but I no longer have x86 to test if it's a 12.x/13.x issue

```
g++ -DHAVE_CONFIG_H -I. -I..   -I/opt/sw/include -I.. -I../. -g -O2 -std=gnu++11 -Wall -Werror -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -Wno-error=deprecated-declarations -Wno-error=potentially-evaluated-expression -MT heif_unit_tests-conversion.o -MD -MP -MF .deps/heif_unit_tests-conversion.Tpo -c -o heif_unit_tests-conversion.o `test -f 'conversion.cc' || echo './'`conversion.cc
mv -f .deps/heif_unit_tests-encode.Tpo .deps/heif_unit_tests-encode.Po
mv -f .deps/heif_unit_tests-conversion.Tpo .deps/heif_unit_tests-conversion.Po
In file included from main.cc:28:
./catch.hpp:7869:13: error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
            CATCH_BREAK_INTO_DEBUGGER();
            ^
./catch.hpp:7583:79: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
                                                                              ^
./catch.hpp:7562:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:2: note: instantiated into assembly here
        int $3
        ^
1 error generated.
```

**Comment by nieder** [comment]
Upstream commit strukturag/libheif@e7d41416c189fcc88e18bca17d6dbba173cd0c84 has a change right in this section.
Version 1.14.2 is the latest upstream and near as I can tell, still at libN=1.

**Comment by dmacks** [comment]
Feel free to add the upstream patch. Please leave this ticket open, to remind me to work on the new version (there's also a new upstream of the underlying libde256 that includes a bunch of CVE fixes).

**Comment by dmacks** [comment]
libde265 updated. Latest upstream libheif FTBFS in a minor way, but if there's a quick-fix here for our urgent problem may as well do it here for now, I'll give them a bit of time to work on strukturag/libheif/issues/776.

**Comment by TheSin-** [comment]
Committed, leaving the ticket open for update reminder.

**Comment by dmacks** [comment]
I pushed the new version of libheif (so I nuked the patch). Hopefully it now is clean on arm or 12.x/13.x

**Comment by TheSin-** [comment]
confirmed built on arm64 with `-m`
