### ISSUE TITLE
w3m needs UpdateConfigGuess: True on arm64

### ISSUE THREAD

**Issue by sth0** [fink/fink-distributions#981]
The w3m package fails with unrecognized architecture when built on arm platform.  Adding UpdateConfigGuess allows the package to build.  Usually harmless on older systems?

**Comment by TheSin-** [comment]
sadly updateconfigguess on dpkg 1.10 is soooooooo old it can break builds.  It has to be tested on dpkg 1.10 before we can use it sadly.

**Comment by nieder** [comment]
This seems to be the current 'standard' fork of w3m: https://github.com/tats/w3m
Original upstream is dead since 2012. They have a newer config.guess

**Comment by dmacks** [comment]
Pushed [f2b019b](https://github.com/fink/fink-distributions/commit/f2b019b58a4db420bfa179182061a8685af8ae71) as current version of Debian's fork. I only have tested it up to OS X 10.13 though.
