### ISSUE TITLE
gyp-py: using python calls at runtime, needs to be patched

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#985]
gyp is using calls to `python` this needs to be changed to `python27` for py27 and `python3` for all others.

**Comment by dmacks** [comment]
Since each variant is bound to fink's versioned python package, probably best to have it use %p/bin/pythonXX specifically for each.

**Comment by TheSin-** [comment]
okay I'm working on trying to make that happen, this is what I have so far, but since tests where failing before it's hard to see if it matches.

```
        # can no longer call just python, needs to be python27 or python3 now
        if [ "%type_pkg[python]" == "27" ]; then
                PYVER="27";
        else
                PYVER="3";
        fi

        for i in `find . -name \*.py`; do
                perl -pi -e "s,/usr/bin/env python,%p/bin/python${PYVER},g" $i;
                perl -pi -e "s,'python','python${PYVER}',g" $i;
                perl -pi -e "s,'python [\%%]s,'python${PYVER} %%s,g" $i;
        done
        for i in `find . -name \*.gyp`; do
                perl -pi -e "s,'python','python${PYVER}',g" $i;
        done
```

**Comment by nieder** [comment]
Shouldn't this be getting replaced with %type_raw[python] since it's a fully varianted pymod?

**Comment by dhomeier** [comment]
> if [ "%type_pkg[python]" == "27" ]; then
>                 PYVER="2.7";
>         else
>                 PYVER="3";
>         fi

This needs to be `%p/bin/python%type_raw[python]` throughout. `%p/bin/python3` does not even exist unless you install the extra SplitOff2, but that would mangle all the correspondence between Deps and BDeps.

**Comment by TheSin-** [comment]
that was already done before you comments, just didn't update it here yet since I'm still testing.

**Comment by TheSin-** [comment]
this is also required for `arm64` only other wise `-arch i386` gets added

```
        # for arm64 only
        if [ "%m" == "arm64" ]; then
                perl -pi -e "s,i386,arm64,g" pylib/gyp/xcode_emulation.py
        fi
```

**Comment by dhomeier** [comment]
BTW have you considered simply building the PyPI package https://pypi.org/project/gyp-next ?

**Comment by TheSin-** [comment]
okay I think those 2 seem to be working, I'm almost done with nodejs, but the issues now I believe are nodejs issues.

This will need a rev up for those who might have it build on arm already

**Comment by TheSin-** [comment]
No I'm not looking to repackage anything, just fixing

**Comment by TheSin-** [comment]
I need to enable 3.9 for it while I'm at it, nodejs 12 will error with 3.10

**Comment by TheSin-** [comment]
Pushed

**Comment by dhomeier** [comment]
> No I'm not looking to repackage anything, just fixing

Effectively you have already, transforming it into a py-versioned package. That's often actually easier with the PyPI sources, but then 0.4 is also already several years old, so perhaps no guarantee it will work better with current Pythons.

**Comment by TheSin-** [comment]
True if I had done that.  It already had 2.7 and 3.10 I just added 3.9 and made it use fink python it was just setting python or python3 as the interp.  So I didn't really version it I just fixed it.  Regardless it's done now.
