### ISSUE TITLE
ruby26 fails to build with Xcode 14

### ISSUE THREAD

**Issue by dhomeier** [fink/fink-distributions#986]
Linking stage fails on
> linking shared-library libruby.2.6.dylib
ln -sf ../../../.ext/include/x86_64-darwin/rb_mjit_min_header-2.6.9.h include/ruby-2.6/x86_64-darwin/rb_mjit_min_header-2.6.9.h
Undefined symbols for architecture x86_64:
  "__mh_execute_header", referenced from:
      _rb_dump_backtrace_with_lines in addr2line.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is a known issue and supposedly fixed in ruby27 and later: https://bugs.ruby-lang.org/issues/18912
I managed to apply their patches from ruby/ruby#6297 and ruby/ruby#6442 to our `ruby26`, but am still getting the linker error above (same on arm64).

**Comment by nieder** [comment]
Do we care about EOL ruby versions on Ventura? Only rb26 that's not in rb27 is bio-svgenes, and that's been dead upstream for 8 years. Might be easier to just restrict rb20-rb26 to macOS 12 and earlier.

**Comment by dhomeier** [comment]
Ah I missed the rb27 and rb32 packages were already committed (did not find anything when searching PRs earlier this week). Those build both on x86_64 and arm64; only a segfault in the second test iteration and a couple of validation errors on case-[in]sensitive filename conflicts.
I agree I see no need for the older versions on Ventura then.

**Comment by dmacks** [comment]
No objection to dist-restricting old rubyXX. That would also cut down the openssl100 footprint.

**Comment by dmacks** [comment]
There are a bunch of rbXX from even older variants (rb21-rb25) that have not spread even as high as rb26.

**Comment by nieder** [comment]
- IIRC, our glib2-rb and pango-rb only build to rb22 at their current %v. Higher %v requires higher glib2 library.
- hpricot, ronn, and svgenes are abandoned, so no sense in carrying them forward unless really required.
- I've never touched svn-swig-rb.

**Comment by dhomeier** [comment]
> * IIRC, our glib2-rb and pango-rb only build to rb22 at their current %v. Higher %v requires higher glib2 library.

I got glib2-rb27 and -rb32 4.1.0 to build against [glib2-2.59.0](7c1046f), but pango 4.1.0 fails on
`depended gem isn't found:` [gobject-introspection](https://rubygems.org/gems/gobject-introspection) which is not in Fink's yet.

**Comment by nieder** [comment]
all old ruby are restricted. no sense in carrying them forward.
