### ISSUE TITLE
qgis17-py through qgis26-py are unbuildable with current PyQt4-4.11

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#99]
@babayoshihiko

With PyQt4-4.11, PyQt4.pyqtconfig was removed <http://pyqt.sourceforge.net/Docs/PyQt4/build_system.html#module-PyQt4.pyqtconfig>. This causes problems for qgis{17,18,20,22,24,26) to find PyQt4 (qgis28-py works).
````
-- Found SIP version: 4.18
Traceback (most recent call last):
  File "/sw/src/fink.build/qgis18-nograss-py27-1.8.0-11/qgis-1.8.0/cmake/FindPyQt.py", line 5, in <module>
    import PyQt4.pyqtconfig
ImportError: No module named pyqtconfig
-- Found GSL: -L/sw/lib -lgsl -lgslcblas
````
And then leads to build errors:
**qgis17-py:** `/sw/src/fink.build/qgis17-py27-1.7.4-9/qgis-1.7.4/src/core/spatialindex/tools/TemporaryFile.cc:52:3: error: use of undeclared identifier 'close'
  close( fd );`
**qgis18-py:** `sip: Unable to find file "QtCore/QtCoremod.sip"`
**qgis20-py:** `/sw/build.build/qgis20-py27-2.0.1-6/qgis-2.0.1/build/python/gui/sipguipart2.cpp:80202:30: error: 'hideEvent' is a private member of 'QgsMessageLogViewer'
`
Given that these 6 packages are marked as obsolete, and they're unbuildable with the current state of the 10.9 distribution, they should probably be removed from git. Nothing depends on them.

**Comment by babayoshihiko** [comment]
Hi,

it's good time to dump them.  qgis is looking at 3.0.

2018/03/13 19:55、nieder <notifications@github.com>のメール:
